### ISSUE TITLE
Remaining time trigger as percentage of duration?

### ISSUE THREAD

**Issue by ddrak3** [WeakAuras/WeakAuras2#102]
i am trying to get a weakaura to work which glows when a debuff is under 30% duration (feral druid dots for pandemic mechanic)
but since it is only possible to set a remaining time as a clear number eg 3 seconds but the debuff duration time changes with haste and a talent, that is not a solution.

could it be possible to set the remaining time trigger as a percentage (in this case 30%)? i know you can do it with custom code but that is not my speciality :P 
thanks!

**Comment by InfusOnWoW** [comment]
That would be a trap due to how pandemic works, e.g. a debuff extended to 24s with a base duration of 18s, should show the glow at 6s, which is 25% not 30%.

Which debuffs do change their base duration with haste?

**Comment by jesse-greathouse** [comment]
Debuffs may not change their duration, but weapon swing timers do, when you use different weapons. For instance: I'm trying to create a weak aura that tells my classic hunter when to Aimed Shot, by synchronizing with his auto-shot timer. When he gets a new weapon I have to change the condition because the condition can only use remaining duration from a static value. If the duration remaining were to  modify based off of percent, I could use this condition for any weapon, regardless of the weapon.
