### ISSUE TITLE
Quirks in the update code

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1062]
So in this case, the size of the bars (bars are children) is changed when the aura is upgraded even though "Display" and "Size & Position" is unchecked. @emptyrivers said that the size of children is saved in the "Group Arrangement" group. Which I think is a bit irritating. What do you guys think?

[WeakAurasGroupTest.zip](https://github.com/WeakAuras/WeakAuras2/files/2716895/WeakAurasGroupTest.zip)

**Comment by Stanzilla** [comment]
Nope, can still repro https://streamable.com/berk6

**Comment by emptyrivers** [comment]
This is not a bug :)

I think the current situation is correct. In part due to consistency (group size & scale are categorized together, so child size & scale should be to), and in part because it's the only place that makes sense if we want to distinguish placement from general Display Tab options (which everybody seems to agree on). If the author makes a change which involves adding a new child, then the size and positioning (in fact the layout in general, which might be a better name for the category than Group Arrangement) does not necessarily allow for the new child to be added without everything else needing adjustment. And this includes the width and height of children.

**Comment by Stanzilla** [comment]
Well we certainly need to better explain it then, the size changing when I deselect "size" is not great

**Comment by emptyrivers** [comment]
@InfusOnWoW @mrbuds any thoughts on this?

**Comment by mrbuds** [comment]
I missed the discussion about "Group Arrangement", i didn't know this option exists and tbh I would not be against merging it with "Size & Position" (noooo don't beat me rivers)

**Comment by emptyrivers** [comment]
Here is where the request was made:
https://cdn.discordapp.com/attachments/198544915536412683/531842140846686238/image1.png https://cdn.discordapp.com/attachments/198544915536412683/531842140293169172/image0.png

**Comment by InfusOnWoW** [comment]
I haven't followed the discussion too closely, but when I discussed this with emptyrivers on the intial PR.

It's not easy, and certainly not something that can be done 100% correctly. The basic issue is that it isn't easy to merge user and author changes and how they interact, and that there's really not a good way to do this 100% correctly.

I thought Group Arrangement was just the order of the auras in its group. That is inside "controlledChildren". (Which matters for dynamic groups.)

Whereas Size/Positions is basically the subset of display that affects how children are layouted.

**Comment by Stanzilla** [comment]
yeah that was my thought as well

**Comment by InfusOnWoW** [comment]
I reviewed the categorization while working on the new import window. And there's a certain logic to it, also a lot of time has passed without this being a huge problem.
