### ISSUE TITLE
Additional Progress Texture Conditions Properties

### ISSUE THREAD

**Issue by anaseskyrider** [WeakAuras/WeakAuras2#1072]
Add more settings from Progress Textures, Crop X/Y and Rotation in particular, to Conditions.

**Comment by InfusOnWoW** [comment]
After giving this some thought, this is not going to be a trivial addition and thus will not come quickly.

There are a few things that need to be considered and designed:
* As you note (and I agree) the crop paramter depend on the texture.
That means that the crop (and recenter) parameter should be customizable in the "same" way as the texture. Meaning integrating it into a state property/custom texture function would be the right way to do it.
* It's not immediately clear whether the parameters are best provided via crop/recenter or via more generic tex coord setting. I'm more leaning towards tex coords, since that's more general
* A tex coord setting would also allow rotation, so how that interacts with the existing rotation settings needs to be figured out.

* With that said, I kind like the idea of controlling both texture and tex coords via a condition, as that feels very natural. How that should interact with the existing custom texture function/state.texture and the texture set on the display tab is not clear to me.

* And last, there's a open ticket for controlling the icon via a condition. Icons are somewhat similar to textures in that some triggers provide the necessary information, and there's a "manual" setting for these. Though the two differ in what way the manual and the trigger provided information interact. That's unfortunate too.
