### ISSUE TITLE
[Feature] Action: On Click

### ISSUE THREAD

**Issue by Kruithne** [WeakAuras/WeakAuras2#108]
A handy feature for a lot of reasons would be to have an "action" that allows us to define a custom function when a WeakAura is clicked. For editing, this could sit in under the "Actions" tab.

**Comment by InfusOnWoW** [comment]
World of Warcraft distinguishes between frames that can be clicked and frames that can't be clicked. Frames that can be clicked have a far less capabilities, e.g. they can't be moved, resized, rotated, hidden(*) and various other bits. That's so that you can't have a button that automates various bits.

WeakAuras is obviously using frames that can't be clicked since all of those capabilities are core to WA.

There are hacks to add clickable frames to a aura, but those then limit what you can do with that aura and don't work particular well.

(*) They can be made transparent, but they still take mouse clicks.

**Comment by sslebedev** [comment]
@InfusOnWoW Sorry for necroposting, but can you explain what hacks should I use to make it? I am pretty sure I need exactly this. Or maybe using this approach i'll find another solution.

**Comment by InfusOnWoW** [comment]
This is for bug reporting not for help requests.
