### ISSUE TITLE
Masque sometimes not correctly applying to weakauras

### ISSUE THREAD

**Issue by Montrazul** [WeakAuras/WeakAuras2#1111]
**Describe the bug**
I wanted to use Masque together with Weakauras. It works most of the time but sometimes when new auras appearing the masque style is not applied

**Do you have an error log of what happened?**
No error log.

**To Reproduce**
1. Import the following WeakAuras
```
!TA1xZPnoq8pn3JTtmKMM7rcX0WmetgKZ9W9GPY2Yg1iK8yjdH(q)SF7UYgCcqAY0BggqiTA)7V93QKGK4egh(YLWSjSbFoi4ZxKWwNWYXpWHL1MTjSzHtG1ppVOWkCjrbbbFjHTR7VF6QlGlX1zRm1pyKAqzJdJIdxakTINjsIaPt5zpbkRrdAoYOfWfYCsJ2IwX641oVBi1Y2vfWs7kAn8pxTSSuuJIhrUD7g0YDvO(AQ5GQAsfBeAhRPOq(CcB54rS4LS4rlabPtsy3j4k3QdY(qTGKL9q4SzOtluQP5wVBKckITYSDUgoH(De44BadQ5RfTc1GEnRsX3bEelxGxkM8Q7cN9WKhN5f6GptXeNuuSFZ7n5cm0G9R55YgBs0amVAfQI2S6IPF7oSGPKL6E5yhNuAei8kHSCfusgoiHPmCQe64kighGlx3OCY9whtqua8Y99YF02qwj7OnRnkXrBw4RShTFUeSygSZUJ1dctoTJm8O9R2uDgFmtXThhqnwXs)jPi(crHvhhEYFEKhGjjTCn3jWBAZaJIviwQPohRZECCTOeIwF1oFhakKzEtWSMAuf2mHohSlG)EUIRZf5j3a(kG9DCTBcKTmGYwm62PpY6u((wTHGldTm3aak7V((38kU244ukgR5f1aoeAh4oo5DBL5a4EYxVy4vxF1xUEWxVEyW1xCDsXNU8kSlXbTPZR669W8dAGF8TI)E(KD7Qx9dY3kKLT4)9nUt1KlDbMeDIAnx9pqdj5gbb0LYL9uRp11ce66WB7v1uMlh6yrbw630kqvyX7UMl1VFP3Zu8(K31rwnbZC(chB8IWWicdDGHr8SBWRi0W9cMya(feVeH8GzgJk3SvhdhfQ5PkF9Dp94z5gDYSN2DBRxIiSonbLqWNqmsJ1zwJk(XQCegYAA)Tt0W8scCkHGdVXBrtcLEtMcZn3qnfeyAzguADOkGIv2kHTpx3i1w(o7lz6GMjhyCNSICzYdxUscKxmNCne7VGogf3thoURd8JWqFkM0xXp)sQ3ZqPNzwNk1I79HOp4gJPc7BrWx0OuqxpMy)i03egPhs4jHOAesF6wGLAkhCGuVpYAaISWMD5V(ECZtnskbwQaN1OasIumJy5oeZqL9QAtzTWAHWntA7yeihOv9XZFONUNO4Lqip)X4ztJc7nVaU1bZqyh8Za67H03x2gD)ppw5S8XNACZhDccI(qSlwfo5Ok6q2SDP1sU68tUo9CLZph6CtUoZqM(0TNM18mCzq9xGCmmRcAatnoOxSR)R9O)aY0)eJ(gCSE04yanc(1AQDFAeB6THEiOx20gqT65Be1qJDpA3x2C86rFNCUuR5(Ta7(ZXj6uVvFh3KSqVg(9TBhgsCIXUKujS)Y2AiyzfbzJBPxPhj8Bn(pnq6NgYa07Dwp4un77FhHprJ8hCv1Q(VAGicAd7E1hqf(ce9uHR(3fkRysW9A69uqnYsKrp3FI3h6X9V(PdDt3WWblf7F5bj9gWHVCag8j)3p
```
2. Apply `Clean Icons - Square` Masque to WeakAuras
3. Play around with buffs and see the error

**Screenshots**
![auras](https://user-images.githubusercontent.com/13464567/51345803-2f29ce00-1a9c-11e9-8215-f9cf00614202.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes. WeakAuras together with Masque only.

**Which version of WeakAuras are you using?**
Version 2.11.0

**Was it working in a previous version? If yes, which was the last good one?**
Unknown

**Additional context**
Happens most of the time for `Bestial Wrath but it is not reproducable.

**Comment by Montrazul** [comment]
I just found a reproducable case: When I get on a mount. The mount buff showing then is always without Masque Style.

**Comment by asakawa-k** [comment]
I can't reproduce this.

**Comment by Montrazul** [comment]
I tried to use the convert function for the new aura trigger but that broke it. Only one Buff was showing and not all.

**Comment by asakawa-k** [comment]
Yes you'd need to tick the Auto-Clone option after converting. 
Since this is off the topic of the ticket, if you need to discuss that stuff any more come and say hi on the Discord https://discord.gg/wa2

**Comment by Montrazul** [comment]
I found the problem. The WeakAuras group settings are not automatically applied to all existing WeakAuras. 

Example:
On the image you can see the group settings:

![grou_settings](https://user-images.githubusercontent.com/13464567/51425942-7373b600-1be3-11e9-842a-347e943a64d5.png)

I created a new dynamic group containing only wann WeakAura with showing the cooldown for Kill Command. I called it `KC`. I searched in the list of WeakAuras for that specific WeakAura and found:

![kc_settings](https://user-images.githubusercontent.com/13464567/51425960-bd5c9c00-1be3-11e9-8138-42a9912768c5.png)

As you can see the `normal color` does not match with the `normal color` of the parent WeakAuras group. Is that somehow resolveable?

**Comment by InfusOnWoW** [comment]
I could reproduce your original issue, though to me it didn't look like your further comments. What you describe in your further comments, does not match my experience. That would also be something that is under masque's control.

I've made the masque support a bit more robust for the next release, and that should help your initial problem.

**Comment by StormFX** [comment]
I realize this has been sort of resolved, but generally, Masque will apply the parent's settings to a new group. However, since WA allows users to change the aura/group names, this can cause problems with Masque, since that means the WA id won't necessarily match the Masque's group ID, etc. Changing the ID and passing those changes to Masque may cause bloat in Masque's saved variables file since the old group's settings are no longer in use due to the reassignment of the button(s) to the new group. What I would suggest is to have a static, internal ID and then a display name that the user can change.

**Comment by emptyrivers** [comment]
That's planned (see #1039), but we can't act on that until a certain amount of time has passed (migrating today would be too disruptive for our tastes).

**Comment by StormFX** [comment]
Very nice. Thanks for info. :)

**Comment by InfusOnWoW** [comment]
@StormFX how would we use the masque api to have a internal id and a display name? I don't see anything in the api that seems to fit that.

**Comment by StormFX** [comment]
Masque currently doesn't have this implemented, it will be in the next update. I'm not sure how soon I'm going to get it finished (real life, etc), but in the mean time, your users should just use the static ID. Perhaps put a little box at the top of the settings panel for that group that displays the static ID or something.

**Comment by Montrazul** [comment]
Just to give feedback: Since the last update of WeakAuras2 I do not get any issues with Masque anymore.

**Comment by InfusOnWoW** [comment]
@StormFX well we are doing masque "wrong". As the api of masque is clearly meant to be used for a static set of groups, whereas we do have a pretty dynamic set of groups.

If masque had apis to list all groups (which I think is already there), and allowed us to delete orphan groups/rename groups/create groups with settings, we'd use that to keep the list of groups up to date with what is actually using it. Feel free to open a ticket once you have found the time to add any additional api, and we can certainly improve how WA uses masque.

**Comment by StormFX** [comment]
For the most part, Masque does support dynamic grouping. You can create/delete groups on the fly. The problem is that deleting a group doesn't delete the SV settings for that group, since the idea is to remove a group when a particular bar, etc, isn't in use but retain the settings for when it is. In the next update, there will be an additional parameter for the `Delete `method that when set to true will scrub the SV settings.

Additionally, Masque doesn't currently support the renaming of groups as that conflicts with Masque's internal ID system. So to address that issue, the `Group` method will return Masque's internal ID (authors would need to store this ID for subsequent sessions) and then there will be an additional method to refer to a group by its ID. This method will also allow for creating groups with custom IDs (provided by the supporting add-on), to make integration more streamlined. As far as group renaming, I plan to implement something for that as well.

When I get this implemented and pushed, I'll create an issue about the changes and demonstrate how best to use them.
