### ISSUE TITLE
Update Auras as default

### ISSUE THREAD

**Issue by NLZ** [WeakAuras/WeakAuras2#1149]
Currently the default import mode is Create a Copy.
If the Update Auras mode is generally safe to use then I suggest making that the default, as I think the use case is usually more fit to that; its less likely that someone wants to keep a copy of the old auras to tinker with them, they are more likely updating the fast changing auras like Causese's T23 one.

Edit: how do I change the label? :)

**Comment by emptyrivers** [comment]
Apparently I was wrong about moving issues.

**Comment by emptyrivers** [comment]
Ok, so now that I've learned about new features in GitHub, we can talk about this. Originally, we decided on the default behavior matching the legacy for the sake of backwards compatibility. We didn't want people to submit bug reports because they were being careless, essentially. Updating auras like this has actually been around for several months now, (2.7 was the first time it was available in a public release).

@Stanzilla you were the main proponent of sticking to the legacy behavior as default. What are your thoughts?

**Comment by Stanzilla** [comment]
Still the same opinion I guess, as long as we don't have something like undo, people mindlessly just clicking "next" won't cause any permanent damage with these defaults. Open to discussion of course.

**Comment by InfusOnWoW** [comment]
Note, that https://github.com/WeakAuras/WeakAuras2/issues/1150 is about changing the defaults of the Update list to not include "Load".

**Comment by NLZ** [comment]
But the people who are mindlessly clicking next are probably the type who are not modifying the auras they grabbed from the web, thus overwriting with a newer version is probably a non-issue.

In contrast the mindless next clickers are probably having multiple duplicates, creating a mess and potential conflicts in their UI.

**Comment by cont1nuity** [comment]
I have to aggree with NLZ: most people either want an update or would mindlessly create copies of existing weakauras which they would a) not recognize or b) complain about because they throw errors or do not work properly anymore (ScanEvents-Auras throwing double events now, etc...).
Understanding that changing this behavior now would cause some confusion, I propose to set the "update" function as default for companion app updates. In this case you can be 99% sure you want that update.
Another idea: Hooking the dialog from with another WA for easy import cannot be done when having the config open, but it could work for in game sharing.

**Comment by emptyrivers** [comment]
Yeah, no, I’m in no rush to expose the import process to random, untrusted code that the user might have downloaded without knowing any better, if that’s what you meant by that idea you mentioned at the end.

**Comment by cont1nuity** [comment]
Yep, understood. Just took a look at it and it is for the better if it stays where it is.

**Comment by Vardex** [comment]
If they really want to undo we have the companion app automatically backing up the WeakAuras config file.

> Still the same opinion I guess, as long as we don't have something like undo, people mindlessly just clicking "next" won't cause any permanent damage with these defaults. Open to discussion of course.

**Comment by Stanzilla** [comment]
We had something while developing this feature that just remembered what you did last, you guys like that?

**Comment by cont1nuity** [comment]
I would welcome this feature. Neat solution without introducing any config.

**Comment by xanderti** [comment]
hi

**Comment by xanderti** [comment]
Currently the default import mode is Create a Copy.
If the Update Auras mode is generally safe to use then I suggest making that the default, as I think the use case is usually more fit to that; its less likely that someone wants to keep a copy of the old auras to tinker with them, they are more likely updating the fast changing auras like Causese's T23 one.

Edit: how do I change the label? :)

**Comment by xanderti** [comment]
by

**Comment by emptyrivers** [comment]
Did you have something to share @xanderti?

**Comment by Hekili** [comment]
+1 for Update as default.  99% of updates for me involve using Update and then unchecking Display so that style changes I've made are retained.

**Comment by krazyito65** [comment]
Maybe a checkmark for 'remember my decision' ?

I see the reason for both sides.. but when does QoL trump destructive behavior?

I think the best option is some kind of config and let the user decide, but keep copy as the default for new config.

**Comment by emptyrivers** [comment]
After an extremely reasonable turnaround time of one year, I did implement this. With the next release, WeakAuras will remember your last choice when you import a new version of an aura.
