### ISSUE TITLE
[Idea] Import/Export multiple auras

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras2#1183]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I want to import a collection on wago.io.

**Describe the solution you'd like**
I would like to copy an import string directly from a collection and import it. In WoW, I guess the easiest way would be to show import pop-up one after another. I think importing them all in one click would be hard to manage with aura already existing to select if you want to copy or update it. 
Also, the other way around could be useful, selecting multiple auras with ctrl or shift and exporting them. importing them on wago.io would import all the auras and put them in a collection.

**Describe alternatives you've considered**
[Nested groups.](https://www.wowace.com/projects/weakauras-2/issues/64)

**Additional context**
🙅‍♂️

**Comment by jec324** [comment]
After speaking with Rivers I found that the issue/limitation is regarding processing so many groups into a single import string and the potential impacts of that.

**Why do we want this to begin with?**
So essentially with group import/export we're hoping to eliminate large groupings of auras or to provide a bit better organization to the auras themselves.  As an added benefit it might prevent some LARGE aura groups from being developed and solve an issue where users are using the display settings to change these group auras sizes instead of group scale.  Instead of having a massive Raid Auras Group you could have individual boss groups and a Raid Auras Collection of each of those groups

**Previous dialog**
Within the #wow-addon channel for issue #1183, created by Vardex but first mentioned by @Hekili: 

Hekili 06/03/2019
batch import (multiple groups, not nested) from wago collections when?
 
emptyrivers 06/03/2019
Ora has already said no
Because of the bandwidth impact

Rivers then later mentioned: 

emptyrivers 06/03/2019
I’m open to other solutions

**Describe the solution you'd like**

Right now I believe the WACompanion app checks the default folder location for a wow install then checks which auras are within the SavedVariables and checks those versions against wago.io.  I also believe that wago.io verifies users with blizz credentials (I think OAuth2, but I could be totally wrong about this it's not my particular forte) 

I'm not sure how married wago.io and WACompanion can be but a potential solution would be to allow "collections" to be placed in a specific section within the wago.io Users profile.  Say the "Downloaded Collections" for a lack of a better term at this point.  The WACompanion on loading or forced fetch could query the wago.io server for these "downloaded collections" in order to list them.  Then through user interaction, if install is desired, they could click a button and download those auras 1 by 1 through this interface.  This would eliminate the need to process a large single import string.  

**Downside?**

figuring out how to display this info on wago so you don't just have multiple entries by the same user covering the entire first page just listing the individual bosses.

**Comment by emptyrivers** [comment]
jec's comment is really outside the scope of WeakAuras itself. @oratory, @mrbuds, do you have anything to say on this?

**Comment by HereIsJimmy** [comment]
Has this idea been thought out any longer? When making WA's I often see myself using multiple groups for weakauras that should be used together, like a vertical-centered dynamic group + a group of static wa's, or even a weakaura with a nearby unit count script to be used by the other auras. If I want to export this to wago.io it feels so absurd and cumbersome

**Comment by emptyrivers** [comment]
Now that nested groups are a thing, is this still a ticket that needs to be open? I feel like we can close this

**Comment by InfusOnWoW** [comment]
Yeah I tend to agree. Nested certainly has made this more or less obsolete.
