### ISSUE TITLE
Weakauras not importing via chat caused by special symbols.

### ISSUE THREAD

**Issue by Melonoway** [WeakAuras/WeakAuras2#1225]
**Describe the bug**

Whenever I try to share a weakaura that has special symbols in it's name such as [ ] in case, it displays an error "Requested display does not exist"

**Do you have an error log of what happened?**
 

There are no errors in bug-grabber I use it all the time to analyze this stuff in case shit hits the fan. 

**To Reproduce**
 

**Screenshots**

https://i.gyazo.com/dfeb36d5793c885ea6da74a794b8ff4e.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, base blizz + wa's

**Which version of WeakAuras are you using?**

2.11.6

**Was it working in a previous version? If yes, which was the last good one?**

No

**Additional context**

**Comment by emptyrivers** [comment]
This is a fairly standard case of pattern matching being used when a true parser would be more appropriate. See here, where the display name is taken to be a string of characters which are not `]`, but then is followed by `]`: https://github.com/WeakAuras/WeakAuras2/blob/7c00037b69285e8ca11c5b31738d88d5f9e58a4c/WeakAuras/Transmission.lua#L148

Since there already exists a simple workaround (just don't end the names of your auras with a `]`) and we plan to revisit how the database is indexed in the first place (with #1039) which would render this problem moot, I am personally in favor of not fixing this at the moment.

**Comment by InfusOnWoW** [comment]
Even if we internally use a uid, the problem would remain. As this is the text that is shown to the user in a hyperlink, that'll still use the displayname.

**Comment by emptyrivers** [comment]
It seems i've been overruled!
