### ISSUE TITLE
sound loop condition

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#1234]
**Describe the bug**

-expected sound to stop if condition doesn't match
-instead sound continiue to play

Do i need to add stop sound condition and this is intended?
**Do you have an error log of what happened?**
 
no errors
**To Reproduce**
 
1) make any timed trigger like event > CLEU > cast start > timed > 10
2) add condition to play loop sound when time <= 5
3) when sound starts to play cast the spell again to refresh duration back
**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes
**Which version of WeakAuras are you using?**

2.11.6
**Was it working in a previous version? If yes, which was the last good one?**

same issue
**Additional context**

https://pastebin.com/RXptsgP6 hearthstone cast start WA to test. Use hearthstone and stop the cast. Wait when sound will start to play and use it again.
``` HERE ```

**Comment by InfusOnWoW** [comment]
That's by design, which is a bit odd.

Adding a condition that check for remaining duration > 5 and then sound/stop fixes the aura.

The looping sound acts in the same way as if you'd play a very long sound via sound/play. Similarly a long sound file is not automatically stopped if a condition turns false, but just continues until the end. 

Instead there's a explicit "Stop Sound" action that can be triggered as needed.

Having Loop and Play Sound behave in essentially the same way made the implementation easier and there are no corner cases in how Looping Sound and Single Sound effects interact.
