### ISSUE TITLE
Aura's lagging/loading then disappearing then showing again.

### ISSUE THREAD

**Issue by Keksecute** [WeakAuras/WeakAuras2#1235]
The best way to depict the issue is with the clip from stream below:

https://clips.twitch.tv/InexpensiveConfidentMelonTwitchRPG

Weak aura version screenshot below:

![wowscrnshot_030719_221812](https://user-images.githubusercontent.com/48346057/54014720-97ffff00-414b-11e9-818c-80f9d9246957.jpg)

**Comment by mrbuds** [comment]
**Describe the bug**
What did you expect to happen and what happened instead?

**Do you have an error log of what happened?**
If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install https://www.curseforge.com/wow/addons/bugsack & https://www.curseforge.com/wow/addons/bug-grabber, yes both are needed. 
Note that if the error looks like `[string "--[[ Error in ' my awesome aura' ]` then the bug is in the aura that got mentioned, not in WeakAuras itself 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error


**Screenshots**
 If applicable, add screenshots to help explain your problem. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Testing with only WeakAuras enabled is crucial to ruling out conflicts with other addons.

**Which version of WeakAuras are you using?**
You can see the current version in the title bar of the options window, if the options do not open, check the Twitch app or the `## Version:` field in the WeakAuras.toc file

**Was it working in a previous version? If yes, which was the last good one?**
You can always find older versions of WeakAuras to test with at https://www.wowace.com/projects/weakauras-2/files 

**Additional context**
If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\` 

In case you do know which aura is problematic, please export the string and paste it below. 

``` HERE ```

**Comment by mrbuds** [comment]
screenshot show: aura is active when immolation aura is usable
video show an icon of immolation aura when it is usable
i don't see what is your issue

**Comment by cbegs** [comment]
The aura shown in the video loads, dissapears, then loads again. The aura is for immolation aura a demon hunter spell, it’s supposed to trigger once that ability is off CD and usable. The trigger settings is status and action usable (I’ve also tried spell not on CD with similar results)

I don’t have error logs and am not sure it’s considered an error.

I can’t screenshot the problem but the exact issue is shown in the attached clip. 

I didn’t uninstall other addons, but I don’t use elvui and weak auras is likely the largest resource using addon I use. 

Weak auras version.  2.12.0-beta 1 

I believe it was working properly in an older version, problem is I don’t know which versions since there’s been quite a few updates and a few patches that had bigger problems with auras not loading once triggers have been met.

**Comment by mrbuds** [comment]
Ok i see it now, i tried to replicate but i could not.
Can you share you savedvariable file ? You may have to zip it before dragging it on github
Also if you can tell step by step a minimal example on a target dummy how you do to reproduce that would help a lot

**Comment by mrbuds** [comment]
We are waiting for your input to handle your issue. Do you still have it ?

**Comment by cbegs** [comment]
Sorry busy few days. How do i get the file you're asking for?

Also I don't know how to replicate it since it happens intermittently.


Cody Begley
Phone: 513.600.6710<tel:513.600.6710>
<tel:513.600.6710>Email: Codyb88@live.com<mailto:Codyb88@live.com>


________________________________

**Comment by mrbuds** [comment]
> please attach a ZIP archive of your WeakAuras SavedVariables file, it's the WeakAuras.lua file in World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\

**Comment by mrbuds** [comment]
You were asked multiple times to provide more data in ticket and on discord for 3 days.
If you still have an issue please open a new ticket and answer every single question asked in the issue template.

**Comment by cbegs** [comment]
[SavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/2973363/SavedVariables.zip)


Does this work? Still having the issue and am now on weak auras 2.12.0-beta3 version

**Comment by emptyrivers** [comment]
Hi, thanks for providing your savedvariables, that clarifies things greatly. Unfortunately, this is Working As Intended, and you will have to work around it.

To give a bit of background information, the action usable trigger asks the game if the action is literally usable at that moment. This is slightly different from the question, "is this ability ready to be used", and you've found one of those points. Some abilities, like fel rush, or Highmountain Tauren's Bull Rush, or a Monk's Roll (and a few other dash type abilities, if I recall) temporarily pacify the player. Since you're considered pacified for the duration of the dash, the action usable trigger correctly reports that you cannot use that ability. Of course, this conflicts with the common intuition, but there's no perfect solution with the Action Usable trigger.

To work around this issue, you have a couple of options:

1. Edit the problem auras to use Cooldown Progress triggers + other necessary triggers like power. This would be the most direct replacement that would preserve the behavior that I think you desire. Here is an example (it is the Felblade aura in your DH Havoc group, with only the triggers changed).
```
!nA1BVjVnq8pntA7ftIKM9O9QhPcKUIuBGHd7LM6KCj4vh7ihhO0x0p77SDcKcTDvcboxU7NV739pOb0ukHttcUjk6hr)GsAPK5WEkPMskSFWxxjuhOtPed8Ij4oL0q4VcOjHuYXLLLTGbFyYekHjZ3P0RuCPHsMfNKgVMsYvkrH6GKCG3awyY7AnQ6ueSnnfmdqjD9)oOACrfqZq8YnCLS16dTgM2GhqGl5sE7o)z8OxkE2O5vvG2QEIlS6f4pYYFgbSZOWGQtZSatjbyWbsqZZj7uhwIsAD)UgyfhXh6YG9G0SsdL8xOeYQ4hEaThY6kltpIHd5(4hwD3guOX9i6MMoKc7KodhUXUwyRhzlb0)Qz9r7BpTsRQ0qB7Bp9RKgqi(nlayGrAeSJyaq0at4EtcRgVL7arMGva9aF6fi2Uhwu06PhjkT)4qSqqx3glBNDljDlj921PEyEprm1l0ZBd46UKKWGBcJcSy2jhrXFbrAtpjHxMs(kcRrDa0BvnaMPuib8ZlYA9kVYQM3tDe20pnN9E(0AalRvPZEuvaJn7tPhNhz10FGen5sgWveAlz3dPEHoWtc8fQgqlzI)blqTbb2WrjpdqZTiZMBwBdnxjVKx7dZrf9NI9T9KgKRKyoUNdLkjyVJAgxEMzBWkkWC(3mvNmh(uSg3y99UpJTHvO0((n7Nq3334(oQpWlGwmdRT93z(rjZ()nYnPPFoY0LPPlFC9I)6(u)lcTJGUtWQqhA5M0hwKetj7aE1oSklAIRechdTSzy4bcIqXCJY4YkTQRXESUty4dPTCbR1pNb1qGX484hxMC)g)iS3PQRTGjS1F9njEJXhWMf4kO7BrZDvz2bNxQGhSWpr(iNcjPtAG020Z4Vh2XZfog2DvJSj4JSPGJv55O4JxDRL(HUxjVzFZzh6QamxvNXori9UZgU1H0kXvXSR0rwWhLHCz2lwDWrLgw8eodZ6ybETRXFrczX8yF9KFqCwNXOKl3dAShF0UkCAPM)6Bp93DScSkK92tP2oAoUC7()nmDw2FKUOjEuL1hBWj8USWtdvyq49bN)2Vf8onoS0lMmBDCCs)velzzcOWYmNUs)(0Wih7DUfj7uK)9AyOKFb9SxvQAAYKZBtTBANZBF)1I620pSfj4sRZAxsAyUkgl7CEjJd8VHtWen782FGxy25Bg7n(dYDizvYRg2JJjUwyW9cgXsTGO8I6IcERDs(chDBhtYZF(48H9dOnVm83s(9G)0nNEp6wrHwVK(Fd
```
2. Have your auras appear always, and change appearance when they are ready to use. Conditions are useful for this, and you can check out the templates feature to see some examples which won't take too long to set up.
