### ISSUE TITLE
Hold Shift to Align - Not align by default.

### ISSUE THREAD

**Issue by timtrousdale** [WeakAuras/WeakAuras2#1273]
It is extremely frustrating that you now have to hold shift to move anything without the auto aligner. 

The alignment tool added is a fantastic addition... but making it the default movement option is frustrating. I have used weakuaras for years and was extremely annoyed that I now have to hold shift to move anything the normal way. Adding an extra step if I don't want it auto-aligned to whatever the addon thinks it should be aligned to.

Having to hold shift to disable alignment is not the best UX design. Please swap these.

**Comment by InfusOnWoW** [comment]
We think having it as a default suits more people.

**Comment by krazyito65** [comment]
Maybe add a new option for a window?  
`/wa opt` and just shows misc options like not using shift by default?  I feel like there have been other small options like this in the past that have just been said 'we don't have an options menu so theres no point in putting it'  Maybe we should start slowly adding some kind of options that we can extend upon for the future?

**Comment by InfusOnWoW** [comment]
I think the vast majority of people won't even realize we have such a nifty tool when it's hidden behind a modifier. If it truely turns out that it annoys too many people, and I see no indication for that, then we need to figure out a way to make it configurable.

But switching the default is not the way to go.
