### ISSUE TITLE
Use by default a font that support local language.

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1318]
We use Friz Quadrata TT as default font right now, i don't know exactly the extent of which languages are supported by this font, but it doesn't handle asian fonts & cyrillic afaik.

WoW use globals like GameFontNormal, maybe it's possible to register them automatically on libsharedmedia and use them as default.

While not a "breaking change" per say, changing default font would change old behavior for people used to Friz Quadrata TT, but would improve quality of life for people for which their locale is not supported by Friz.

- Is it something that we are willing to change or not ?
- I haven't investigated enough myself on the possibility to add default fonts to SharedMedia, do you think it can be problematic ?

**Comment by emptyrivers** [comment]
Everything already goes through SharedMedia which is designed to handle this kind of thing, or it uses STANDARD_TEXT_FONT.

If a font is not registered with LSM as compatible with a particular locale, then when attempting to fetch it you will receive a fallback font that works ok.

Are you reporting this because users have mentioned that the default region fonts don’t work?

**Comment by mrbuds** [comment]
I misunderstood a problem reported on discord by someonetrying to use the various fonts offered by LSM not working for cyrillic, but he confirmed default font works fine.
