### ISSUE TITLE
Bar progress towards center

### ISSUE THREAD

**Issue by efremzero7** [WeakAuras/WeakAuras2#1413]
I just wish it was possible to make a bar progress towards its center, starting from both ends, and finishing at the middle. Is there a way to do this that im missing?
i thought about simulating it with two bars, but i wish there was that option on the orientation drop down menu. Thanks!

**Comment by 1ps3** [comment]
As far as I can tell this isn't really possible due to the nature of the progress bar region type. It's a bunch of textures, not a status bar. Status bars have the option of using `StatusBar:SetFillStyle(style)` to change the fill style of the bar. So it'd probably require a load of work to do this.

**Comment by InfusOnWoW** [comment]
This is too fringe for my taste and also easily accomplished by having two bars.
