### ISSUE TITLE
Advanced import options

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1467]
**Is your feature request related to a problem? Please describe.**
Users came forward to me with few issues:
a) changing fonts lags them out and even with the update feature, users are forced to change newly added aura's font manually. (it can be hard to detect which aura was added in the recent update in big dynamic groups)

b) they want to move the aura's used sound channel to a different one, same issue as above.

**Describe the solution you'd like**
upon importing, there could be an advance options collapse thing that allows you to specify "import conditions?", where you can choose which font/sound channel the imported auras etc should use and then it basically overwrites the default ones to w/e you chose.

**Describe alternatives you've considered**
custom options for dynamic groups that overwrites data stuff

**Comment by emptyrivers** [comment]
That’s what #1428 is for.

**Comment by emptyrivers** [comment]
Well, ok for some more context: no I don’t think your solution is a good one, primarily because it would be rather hard to use for most people. A better solution for most cases is to distinguish changes that originate from the user, and changes which originate from the author, and merge them when possible. This requires snapshots of the data’s history.

**Comment by emptyrivers** [comment]
I think between the default options/themes ask, and various improvements to updating in the pipelines, the ask in this ticket is covered by others. So I'll close it.
