### ISSUE TITLE
Item trigger somehow exports the stack count via %p

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1474]
**Describe the bug**

Follow up to https://github.com/WeakAuras/WeakAuras2/issues/929
item trigger somehow exports the stack count via %p instead of %s

**Do you have an error log of what happened?**
 

**To Reproduce**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by asakawa-k** [comment]
I think it's *fairly* reasonable for the count value to *be* a count trigger's "progress". However there have certainly been plenty of people come to the Discord over the years asking why %s isn't returning the value they expect so it's certainly counterintuitive to many. 

If you "fix" this then please do ensure that it also stays on %p because a lot of people do use it as it is right now.

**Comment by Stanzilla** [comment]
Considering %s seems to return nothing, it would be perfectly fine to just return the same for %p and %s in this case
