### ISSUE TITLE
Add a "count" setting/value to Event type triggers

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#1508]
**Is your feature request related to a problem? Please describe.**

People very often want to catch things like the 3rd boss cast in combat. There are workarounds to achieve this but would be nice if it was handled by WA itself. 

**Describe the solution you'd like**

When an Event trigger is made, WA counts each time the specified event occurs. This could reset on the Aura loading, allowing users to have the count reset on combat, or encounter, or even zone, etc.     
Event triggers would include a "count" setting so that people can specify a count on which to activate, but also, without using that setting, the count could be carried for output in `%count` or whatever.  Bonus points for the count setting to accept multiple values!

**Describe alternatives you've considered**

Custom triggers, generic triggers with custom code in Conditions to keep count, using boss mod triggers for their count. There are other options but all awkward in their own way.

**Comment by InfusOnWoW** [comment]
Yeah, that comes up regularly on the discord, let me gather a few cases where !spellcount was suggested:

* "Hey guys, I'm really super new to writing WAs, but I'm trying to figure out how to  create a WA that will track which rippling wave we're on for mythic Ashvane. Potentially more complex as we go on, like stating which cooldowns are being used... but for now just a simple one to track which rippling wave we're on.
Anyone feel like giving me some direction?"

* Is it possible to make a Weak Aura that counts the amount of times a boss has casted a certain spell?

* Could someone help me with some adjustments on this WeakAura:

https://wago.io/spellCounter

I'm trying to figure out how to make it so that it will only show up for about 10 seconds when it gets to a certain spell count. So it's hidden, then pops up when the counter hits 2, 5, and 9.
Spell Counter
This is a template, designed to have as few moving parts as possible. It will count the # of times that an event of your

* I have a hopefully fairly simple problem: How do I make a WA that triggers after the Nth cast of a boss ability? Say I want a WA to scream at me at the third time the boss uses "big boss attack", how would I go about that? I assume custom trigger, have some sort of counter variable that ticks up whenever the ability is cast (somehow?), am I on the right track?

Seems like a commonly needed thing. Is there a snippet/library?

* Any Glorious soul knows how to make that "Check interrupt" Appear, when it is your time to kick? 
To which asakawa suggested spell count. This is was for Uunat, which is certainly a bit too complex, since it featured 3 adds, and somehow we would need to trak per guid? and reset on guid death?

* i want to count  each mangoost bite spell  during  my coordinated assault.

* hey, i'm tying to make a weakaura that tracks the amount of times i've used roll the bones during a dungeon, what kind of trigger would i be using to track not only the first, initial roll the bones but also refreshes?

* Does anyone have a WA for counting how many times the boss casts a certain spell? I tried this but couldnt get it to work: https://wago.io/spellCounter

* Is there a template for tracking number of times boss has casted x ability?

* Well, the spellcounter works as intended now for me. The only thing that bugs me is that it is always showing. I'd like to have it only visible when that cast is happening and then hiding again after a set amount of time. But that doesn't work due to the always active trigger, without that the WA can't count, of course.

====
I stopped there. Apparently:
* The most often use case is counting boss abilities. (Don't people pay attention to their boss mods anymore?`)
* The wish to count the number of mangoose bites while coordinated assault is active is interesting
* The Roll the Bones during a dungeon, when would that reset?
* Apparently some want the aura to always show (which I think is how the template works), whereas others want it to only show on a certain count
* This is exclusively combat log events.

**Comment by asakawa-k** [comment]
> The most often use case is counting boss abilities. (Don't people pay attention to their boss mods anymore?`

Some of this definitely overlaps heavily with Boss Mods (and the WA BossMod triggers). They are (perhaps unavoidably) finicky though. You could argue that a Combat Log trigger is on a similarly level of finicky but I see why people would want to use one for this kind of purpose. 

> The wish to count the number of mangoose bites while coordinated assault is active is interesting

> The Roll the Bones during a dungeon, when would that reset?

I imagine that the count would reset on Load. This would make the RtB one simple but the Mongoose Bite one difficult. 

> This is exclusively combat log events.

Would it need to be though? I don't think I've ever seen anyone ask for a count for the other Events provided by WA but I could see someone wanting to see a count of CD Ready events or something. Like, maybe not worth much effort but if it's easy to implement once it's made then I wouldn't avoid putting it in to all Event triggers.

**Comment by InfusOnWoW** [comment]
Well, it might be that the solution involves adding a count to all event triggers, but the first step is to step back from the proposed "solution" and figure out what problems we are trying to solve.

E.g. "time since encounter start", "time since last cast" sound like a related problem, but that wouldn't really fit into the cleu trigger.

**Comment by Causese** [comment]
> The most often use case is counting boss abilities. (Don't people pay attention to their boss mods anymore?
bossmods (atleast bw) doesn't count everything. they tend to miss adding a count to relevant stuff but usually implement it upon request

there were also casts in the past that are exclusive to UNIT_SPELLCAST_SUCCEEDED events and don't fire for SPELL_CAST_SUCCESS but the majority doesn't know about these anyway

**Comment by eyriewow** [comment]
>bossmods (atleast bw) doesn't count everything. they tend to miss adding a count to relevant stuff but usually implement it upon request

They are also, unfortunately, somewhat arbitrary on how those counts work.

For example, BigWigs on Ashvane resets the count of each boss ability once the boss regains the Hardened Carapace buff.

This makes it tough for the average WeakAuras user who doesn't know anything about custom code to make an aura that, for example, triggers on the third cast of rippling wave on Mythic to remind them to use a cd or something (for my guild this would be the first cast in second phase 1). 

If you used a BigWigs trigger with count == 1 it would trigger on the first rippling wave in *each* phase 1, something the user doesn't want.

**Comment by mrbuds** [comment]
This was covered by https://github.com/WeakAuras/WeakAuras2/pull/4335
