### ISSUE TITLE
Raise Text frame level above glow

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1519]
Currently with glow enabled, text on the edge is a level below the glow, making it hard to read, we should raise it above it.

![image](https://user-images.githubusercontent.com/75278/62485349-be8a9a80-b7bc-11e9-8ead-3cc1db599d84.png)

**Comment by emptyrivers** [comment]
Related: #1531

**Comment by InfusOnWoW** [comment]
The glow lib uses the base frame level and adds a +8 to it. Due to #1531, we can't add +9 to each text frame, as that would then show up above icons in the same group.

Thus, this needs to be first fixed in the glow library. Feel free to ticket that, and or fix it, and after it is fixed, reopen the feature request.

By that time we hopefully extracted the glow thing into a sub element, which can then be reordered between all sub elements.

**Comment by Stanzilla** [comment]
Keeping this open for Buds to track

**Comment by mrbuds** [comment]
it's @Dooez 's lib stan

**Comment by Stanzilla** [comment]
oh shoot

**Comment by Stanzilla** [comment]
So, lib has changed, what do we do now?
