### ISSUE TITLE
Group summary (blue text) wrong with new texts

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1560]
Example group https://wago.io/nPdaIno7o

![image](https://user-images.githubusercontent.com/75278/62886588-afb36300-bd3b-11e9-83f9-f950b0beee86.png)

most stuff is blue even if it's the same info, also the font tooltip looks pretty broken

![image](https://user-images.githubusercontent.com/75278/62886613-bc37bb80-bd3b-11e9-8691-3beaf825091f.png)

**Comment by InfusOnWoW** [comment]
That's because only a subset of the group has the same settings. It does look strange, but I would argue it's not wrong to show that it's only a subset. 

Ideally only the title would be blue, and the other settings would not show in blue if the same in all. But I don't want to look into implementing that. 

I can reproduce the font tooltip having that much whitespace, that's because blizzard can't calculate accurate tooltip sizes if a line is too long. I'll fix that by showing the actual font and not the path.
