### ISSUE TITLE
[Idea] Weakaura profiles (Change static info like size, position)

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#171]
In ElvUI and I guess other addons you can switch profiles when entering a specific talent specs, ie. when I switch from Holy to Protection (Paladin) it can change ElvUI profiles automatically.

I often have utility weakauras active on multiple specs, however due to how my UI looks different in each spec I need to find a place for a weakaura which works "everywhere". 

Wouldnt it be nice if you could change size, position etc. dynamically in specific specs?

**Comment by asakawa-k** [comment]
You can just duplicate the aura and change the load conditions. Then you're free to alter the appearance for each spec without affecting the others.

**Comment by Stanzilla** [comment]
Yeah i'd rather not, the settings are already pretty complicated as is and I feel like load conditions solve that problem quite well.

**Comment by pquerner** [comment]
Having to duplicate things which differ in the loading settings will also make the load process even slower if you have loads of weakauras active, no? So what good would that do.

Also if you update the "original" weakaura you'd have to delete the other one and then reduplicate it. 
If there would be some sort of cascade system that would be fine I guess.

**Comment by Stanzilla** [comment]
Yes, sure. I was thinking about that exact problem a while ago because of my own UI and I came up with the conclusion that if you run into the problem where you have the same aura but want it in a different position, it's a problem with my placement and UI building and not something the addon should solve. Ultimately I don't think this is something we would solve in the addon since too much already revolves around load conditions and not profiles. I'll leave the ticket open in case we start thinking differently or a good idea on how to solve that problem comes up though

**Comment by InfusOnWoW** [comment]
Yep I agree, it just doesn't fit besides load conditions.

**Comment by Auranim** [comment]
Well, I'm venturing into the realm of UI building with ElvUI and WeakAuras and, so far, the biggest issue I've found was not being able to specify one different profile per character. Of course, I can just create groups and make them load based on character names, but that would make the sharing of these UIs a little bulky since the person who's receiving that UI would have to open up the options and change the name to their character. Having a switchable profile would make it MUCH easier to create and possibly share entire sets of options on a per-character or even per-spec basis.

> Ultimately I don't think this is something we would solve in the addon since too much already revolves around load conditions and not profiles.

Welp, you don't have to remove the "load" function. Just add profiles. People who don't use profiles will just edit everything inside their own "default" profile. Those who do would also have that option.

**Comment by InfusOnWoW** [comment]
Adding options adds complexity. Especially if those options need to interact and aim at similar problems. And since our solution with load conditions works very well for the use cases we consider most relevant, we aren't adding profiles.

Since you mentioned per spec basis, that's perfectably solved by load conditions. In fact, it's better solved by load conditions. You can have auras for a specific class, which are augmented by different sets of auras for different specs. With profiles, you can't do that.

**Comment by Auranim** [comment]
True, but then, for organisation's sake, I'd have to create a single group
for each UI collection that activates based on a class. Then inside that
group, things would be harder to organise. Is there any group-within-group
function? It would be a lot easier to work with different regions of the UI
that way. E.g.: My mage has 7 nameplate auras. One of these auras is a
frame for the Arcane Power auras, which are 4 different auras that light up
as I build Arcane Power. The two other auras are my Arcane Missiles prof
and my Time Warp counter. It would be a lot easier However, I'd like to add
a small glow effect to each of my Arcane Power auras that only works the
way I want if I set up a second aura on top of the one that lights up
individually. With proper nesting, it would be a lot easier for me to
manage having ONE group just for the Arcane Power, then another aura for
each of my procs, reducing the number of clutter from 11 to 3.

Em sex, 23 de mar de 2018 às 06:20, InfusOnWoW <notifications@github.com>
escreveu:

**Comment by emptyrivers** [comment]
Lots of people have asked for nested groups, but it’s not really feasible without a large rewrite of much of the options code, sadly.

**Comment by Auranim** [comment]
Hmmm, hopefully it will come true one day. I'm using a workaround of sorts
(just organising sections with numbers "1. Player nameplate", "1.1 Player
castbar", etc), but it can still get messy when everything is visible.

Em sex, 23 de mar de 2018 às 11:26, emptyrivers <notifications@github.com>
escreveu:
