### ISSUE TITLE
Model Element Overlay Alpha bugged.

### ISSUE THREAD

**Issue by Dajova** [WeakAuras/WeakAuras2#1817]
So i wanted to test out the new model overlay feature for some of my bars. However, it seems like the alpha slider is not working at al. 0.1 looks exactly the same as 1.

![model bar](https://i.imgur.com/0Hn07DD.gif)

Makes it really hard to see it, specially since its strata is above the text itself (since there is no option to move it below or above).

I tested this with both one of my existing WAs and a brand new (just make a progress bar of something, add a model that covers the entire bar and adjust the alpha slider in any way). No change in terms of transparency.

edit: also, enabling SetTransform or else the bar just hides the text entirely.

**Comment by mrbuds** [comment]
Can you fill the issue template ?

**Comment by asaka-wa** [comment]
You _can_ change the relative strata of elements by using the arrows in the interface to shift them relative to one another in the list. 

The issue, I think, is the Condition which sets the Alpha of the Aura as a whole. That gets inherited by the Subelements, overriding whatever setting you gave it in the Display tab. This diagnosis (if true, I didn't put very long into investigating so there may be more going on) undermines your report that you had tested in a new Aura though. Granted I'm running 2.15.5-16 which may have differences to live, but I see now issues with a new Aura (without the Condition). 

Maybe worth mentioning that while this can likely be fixed and is likely not intended behaviour, you probably ought to untrigger your Auras properly instead of using Conditions as a weak substitute.

**Comment by InfusOnWoW** [comment]
There are questions in the issue template, please answer them.

**Comment by Dajova** [comment]
There is a way to successfully replicate the issue:

* Make a progress bar WA.
* Set a Model.
* Set it to 0.1 alpha
* Works fine.
* Reload the UI.
* The model is back at 1 alpha, from 0.1.

**Comment by InfusOnWoW** [comment]
That doesn't reproduce for me. The progress bar is hidden after a reload ui with those instructions. 

Why don't you just include a aura that shows the problem, like the issue template asked you twice?

**Comment by InfusOnWoW** [comment]
Finally at last:
!DBrYUnUn0VMEyoKbwEbDUA7O0yapYPMkttkgin0suwCImPajL3omF7994sSCgG2GEOhkqIm5BF)XSOS0mYUmsj(hCu3svV8h8stDws0a)9vvvAM5PSeaaTZulvRAnCPqdCyYiNC4DOffa6hKCbGyECsA8AVqwlnuKjlzxb5ZYswgz6JPRYiBOfVSvj7eLZLnsfOGKiKJKH2VJSFhdF)4eu1gfF7wMs7Ol9va2JNAbXQbD0PZiDAwoT5a9K2O6yzZaic2EgAMGljb3Vt5SpsugXJzUuuYDEQvaDcUXXk8lPTHEcuf4mSMMfL(OHGUJ5pQ72yf0dkwf)ygH8q8YLEtzJwQ2y98zxiK0vzjmF(usAojD6AWpkzBaWPwV5(4LpC3JlrH3jU4RgeaTWW3ZsDaTso5gifcy4fsrErV4zKnEgzJNr24zKLoHHPe0MVaruBMA4emJY35cmP2OPYGhcrRCFuMbQaIa(GUqkyOa3r5I3p1vCbxx)UP3GvlQ5)KB1VmX6wLmnudasKLT5Qk6ND1IDBwZ26lN9vrw9qbEanKd)dIbenIHD0KRRPLYdpfk7JETwRBdI3tL74V06V(oI)w6QKyL3Dk(5F8TFVJwc2n9hFl9AD)33CCryoQFoyP3efGZAQ8nPU(ol09CnFtJTI8vtXv3LGHChWR6WxKKeVoFz8DPHw)N7nmWs)370gE1PltduyBpl1gDswLeh48P3YjQEc)muhhnetaJ(3Lae))pbSEXVD))fzGXygG2YX(ODWeMM8JwIDN1MCysBY4b2gZChWEU0RuPo1JRkEdBbS(z4OjJg9PEuz6t1PR1Jc07WFDG3vcBvUG(813noZ8IvrBARP4wK(LoaAl2aJVviNFJqkA4TGFzNevZ4BRXsryIzJK63LYkSRx7Am8Wu6IgQw)tq1yq(nan(zvZAyIs)oYBV1U(yAjMtzLSYptpAhQDPCkKKVMmyomqMYoNlT)0n3Ed3WVxhV3FySDVa3eS0Zs5oBCWUurZrZku(H7rH8mhYMjSdEZ)EFKzKVOQtbCmRHF(mvbeEW9wJHdcVkinqZcCBufTG915uOawSDgv91hxCZLB3qqg88H(NrwSpS76tdgoysWg4LLmyoqs8xWqdy5v8TE)ub7RHNnan52bjUoH7qOU4ez(644eaHRKbiPdDWJFy8sb5HpC7JhWaeQw3QCuFZ)Nh1ivCyHV)fh3VA9I)Cvs60LwJl8MJW6OIAwXl9FDdAf7Pkof7Si6A5b8Ed8UMe7c)IAQyl7IaAvYwMcAO8EHjuGDSxhpMqTLZeyt7WpgnbEIfzpiHXdrlo7Vc
