### ISSUE TITLE
On-import custom options setup wizard.

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1860]
**Is your feature request related to a problem? Please describe.**
when importing a larger group you don't necessarily know that the auras have custom options, therefore a feature that makes a setup-wizard appear for all auras with custom options of that group might be neat to make users more aware of it.

**Describe the solution you'd like**
Upon importing a group, it should check the amount of auras that have custom options, then it makes a custom-options wizard (setup) appear, something like this:
![](https://i.gyazo.com/8352f450d13126b5b6d2ecbd98ee9d95.png)
when you press continue, it goes to the next aura's custom options and allows you to set them up.

It would also be neat if the author had the option to define page 1 for himself (an introduction)

**Describe alternatives you've considered**
you can only fit so many explanations on a wago page and people who import it from someone elses pastebin or ingame, will most likely never figure out that an aura has custom options.

**Comment by emptyrivers** [comment]
I don’t want this. It’d get in the way of actually importing something something major. Barely anyone ever voluntarily touches settings for any app, and that’s not a bad thing.

Choose a set of default values which is sensible for the “most common” case, and nudge people towards custom options when they ask.

**Comment by InfusOnWoW** [comment]
So I agree with rivers on most points. That is, most users actually don't like those wizards, and most users never want to change settings. And such a wizard would be duplication of the custom options interface. That's not something I would want.
 
This feature request is the typical case of proposing a solution instead of describing the problem. The problem only gets one sentence: "when importing a larger group you don't necessarily know that the auras have custom options". Whereas the proposed solution takes the vast majority of the text.

I think that's actually a somewhat valid problem. We could add some text to the import tooltip pointing out that there are custom options. Or we could add the description of the group to the import tooltip.

Or maybe show somehow in the aura list or in the tabbed display that there are custom options.
