### ISSUE TITLE
Swipe issues 8.3

### ISSUE THREAD

**Issue by Duality1080** [WeakAuras/WeakAuras2#1917]
Am I the only one who have some issues with the Swipe function with 8.3 ? It doesn't work, swipe or not swipe, it will show the classic sweep cooldown (even with my older 8.0 / 8.1 / 8.2 Weakauras, who worked perfectly until 8.3)

![WAIssues3](https://user-images.githubusercontent.com/60038214/72665730-61ea0780-3a0b-11ea-874b-a92e49eaefac.png)
![WAIssues4](https://user-images.githubusercontent.com/60038214/72665731-64e4f800-3a0b-11ea-9d33-391ba7e98775.png)

Thank you ! :)

**Comment by InfusOnWoW** [comment]
In those screenshots, what exactly should we be looking at?

**Comment by Duality1080** [comment]
@InfusOnWoW Sorry I'm stupid D: It's now edited

**Comment by InfusOnWoW** [comment]
Can you add a link to that specific aura?

**Comment by Duality1080** [comment]
!nwvWUnUnq0VMc0EynKvIDCoShCCD2naELsnv2UThKnTeLeBKjvPOSJZb))Sx2FI8J1ziPSKttrdGbm5WrVz4BM5X4HXrXeECWOjxpC41XK6yI)GHJh4ft2gtsXFGd0gDHufwP5srnyqhtoeMLvZ0XbGNurcC89sUaoy28GO5lJjjszzQCVGSNxXI30zyEAol(g4RsAHJuRPkTf3mUGxxyxdlTwH1AfppNPq3dmjTZaUSb9Juvspa7j6dq8qi1nWTjLTPjllYy7ZZxC)TpSaoSzdBhtOjWr8NIjRMnLeTIenDjGwAJIIzwmziaDnBvotWu8esHCFOaZ8ZnqQH)NwUNEOUd57vmdYK7NVacOIrljvSYYa6wirMjBQoUo9LVNuqF5hIx(Unq1N8acIzZDPo6wawDlBeMiyQkYyIBZmh7EC99kzUIvxFC9pBc5VybxROjpEcytucMmYFYelMD0PHUXIZowK14xKPGZFyONTOOzkbT8RqXazPa)XXKhzSQPaWj6Li3HLBQGV1YJ9kWNi3vUQelrkG7OROjKcggJTuU4979PwM3N)ASPOg6oaFnnMqnBjl31l6AUypPxvxqbg9B9A0DW2Sbp35LD5pv72MilLklo3E5i)H(J9M45FXvxF11(XzFyShqy4HbxGigCjUUfQmjwjVvXF(46FRHMcji946OZZNzDbiWcM3BcM17)OF2BmZkZCtQtFikSxKTZiHpeT4UG5o77418nLM(rZ(ZM0Vliy(Yv3egff(LL39Pph1Qe8Vc6F1uR5zh6ehofuc)zO1Y)KisF2wjHzywKHFdcHCsJxxik5LY93Qy)DdtKCaCDG)OE1g8utl)NkBzRn2VXEd30O1sr4oMcemShSGjY1fa75z33)cKxEoNpSxbCyhNBIQloF7vFojHcCi4Nnlk4jpkGb0twwWHTW0OD3nsvkdZztRAbJNxaqDjGvPKAKJXX5KskGWn2nvm9gQwxA1znNGdDCroyI87txU8UqG132uQ5Tt4obNKwm2XG8YIGbF5wasNErsp4GB)5avJLWOZnQrjpCKYs58euontbIoGUn0vBU62k(TOvRBKzlNppO7LcS0)R8Ak0bMI51Zs5w7doOYh2tkt21kdnX7cp4iE6BiVECTVljW3DkRkSjWEEkw1rQfolJN7eyrmc(tVTpEfTu7Td18WWyLL7MF6EP7)T7a1H46ZKyskyGEmSyhTSbU8E4kfhVS4Huvo0tqKvXKp(XUx7CWvqf5SoSSqazxLswXu6dV(532jN3WXEAH2kN1ZtPxVi3lbTVojwI5rlSbE)35wp25TKfhn(1Ay9Vji96YTlEh5Mu0(y47jZoJma5Jb(dmZY62g5wMe98PUjB4KDaqx6JPB8)8

Have the same issue with any WA of any cooldowns with stacks (like Judgement of Paladin, Rune of Power of Mage, etc)

**Comment by nullKomplex** [comment]
Are you using ElvUI?

**Comment by Duality1080** [comment]
Nope, and I use exactly all the same addons than before 8.3

**Comment by Duality1080** [comment]
Never seen this before 8.3 but I also get OmniCC and got a update for OmniCC at 8.3, maybe a prob with both ?

**Comment by nullKomplex** [comment]
Ah, yeah I would start there. OmniCC is likely in control of what you're seeing there, not WeakAuras. They probably changed a setting, hopefully you'll be able to easily change it.

**Comment by Duality1080** [comment]
Seems like when I disable OmniCC it's okay, I'll found how both can be friends like old days ! If u have any idea

**Comment by InfusOnWoW** [comment]
This is a issue in OmniCC, which you should report in their bug tracker. It works if OmniCC is disabled.
(Which btw is something that we asked you to do in the text for the bug report.)

Specifally, I'll explain a bit of background on what exactly you are doing, and how WA does it:
This is a aura for two spell with two charges and it's set up so that on using the first charge, only a cooldown edge is shown. And with both charges used, the cooldown swipe should be used.

Internally, WA calls SetDrawSwipe on the cooldown as needed, that is on using up both charges it's called with false, and on gaining a new charge, it's called with true.

This was broken by: 
https://github.com/tullamods/OmniCC/commit/ba70f2fc5c7d53da5f2b7ae29981640d13b6da35, which overrides that SetDrawSwipe with whatever setting is set in the OmniCC settings.
