### ISSUE TITLE
Slider values appear as blank on reload until options get updated.

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1927]
## Describe the bug

First time opening the options in that session results in blank slider values until you change something.

### To Reproduce

1. Create new Aura Bar.
2. Reload.
3. Open WA options, select the New aura, and observe bug in Display tab.

**Screenshots**

![image](https://user-images.githubusercontent.com/28709830/72764604-32bbcd80-3ba6-11ea-9d29-ff5f057640e4.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Tested with only official WA addons enabled.

**Which version of WeakAuras are you using?**

Latest Twitch supplied alpha, 2.16.1-4-ge6439ac.

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Unknown

**Comment by InfusOnWoW** [comment]
That doesn'T reproduce for me consistently. It only happens to if I switch to a different tab before step 2, and then only with roughly 25% of the times.

It very much looks like a Blizzard bug, since the slider does show the correct value, just the text is missing. The code of the slider does not allow for setting those two individually, they are always set at the same time.

Can you figure out a 100% sure way to reproduce this?

**Comment by InfusOnWoW** [comment]
Tried again, sadly far too unreliable to try to pinpoint what the problem is.

So we can't do anything about. :(
