### ISSUE TITLE
Accept multiple items for Item Count

### ISSUE THREAD

**Issue by roblabla** [WeakAuras/WeakAuras2#1932]
**Is your feature request related to a problem? Please describe.**
I am currently making a WeakAura tracking if I have a healthstone in my inventory. I currently have two choices: either write some lua code (which isn't great) or make 5 different "Item Count" triggers for every kind of healthstone (works, but is frankly disgusting).

**Describe the solution you'd like**
Ideally, Item Count should take a list of items, just like the Buffs/Debuffs takes a list of Auras. 

**Describe alternatives you've considered**

None, so far.

**Additional context**

None, so far.

**Comment by InfusOnWoW** [comment]
We briefly discussed this, and the general feeling is that this has such a narrow use case and would complicate the item count trigger quite a bit. E.g. what does the trigger actually do if multiple item counts are available?`The buff trigger has plenty of options for these cases which we frankly don't want to have for the item count trigger.

**Comment by SohMahmood** [comment]
Can we have a look at this issue again? In Dragonflight there are three qualities of the same item bronze silver and golden so you need to make a duplicate for each one...

**Comment by theruan** [comment]
Another example of usage for this would be when you have multiple items that you want to stop to do something, like converting, opening, ...
I came here looking for this because i'm creating an aura to tell me when i have restored artifacts to convert to crate, restored artifacts before crating have 109 item ids, which would mean 109 separated triggers at the moment.

For such things like multiple items it could accept an item list like the zone ids.

Expanding the function further, it could allow item count based on:
Type
Flavor text
Effect text
Quality(rank or collor)
