### ISSUE TITLE
Classic was pushed to the Retail twitch

### ISSUE THREAD

**Issue by arcomador** [WeakAuras/WeakAuras2#1945]
Used twitch to update, it installed the classic version on the retail 8.3 client.

**Comment by Stanzilla** [comment]
**Twitch** is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing **Retail** on **Classic** and vice versa. Ensure that you have got the right version selected. If you do and it still installs the wrong version then you may have to just install manually with the zip.

You can get the latest versions from:
• CurseForge: https://www.curseforge.com/wow/addons/weakauras-2 
    (see the Recent Files section, bottom right, for both versions)
• WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) or [Minion](https://www.minion.gg/)

Most importantly **this is a Twitch issue** that is ongoing and a frustration to many people. Don't just fix the issue and move on without contacting Twitch and letting them know how bad their client is. @ZeldoKavira @telshin

**Comment by Daptonic** [comment]
Twitch is literally serving both versions in the same download. It's not "picking the wrong one".

**Comment by krazyito65** [comment]
Its still an issue with Twitch, and not WeakAuras.

**Comment by Daptonic** [comment]
When it's only add-on experiencing issue (out of the 100+ I use), it points more to HOW the addon is published vs strictly a Twitch issue.

He's literally publishing both versions in 1 listing instead of separating them out, as many other addons do, which would completely solve the issue.

**Comment by krazyito65** [comment]
Did you even look at the repository? https://www.curseforge.com/wow/addons/weakauras-2

![image](https://user-images.githubusercontent.com/479738/73587482-08a9bb80-4482-11ea-85aa-7c2d566889e3.png)

We are using TWITCHES standards to publish both versions of the addon. Everything we're doing is as the way twitch has specificed, their application is just broken.

and no, its not JUST WeakAuras, there are other addons having the same problem (Bigwigs being the exception in this picture)
![image](https://user-images.githubusercontent.com/479738/73587484-0fd0c980-4482-11ea-8eea-f62cf69fb38a.png)

**Comment by nullKomplex** [comment]
Here's another user where you can see several of their non-WA addons attempting to update to the wrong version.
 ![image](https://i.imgur.com/ZvqSEN8.png)

**Comment by Daptonic** [comment]
I have, thus the stating of publishing both in 1 listing ... I also clearly stated "of the mods I USE", which the majority of which have separate listing for Classic installs, if they even offer them.

Twitch has been trash from Day 1, I've hated it since the switch from the old curse app. Why would expect their stuff to work as intended? That said, it's still better than Minion which tries to tell me that 4 year old "updates" are new. And i literally just tried it again, the app was last updated in 2018 btw, and as before pointed it to wrong addons, and served up old shit as "new".

That said, if you know something doesn't work, trying to force the square peg into the round hole until they fix it isn't helping anyone. Instead you get people shouting at each other on github page on a Friday night.

Until Twitch gets their shit together I'll just disable updates and manually check it every few weeks.
