### ISSUE TITLE
Target of Target Auras

### ISSUE THREAD

**Issue by MorteDeAngelis** [WeakAuras/WeakAuras2#2148]
## Describe the bug

**Do you have an error log of what happened?**

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

```
When attacking an enemy, Target of Target Auras initially stop tracking before disappearing a couple of seconds later.  This is happening on Weakaura version 2.17.4.  This was working properly before the update on the 15th April (2.17.0) on Retail

No error log appears, Error reporting is enabled as I still get some Lua Errors from some tooltip addons during the new AH Window.

To Reproduce
Target an Enemy 
Start Attacking Enemy

[![Screenshot from Gyazo](https://gyazo.com/1f2cabbeb33acb027e1bf86bbfab9deb/raw)](https://gyazo.com/1f2cabbeb33acb027e1bf86bbfab9deb)

This Occurs if Weakauras is the only addon loaded also.

```

**Comment by InfusOnWoW** [comment]
Can you add the aura to the ticket?

**Comment by Tebec** [comment]
Its also on Classic, and it seems to mostly be progress bars (my one that is Text only works fine).  More specifically my progress bar one shows when the target has an auto attack available/ready and hides as soon as it hits until its back up.  Its also a weak auras side thing because mine stopped working promptly with the ZG release (I updated all addons) but my brother (didn't update all of his) had it working for 2-3 days longer until he updated his.

Working Text:
!TsvtVjomq0Fn7rqjH8bCSLnzB1sdS4W2BgCtSbxfSJIDyHEGF77y7eAv71kHqJNmZZp)MpW(4cm6igvz(bMYoDnxqXOLBkw8yEkgXKcnI)gfN7hGrNxYykQgoeNmozkKfx1utUuqpRXOF4pwqoczFPpSSrXErX(E(HrrtJIIdMGzJcH0AP75srXLgiyTnxTS8eTvbEbW9N4fIrDCGwYx)9tl9)1plJUGrKo9bz7YgneMc4lKxzNslpAU)nnvenGh9evOTXkps08YN5v6dy0DWzWB5qUiLM0QDGW4cU6GZgmDEnKQLVFpWk4CUvQ6Dym7u0TDqSCL5F8lophKknVMRVGVheNUwI56WiF3xlpqAbgaaaFv19ILQRAPm(zmcTkDXc4bDlgKOPeaH(shJ5KQhsxSkBdeK2EeEb6o17iHGaniTD(DOITOI7wxCto2aK86U5dGZbAwcPA5ocuI9uT7FaUgAD9Jv9cSPI2B2j(G26ErqSLCgV0kfMx1GSySFxm6nPou(Kk(vm(kPSLdtX7eTWL9tYkOPCKVN9lIsOXyLKBy3808I01Mkj8qfK6)o0xfmdJEf6x4mGrlsZkmjYp6QrFOJ4wHBBVotlLcqp6LDH0mHqjkk0pqf7HUR8johfVhaqKJeU4BeUBDPFtaAA2HjScRcFDNKDD3G9d9Lla6AwVSE)YIILp5Knwl0vaOt0eZKrV(Nz86Uc081PP5goFMw5MaZd88C7tWOSw(Bx39NosLbc4Ebm)NST65wsdg98nlOZETDvXW0USw26MgZMg5hepnEsuy4uVeaB2OOjWTGZIdNnBIFqO3KWaVzrrMVeB0GSKKeVz(qWHEZ8csS5eHZdnaAHxuX)WYLAjXUw00HA3u2vR5dlhkRjk1x8AAOnJjTMnckZIZpfH7Ay89dza1TGX(jJHnENaEegyOc())

Not working Progress bar:
!TB1wVPosm4FnR0(cv5g5YJaf2IenWYKEApshnWqYKWSnKbnzsPTpWV91ZfU0UNhQ0E23wP2OGJTh7Vpp2g7IZWODyuH6p4129eXZpYkKBXPUo2FpVSSLkFcNcciDYTCX89sgVPfSqIrVz(oEsVGK(99CcICCD9cd7hJl7fec20Kd2SGZAaThnonB8sRNxYLeLN0U(dsUNxqXObpKnhJy5GgBWiPGvvrfQJnvh4wb6xFBpOFlyCxlg11sx1ULFyeVvIhcY72qFH2irDLLSxXOvJgGYwHYgSemTRHbXLKiQOsZtam6eMad5IrAtXO7OKAax0oxBZq7bTNMZkz5NfUNFGk0bKjTO11tlSG1PizHGQJe0IXZMHrnKDuRgDn2ZdGAU5eU4qW7f0nqwKPZ37gpBXKhMzm7k04NLs)SqvQSKKlzVqZmwRX90Ea3lna)QCEnxyGC1FE6N(6NbQNk9AKurdP(Ba5OztVeitP1LFIZL0xLkICdrm6kV6O86KWK(X9D8s67hg6fgebfp99vN0KWGKeFxVah)aphOet9LWlNEbTfyDGVOkFFvf73n4F3ML0kB5QTUrdEeWgiswb)dUbcHmtecvoKc(HNSL1GjgX6Oh9BU3S1wiCLY)J0r90x)8uyA0(cOyQT1svm9oOEl3CZdnqZ86pbfj0c7fYWGt3L((PyZXQ2F11kzLVDbQfQ7r0mDiNopD85BiDBm5H2SVa3AIcUkINiyVFC9F2rkaWMCCD2hbSZbvVti2bUO4rbzpg94530F4fwlBtTUC2aax3Hy48SS53F1jJyVd1KUUNY(N(C2RuYCHy(dzZMczRuLgFn(u()e5)rez28f)BzrWlBPSQTW0LqNi)KqNGWWOaFVKa7WLAoXo5IMRhM1vlz6oPGT51K2w9xznvqyIwmy2GBNMErTZsSndvDjvnGf6EjQq(t(uABXmSM2uyNsD7TAdhuOypAbT4EYRk7jnSDMXiz6ztc5LUpn8g6L5mRSKkf64cJkquslfgVrBQu1l(gbzxmeIIDewZVq3vYAyTB)15q7GftB3ZjVEybZ(25J0GQ74C52fcELGcK2WpdPm9oacDR8SRBGJrVEAdKOaVeNi3(o(XXWRQzib9Te2OVWCm18UwMItxo9pUdI7358Dxwo5owrbf2jiD83oVcZDMYZuFBzCNaSEyn793jIIJRhTLiaCGkoUg9mRUU946HQqgoPswLDNaLFYoz7u1W0sso9hJiqVGMkq)F8W0Ex(vpKYaRD6fJ45VCA0RRRVd0EHvCAHLJRHXYqljsnCrNi4LzQZ)GUt0KG(bEEXbj(bHrHbX6n2IbMra7Ja8l0Dq3V0CJDIsQb6rJwoEmCnIuVFRrLo1jwCyZZrsp(T)ENIOvbLEOSEvgGr5cgSAJDZkadZMoAWSvttHxrJ1Gsb7Qnl3qYFUsW7AkUI8Me6fh5hf77477KalfyxuWtLnEWINoXoE(rjrjEQVKywHik2noX1ZXVFysyC4hxHqXbyK3nUr3aq3lGWapLC8F)d

**Comment by MorteDeAngelis** [comment]
Progress Bar

!TB1wVTTnu4Fn7Xe4lP7YJoUkZgWvoZuPjTOGU0Iu2CvM0GKYjXp0F77CoKYwXTBRaR7Tc4OqD45(35I495fC2wotI)GJ(Dc3NUxldB4597LEFEvLxfEGNdeEk(cD(5oNfMYnw3TwTjWzJZYlYwKKEHnicARHy7fuEJvQ4Sr3vmNZ0LahxZzbNE9ALZdoto5Cjc0XN3b87bHB8W)BwP2RmbwtvL(joB54rSILSIrlawnITkuhGZiBCr7Z6ZzKeC2eLOgcrwJxT0VtvQR0LlBm6a6ciX2ZTg5wNImc72SzZWWqvxpvMSqRgUdfIfeU1Qq8jOSVgnWaIvERBfLbqtAsoMOjybxwTccQckCNKn72BUBgN0vNKXFNIppCcOKIYGEVQiknz08la4neZ7llT1wxmJJ)gqphspVcFI8zckNru)waBiWCWVbbUQU6miFLWn(l0wpsB9oPnPYdGiGlk(QxuK9UyvsZQfQ1Gz6ugqjdbidyHLWFGAavJ3OEkS0VriTp(qBbz)ez8bN9t7EbxD9VEFD)lY9POlwJsureAluqvg7syJieJUcQquYuZZpFvBpX760LqS9Nn(GU65t5mh2pOkiFnFEE2Xk9MvXaGe7BaKIEHf94BC6dF(J)rJqczzXN)yXlZuhDQlAtvpADY7DcivD)Xt0f71E9QAQmnMa62PpnppBXYzz3u0X6m9bOaR)G2mWdNNbqMIv35wJcrYHFJiP5hi5)Ri5IP)(K)BqjOQnk96ni29koR2kslwuL0UMM6GMgBcmwwl8(VGQhT5zedPPexxRmY0EJx)AAI3ijcdkPs(gXt44KhJ42GE9o)ETbV3rJwk6oqbdp924AIcAfJlGhucVc2aPmRrnoSfonyOECXYYegRGrPWkbsOIt8bU(wH28DuDvAJ2V57NctliIJBpg8DneTaqhAriAPHxJOqQGH2Bb1vA4djYvpMqRjPcHHPQLghiX116dheojjeusnFxRPbnFWA3E6dfq0kyl33UZ5x7nSx7Dt0sPcghKN9wSZd8Ok96KB7GT)qAbAxObiXs3BqQX4MnErwwoCr9UnrwAqhV5PMrVpmt5QhGXlA2t7Ng)V30ADAyjE6JnMmFX03ppVy0mY5K6orjPWI2eYuC1ALOu9HXcyEIz91c3hUB6fNE7cgLnGLRLFATZ2yK)Zt(6D5Rs9mC2Gl7)lxcJW2d8E1a0p5)1

Progress Texture

!TwvZsQnoq4NOHY2yd4JegZouHXdlYjP2lIiSLnkXi5swEcKd5zF7wY2WsoSxsbLq0Qv)7x)jQpnJsotjf4xyBxlxF4kn1RF7f72RVvw2Yn01pfopk0ZFAONxu8SWfE0YNIcOKsLMxPvDYIvQALgSuQV9BaD9S5l8xe7h4nnAw8S4P4vwqtNIwone1YaoN3YmDAMH)bw(3DMIEKsAzN5z8lWrC6hOKJJhEVF8q)GRJ20BseAvJwuvX1To9Ygf0NPhApP(XYJTk9r04fO)fkjL47oUtkm2d4h7klZU2WPKxs2UB9N2cMY(3wde2To1pXz1Mtyu3j5VZLqaW6mky16IxvfWfE7Zj73U8FoSE)BVEij95(aPHNlkf5JUCi62iZvNfYQxaBJYB7oAnnbciXfk5WQLKSdKSL7HucSsD9McmDnotCNNHl3huV4ItIeQTd6IULyy6kUXTEZv70CRRi7s2U1P8JLXhJ()Ne(3Dg(HWYnI35zoBBVC6t(E4jCzXszvniy6maokKgUwYQ)m0AX(vAqmeU86YDkbMGRssZs2dUqL)(Gkl8M6bx1ayjlUYiY)(1Nh64GeTY42Ja(sfAN1AXp)1x)7owbOg7xFndY3tCr1jdnnYZfWkjwcrCG24QLLcPO9KBVat1mx6vRy2rmOBci4g7GxxTrGBCsW(laRHFndnqeiPXWlVM12E)DSQGv(FxO4N8hfILxP4SldVlEhb9h6XZ8CLeqq9WBPscRCwlhgD4Yka2adzwbz3uam(zMq(h0CJ1W)qg0vnxw8TUwdVGx8k7cwunoMLVOznoW6QTlFDhuSbFig6TM7P3g4Ii(ZIMnfWax6PgbOAy4K5ZNVykW05hebwrRASCPtcbcLZcTwzBL)3ir4qF8kWDUyUrRQ082wZGVuagOMDDKg7g36IiGd2BXCVWW44G4aKBD6dCRGE3tt67oEsW04a)OzlMfmpmYFuBiBpwdZBU6XYNX5vb86q7hNB(uAd5V28nlT2jL(TM7krT1mPXDPnPKnpNqj)quG9d7KsDZjg6a7KfbbOP(biMmhm0dJT3i5hR2HrEX(yjvDUblnyjdJQml9HB9WaVMi3nrxQbcoaxaZUwx7C2AuQRqtwTpjjTFyONGXZ29lfvddWidc3ob2)IdivPfaXy)JfR2(2Qp(LnKK(o(LHo(T30wpIFqdDl)gWowsoauhmXF(Kqk5DiEddW2b9Fp
