### ISSUE TITLE
Nameplate Anchor not updating when moved offscreen and back on

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#2207]
## Describe the bug
Nameplate anchor does not properly update when the nameplates are jumbled up from removing/adding them. I would expect the default nameplate anchor option to update it properly.

### To Reproduce

1. Import aura
2. Find area with multiple enemies
3. Focus one enemy
4. Turn camera away so that no enemy nameplates are in view
5. Turn camera back
6. (repeat as necessary)
7. Observe bug

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
bab5d5c

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Unknown, but it's a relatively new feature.

### Additional Info
https://wago.io/ZN4Cz2Jes (no code used)
https://wago.io/ESWkxHCpe

**Comment by mrbuds** [comment]
For you first example, you need to use a trigger that supply a nameplate unit.
For the second example, you need to update your trigger on NAME_PLATE_UNIT_ADDED and NAME_PLATE_UNIT_REMOVED.

**Comment by emptyrivers** [comment]
We shouldn't leave this in the state it's in without any changes. Either we fully support arbitrary unit ids, and handle nameplate events in the anchor system, or we validate unit ids coming from the trigger, and explicitly reject anything which isn't `nameplateN`. I personally think the first is the correct thing to do, but either is acceptable to me.

If we do nothing, then we leave this as a secret "feature" that hurts usability.

**Comment by InfusOnWoW** [comment]
I agree with rivers, though I think the second option is the sane one.

The way it currently works is that mapping is only fetched if the trigger updates the states. Since for a nameplate based unit that happens naturally on NPUA and NPUR that works.

For a focus unit, the attach code would need to handle it, by
* Checking on NPUA if any of the auras that couldn't be attached in the past can be attached now.
* Checking on NPUR detach any auras that are currently attached,

Imho it's much simpler to just limit it to nameplate units for now.
