### ISSUE TITLE
Add "Show GCD" option to Display Tab's Cooldown Settings

### ISSUE THREAD

**Issue by ryanschmitty** [WeakAuras/WeakAuras2#2213]
**Is your feature request related to a problem? Please describe.**
Sometimes I want the GCD to show on an Icon WA even though I don't have a cooldown progress (spell) trigger that allows the "show GCD" option. Currently I'm adding the GCD snippet from the WA discord, but it seems like there's at least been some thought into making this easier than injecting on-init code.

**Describe the solution you'd like**
Moving the Show GCD option to the Display Tab with all the other CD display options would be great. As a bonus, letting the GCD swipe have different display settings than the actual CD swipe would be cool too (e.g. an edge on the CD but not the GCD)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by InfusOnWoW** [comment]
You can add a gcd trigger to your auras then. 

Having different options for the different swipes can be accomplished via conditions already.

**Comment by Dreamjammer** [comment]
I'd love to see "Show Global Cooldown" under the display tab as well, right next to "Show Cooldown" and working similarly. Adding a GCD trigger does not work, since if you add a GCD trigger, then the aura only displays when the GCD is going, or not going if you select "Inverse" there, whereas what I want here is for the GCD to be displayed on the icon but have no impact at all whatsoever on the actual triggering.

I suppose if, in addition to "inverse", there were "always" and "never" options to use (depending on whether you're using "any" or "all" triggering) to that this "trigger" is always true or false, but that seems kind of perverse. What's really wanted is a pure display option that has no impact on the triggering, just on the display, which is why it would make most sense under the Display tab, in the Cooldown Settings section.

**Comment by asaka-wa** [comment]
The setting in the Display tab simply enables the Cooldown display (!spinner!, "swipe") on the icon. The information that swipe is showing comes from the trigger(s) you use. 

Generally when people want to show the GCD they want it to show on an Icon they're using to display a spell's CD. This can be done by opening the extra settings on a Cooldown Progress trigger and ticking Show Global Cooldown. 

Pretty much any other setup you might want to display the GCD (outside of a CD trigger or a GCD trigger) would be so specific that you really would need to organise your triggers to display it in the way you want. A simple tick box in the Display tab couldn't hope to cater to whatever various people might expect from such a setting.

**Comment by Dreamjammer** [comment]
Usually the icons I want to display the GCD sweep on have no Cooldown Progress trigger, but they do have an Action Usable trigger. Could the "Show Global Cooldown" option be added there as well?

**Comment by asaka-wa** [comment]
Yes. As well or instead of.

**Comment by Dreamjammer** [comment]
"Show Global Cooldown" as an option on Action Usable as well as on "Cooldown Progress" (i.e. same option on both triggers, so you can use either one as appropriate for whatever you're trying to do), instead of on the Display tab which can stay as-is in this case.

That would be awesome, thanks :)

**Comment by Malevola** [comment]
I'm actually curious about this for a toggled ability. Showing the GCD would indicate when the ability can be toggled off.
