### ISSUE TITLE
small button to collapse all sub elements

### ISSUE THREAD

**Issue by Nercus** [WeakAuras/WeakAuras2#2265]
**Is your feature request related to a problem? Please describe.**
It's a bit frustrating, if I wanna edit some things in the _Display_ tab and there is this wall of options (i.e if there are several ticks on a bar). It gets pretty confusing and unorganized with multiple texts, ticks, glows, bars.

**Describe the solution you'd like**
A small button to collapse all option groups / sub elements (Text, Tick, Border, Glow, Model, ...) at once.

**Describe alternatives you've considered**
Move the _Add Extra Elements_ to the top (maybe even subtabs for the display tab if possible)

**Additional context**

Small concept of how it could look. Small yellow arrow top right. Options are already collapsed here:
![collapseall](https://user-images.githubusercontent.com/48932939/87162032-a7ee9c80-c2c5-11ea-88e5-4ecd00307c6c.png)

**Comment by InfusOnWoW** [comment]
I disagree that this is the right solution to the problem visible in the screenshot.

Instead the problem is that each tick currently requires its own sub element. That was a consicious decision for the first version.

But we want to make making multiple ticks easier and solves some problems, e.g. configuring ticks is currently a bit cumbersome, even though in many cases all ticks will share e.g.  the same color.
