### ISSUE TITLE
Actions>Glow Eternal Element - Still active even when disabled

### ISSUE THREAD

**Issue by tridnt** [WeakAuras/WeakAuras2#2309]
Glow Eternal Element bugs every time I try to disable. I have to reload to make it work again. 
example https://youtu.be/UnuCCZ22QxA

**Comment by emptyrivers** [comment]
That is working exactly as intended. The glow action doesn't keep track of whether or not the frame you chose already has a glow on it. Instead, you need to add both the hide and show glow actions yourself.

Since you're targeting the same aura, you can just add a glow element to it instead of using the glow actions, and the glow state will be managed for you.

**Comment by tridnt** [comment]
> That is working exactly as intended. The glow action doesn't keep track of whether or not the frame you chose already has a glow on it. Instead, you need to add both the hide and show glow actions yourself.
> 
> Since you're targeting the same aura, you can just add a glow element to it instead of using the glow actions, and the glow state will be managed for you.

Thanks
