### ISSUE TITLE
Conditions tab does not seem to work with Trigger tab "Status/Unit Characteristics" Smart Group or Raid Unit.  

### ISSUE THREAD

**Issue by Kolmarwow** [WeakAuras/WeakAuras2#2339]
## Describe the bug
The Conditions tab seems to not work when I try to apply conditions towards the Unit Characteristics trigger while Unit is selected as "Smart Group" or "Raid". Other unit types that I tested (Player / Party / Target) seem to work fine. 

**Do you have an error log of what happened?**
No errors seen. 

### To Reproduce

1. Create a WeakAura and make a trigger with Unit Characteristics & either Smart Group or Raid selected in "Unit",
2. Go into the Conditions tab and try to make any condition, for example "If Trigger 1 Active True - Then Alpha 50%"
3. See that the condition did not change anything even if the trigger is activated. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, seems to persist with all other addons disabled. 

**Which version of WeakAuras are you using?**
2.17.12

**Are you on World of Warcraft Classic or Retail?**
- [x] Classic
- [] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Not sure, hadn't tested this before.

**Comment by InfusOnWoW** [comment]
I can't reproduce this, please add a aura that shows the problem to this ticket.

**Comment by Kolmarwow** [comment]
I followed my own instructions and couldn't reproduce it either so that's my bad on that one. It seems like on its own it functions fine but when combined with another aura it stops working, so following my instructions but adding a second Aura trigger under the Smart Group Unit should hopefully show the error result. 

[Here's](https://wago.io/WKrk84IAu) a link to the aura I first discovered this in , it's for tracking missing MotW in groups/raids. You might need to change some of the triggers around.

**Comment by InfusOnWoW** [comment]
That's is due to how conditions and cloning interact. Conditions are checked on a per clone basis. And due to how your trigers are setup, for each clone, trigger 2 is not active.

For your case, there are two ways to change this:
* Don't set the Alpha via a Condition but through the Display options. As you aura only shows if trigger 2 is active, that has the same effect.
* Enable the "Auto-Clone (Show all matches)" option in the first trigger. (Keep Combine Matches Per Unit checked).

This behaviour is actually what the behaviour should be, but obviously the naming does not make it clear. I don't have a good idea for a better name and this a very rare edge case and thus won't do any change at this time.

**Comment by Kolmarwow** [comment]
Ah I see, thanks for the explanation. 

The alpha condition I set there was just for testing purposes, the goal I had in mind was a condition that checked a players name in the party/raid and if the condition was met then the alpha would drop to 0%. The idea behind this is I'm a feral druid and we don't have the improved Mark of the Wild talent while resto druids do, so I wanted to place a few conditions that would check if any of my guild's resto druids were in the raid and hide the weakaura if it matched. 

I've tried fiddling around a bit with the Auto-Clone (Show all matches) & Combine Matches per Unit options but they don't seem to change much, I'll just drop that idea and keep the aura as it is. Thanks for looking into this & the quick responses.
