### ISSUE TITLE
Group Custom options. 

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#2458]
**Is your feature request related to a problem? Please describe.**
While there hasn't really been much need for custom options for a group, I was creating a custom function for a dynamic group sorting method, I found myself setting vars in the sorting function itself which isn't really ideal. 

**Describe the solution you'd like**
Custom options was created to give users the ability to easily interact with custom code and I think it'd be nice to have a custom options section for the group itself. 

**Describe alternatives you've considered**
Setting vars in the groups sorting function, which I feel is a little messy.

**Comment by emptyrivers** [comment]
This was largely the motivation for the `child_envs` value you have access to in group sort/layout custom functions. It is a bit clumsy, and a bit of a hack. Unfortunately though, I'm not keen on adding _bona fide_ options that live on the group itself.

Really, the main problem with the idea is, how to distinguish between options on a group child, and options on the group itself? Should they be on separate tabs? If so, we risk annoying users with yet another tab - that list is getting fairly large. If not, then should they somehow merge with the child options, like we do with options on sibling auras already?

I haven't figured out a solution that makes me happy. So, I'm going to close this request, because I don't expect to be able to find a workable solution better than the workarounds we already have.

**Comment by 1ps3** [comment]
I sort of envisioned having the custom options tab be completely overwritten by the group's custom options. Since I don't really see people needing to mass edit custom options that frequently, since custom options tabs are usually extremely unique. I'll have to look at the child_envs thing. Thanks for letting me know.
