### ISSUE TITLE
Stop the hostility around clickable weakauras

### ISSUE THREAD

**Issue by philipaarseth** [WeakAuras/WeakAuras2#2496]
For a lack of a better place to put it.

I know Weakauras was not made with clickable's in mind and support is shoddy to non-existent, but the whole idea of weakauaras (at least my personal interpretation) is make the UI that works for you.

Two times have I gone to the discord two times looking for insight specifically related to clickable's and both times I've been met with what can only be described as hostility.

Even if the developers have no intention of ever implementing actual support for clickable WAs (even when there's undeniable interest), here's some low effort suggestions that could be implemented to make clickable WAs and the mention of them a little less of a negative experience:

- create a channel on the discord for people that are actually interested in this
- implement import warning if references to clickable's found, you can even make it sounds really harsh like "Do you want to import this dangerous weakaura that might break your UI?", "Yes, break my UI" & "No, my UI needs to work"
- create a faq, can be community powered

**Comment by InfusOnWoW** [comment]
The hostility to clickable auras isn't because it's unsupported, hard, or that it "may" create problems. Only a very minor subset of clickable auras don't require a SecureActionButtonTemplate.

And a SecureActionButtonTemplate is inconpatible with how WeakAuras works.

It's simply impossible to do correctly within WeakAuras. Opening a channel or creating a FAQ does not remove that basic fact. 

If you want to create clickable things, don't use WeakAuras for it, it's the wrong tool.

You are asking us in effect to open a channel for: #can-opening-with-toothbrush
