### ISSUE TITLE
Smart Group not working as expected for units that lack a buff

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2502]
## Describe the bug

**Do you have an error log of what happened?**
Setting unit count >= 0 in a smart group trigger with a supplied spellID & auto-clone checked doesn't make the weakaura show when closing options.

Removing the auto-clone suddenly triggers it but doesn't return %unitName for the players that miss the buff

### To Reproduce

1. Import https://wago.io/60plll_oD
2. Close options
3. Notice how weakaura isn't visible
4. Remove auto-clone
5. it should trigger now but it doesn't return %unitName

**Screenshots**
![](https://i.gyazo.com/0684096939b0b57ed462be3f1274b456.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
Tried 2.18.4, beta1, beta2, beta3

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
i tested as far back as 2.18.4 but still doesn't do what I expected

**Comment by InfusOnWoW** [comment]
I removed that example as it describes how it worked with the old bufftrigger code, but no longer is accurate for buff trigger 2.

Note, that auto-cloning will create a state per match, affected unit or unaffected unit, or all units, which match the filters. 
The exact behaviour depends on the settigns.

Whereas the non cloning ones will create a state if all filters match and otherwise none. 

Thus this works just like designed. I'm not sure, but it sounds like you want to show a list of all unaffected units?

The settings for that are: Auto-Clone, Combine Per Match, Unaffected
