### ISSUE TITLE
QoL feature missing: Allow to change the transparency of all selected items without changing the color.

### ISSUE THREAD

**Issue by epigramx** [WeakAuras/WeakAuras2#2569]
Right now you can select multiple items and change the transparency but that changes everything to the same color which makes it problematic if you do have different colors. So an easy solution would be to have the transparency setting separate from the color setting.

**Comment by InfusOnWoW** [comment]
Well, that's too niche.

**Comment by epigramx** [comment]
Why is too niche? People have multiple progress bars for example with different colors.
It's opposite of niche!

**Comment by InfusOnWoW** [comment]
Because it requires a user to have:
* Many progress bars, otherwise you can just go one by one
* With many different colors, otherwise you can just select all matching colors in one go
* And to adjust the alpha of them all at the same time
* To the same value

In addition this adds complexity because why should progress bars be special. We would need to adjust all color settings in WA. And write conversion code for all of that. 

It's not worth it. You'll just have to go through the progress bars and adjust their alpha one by one.

**Comment by epigramx** [comment]
Many progress bars is extremely common. Not only I have a lot of them but I keep seeing them in videos and it's the default way DBM et. al. show progress so it's a very traditional way for showing progress of 'things' in the game.
I did not think of it just for progress bar but for anything though bars is the most useful one to me (it would be color + transparency as an extra button in each Display tab so I don't think it's a design burden.
