### ISSUE TITLE
Aura category update change/no change

### ISSUE THREAD

**Issue by knelson39** [WeakAuras/WeakAuras2#2628]
So this is borderline on if this belongs here or posted at the companion app, let me know!

Now this is me assuming WA does not do smart updating as in it only updates the area that needs to and doesn't replace any changes made by the end user unless that section needs to be updated, if that makes sense? lol

**Describe the solution you'd like**
Reference: [Link to imgur](https://imgur.com/a/Oski5wS)
When updating a WA in game, it would be nice to see which section of the WA will be updated so the end user knows if they need to update that section or not, if they made changes on that area they may decide not to update it and ignore the update etc..

You would have different options on how to relay that information under the 
What do you want to do?
[ ] Create a Copy
[ ] Update Auras
- Display
- Load Conditions
- Meta Data

Next to the area that has been updated from the WA author, you could simply state in parentheses Display (Changed) or Display (Needs updating). and maybe have the font color red for that text.
This would allow the end user to easily identify if they need to update that area of the WA and if they made changes to lets say the display area and there are no updated changes, they can uncheck that so it doesn't get updated.

**Comment by InfusOnWoW** [comment]
This is very similar to https://github.com/WeakAuras/WeakAuras2/issues/1139.
It requires the same tracking of the original data, which we actually do since a few versions.

You might want to comment that you wish for a "extended" version of that feature request.

But so far no one has made it a priority to show that a aura was changed, or in which way a aura was changed since the intial import.
