### ISSUE TITLE
Clicking and dragging a scroll handle scrolls the editor window in the wrong direction.

### ISSUE THREAD

**Issue by capoferro** [WeakAuras/WeakAuras2#2641]
## Describe the bug
When editing a custom check on a condition, if you click and drag the scroll bar handle, the window (and the handle) moves in the direction opposite of what's expected.

**Do you have an error log of what happened?**
No error.

### To Reproduce
1. Enter code into a Custom Check condition.
2. Click and drag handle on the scroll bar.
3. Note direction of text scrolling

**Which version of WeakAuras are you using?**
3.0.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Comment by InfusOnWoW** [comment]
You mean in the small window on the actual conditions page instead of the edit window?

Because I can only reproduce it there. That's entirely outside of our control, that's a standard blizzard scrollbar, which apparently doesn't like to be squashed that much. And thus to fix it, we would probably have to increase the height to something a few lines higher, or implement our own scrollbar. Neither of them are worth doing.
