### ISSUE TITLE
[Feature] add neutral creatures/mobs/npcs into the hostility selection or reaction possibly? 

### ISSUE THREAD

**Issue by strickland** [WeakAuras/WeakAuras2#2646]
**Is your feature request related to a problem? Please describe.**
I got a weakaura to color the name of chosen selection and I choose condition to color enemy hostile to be red, friendly to be green, and I'd like neutral to be yellow.

**Describe the solution you'd like**
In this picture I will attach, it would be nice if we have an option for neutral, watch image.

https://imgur.com/a/nO9j5Lx

**Comment by InfusOnWoW** [comment]
There are many ways to categorize units. I've intentionally choosen the one that matches Blizzard Show Enemy/Friendly Nameplates settings, and not the one that is used for colors, because it's the more useful category for weakauras purposes.

Using custom code for the more niche check for friendly/neutral/hostile is imho perfectly fine.
