### ISSUE TITLE
Anchoring Pixel Perfect Issue

### ISSUE THREAD

**Issue by Nnoggie** [WeakAuras/WeakAuras2#2696]
## Describe the bug

Previous pixel perfect arrangements of any WeakAura (not just groups or dynamic groups but also stand alone auras) with UIScale of 0.71111111111111 on a 1920x1080 resolution are now broken in the newest 3.0.6 update. Icons and Borders are misaligned by 1pixel. Adding 0.5 to the x offset fixes the issue.

### To Reproduce

1. Import the following WeakAura and set UI scale to 0.71111111111111 on 1920x1080 resolution: https://wago.io/L58_ThF4g
2. Observe the pixel imperfection
3. Add 0.5 to the xoffset of the group

**Screenshots**
https://i.imgur.com/lPXfUOo.png
https://i.imgur.com/S7bOINZ.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, same behavior.

**Which version of WeakAuras are you using?**

3.0.6

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes, 3.0.5

**Comment by Bakamaka11** [comment]
I have absolutely the similar issue with latest 3.0.6 update. All my WAs in classic and in retail got shifted somewhere and now it looks so ugly.

Should i just use downgraded version and wait for this to be fixed or this is the new standard and i should edit every single WA in my UI?

**Comment by InfusOnWoW** [comment]
@Nnoggie I'm confussed by your screenshots. Are both on 3.0.6?

**Comment by leobolin** [comment]
Same issue here. Everything is off by a half pixel since the last update. Messed up my entire UI.

**Comment by leobolin** [comment]
I don't have a UI scale and instead scale all my auras manually in order to achieve pixel perfection (based on my resolution). It seems like all auras have had their positions shifted by ~0.5 in-game pixels on both the X and Y axes going from 3.0.5 to 3.0.6, meaning everything I have positioned has moved slightly.

**Comment by Bakamaka11** [comment]
For me all my WA have been moved by 1 pixel on X axe to bottom and 1 pixel on Y axe to the left.

**Comment by Nokramx** [comment]
i made the following observation on this:

When i take a WA group like Nnoggies and anchor it to center (X=0) it has pixel perfect issues.
But when i anchor it to the left of my screen (X=960) (My Screen Width divided by 2) the pixel perfect issues are gone. The WA Group has the EXACT same position when i anchor it like this.

**Comment by InfusOnWoW** [comment]
The position To Screens Left + 960 is not in the center of the screen, unless your screen has 1981 pixels.

I actually need example auras that have changed positions.

**Comment by leobolin** [comment]
For me, **every single aura** has moved.

**Comment by leobolin** [comment]
It seems like some calculation based on the X/Y offsets have changed.

I have this WA that just displays a background texture for my minimap (which is a different addon that is on top of the WA). I have it positioned perfectly in 3.0.5 so that I only see the border below my minimap.

`!WA:2!fsvqVTrruySwLwXEO04cbRafIkqqCatCASBcub41zDJb7yR1lHkXb7z8oE3jSEMvZmRtmh9buVI)j4Z9K)j0FbpfH4hq(jKRCHz21nivoWLDM3mV59(EFVV3w4SIsVhxEVYvloPyqXGx8WRWOr)AGGN0GhZf)qHcfSUgZfbeHZ6l86ZJPbxHsvrCr3efLZK24CFgUmF1niKGpLCHKpzPGeQDXFwcXluWttw7sF6Vr6z94YhSk3UftsuwRn(3KlUS74X6BE5DeZY398nQDu5dRkqJYsDnpPcju24Xugvgz7Oxu2ZvcAyiri3ExX6T)(YacoD8ydseN42UxZFQTJYaluQaT)CzcjoUvG0(AzkMmLWu91EtVC1Gg177pOVFDpFNuDWXjXOzeHhdnHiT9YCfFcbfRIU9P9ee9t963ZTD7fPS1qWEfInsZA94uMAUF3EETE2j(3Onicgk(mnE1Luhp5iumXAHKepoZ1LoD9972PTBt)hrdsEWGo6ICckzhtpXqQSGfzCBRrCwP7)0)E1yHgC9vcKcTXn5jTP5itXJ73WZ190Ks0qgxqw3cDnW2vi4c5qSomJPH2lv8rtZbvPcd(JxL3CYBd9SQuU2cKbhM3xd2S5vbAI0ymWqRcjrhMajuYHXzKxrqsdIiSqv0DNBSmGbEIZeeL1eQc1GsWtGdVlCKEP4BEYstWO5QnNyokO5IujzWOyKug5OBEJ2YBsASIA7LD2wW3z7i1ImZM9tPbRCFwJUh0cDXL0PfhT9l2bUxb4DkaFgUH7P(UEW911Gnu0gEGn8U3Bx49(lOewlUuPYRnPcfFbAMujsjdfPSS2SJEkGp)1LDXkWolBClmHp2g(a4dHTTHhbFYCtimYNH5bdl5cChEazi8q4JGTG3h(u7KnnQ6Pe)C9I56x(wWN3b(I91QfTawQrJozKOKndOYrcIImqWvzPVWsT6ZlBAtpqgrOHrQE3Ps1d1tl4mN056PNDLj9jefgPuXKiX48bPDXsklmMmVECmvRyiAAd(Ed5bFB236MV3OixQra5NfOed68A0UENE4juJWjcEBX67xGJjSGmpCA7E6XWVGpO6EhvPkCGrP8MD7V()V)d7ne23OcntaL(Vda7CC6KjZGYWxbFPL3f0av0RlEWz1pwX94ZDyN3(8MWgAfs2)xSSSkavSHVX2dfNeHSMFlvwC6F(8)5`

In WA 3.0.6 it has moved slightly, which is very noticeable. I believe this is the case with all auras, or at least all auras that are inside groups/dynamic groups because everything is slightly off.

**Comment by Bakamaka11** [comment]
For example this energy bar moved 1 pixel to the bottom and 1 pixel to the left after 3.0.5 -> 3.0.6 transition. Altough it is for classic, but i think it will work with retail too. 

>!WA:2!DJvxSXXv1FVDBWKX0whhAAtQHmzPXXU12XF08rBX4SJ964T1E92XJTttdA3zN5U7mXZoZ07mR)I2sJrT1sGkclHi9n0c)5ZYxlGqI(as(bE(ilKG)V6hqiHqi5Nbvo37D21RDCckOwjeJKTVFCU375CpN7VZVJJnFhbQd3)a9FHok3HzhMBC6Dk4rnjufDJfnPE((TR4yV2A6utznppNqB)T1ReA5rNXp02ZnqIU6mflgqc)8XQP7AGtK1Z2nSWyPYOLsTMyZgZZXJ(cXIfl(qvOo(pHvyOFWZD(ZVSEjV(T9oVQtzJHgE(f1p)GuDd((Er1GqDAOKITRDOuHI4FcSKwpKAxQeHgCQUOrnF7QMKcvkwuBvFcDYutLDI5Msje7OQxHQp06b(ehN0Mbs7euPazjIB4SO02Rul3yjNvl3SAjv1AmvwkbNsD2SPMAkLk4jxW3rFvcvLpBHjj6oHwQU6LjbsBwXnsfK2fTyc1v3zEu1qTF6n1DTlRZmKlcFQjGJR465s22evi2y5yQhnGy45AgSfrpGmBiL4wk0Q11z9yMcKqPSUTlUwib85GNeoBRqxyZh(GJqxsCMXRIgHkPe3PO44PBoXMvci5mC0dcucPviQ8MDviW2TKdrvDMRoxk1YvqFQKcElzCcyaSH9AewJTlefai8DXJhpBCmkrnWq3HeVGWVAvv83uM4TWGYzTxH4uLY1bMnOwI6vXpsMzXn(i(pUDjxpkjk4jf7wnfL6rdYVLqmrW0rRg6zezyFYE7jHTP)Xs5sOLwvwrNk)0YA2glwRifDe4vNEOE8DfbFtWgID2fMDm1uPYmufBZAvgptaz1RnUYaJvaVZlAxskkWmTlEyXRYCe2IW5ndiof5HWvvMrtBMPNk1eA0veQ1KxP3J8TBb)6W45245Rg4RtxCbBZqRhcEaio8GsWrEnj4taTcP)hTSfFAXcVwST59u9c5raX8p2(6pTNjrj5CAZah9oFDCPXD8mTn0EMZF5DzEf2TQRzJ3uXGh5H7cAFJJTE94Rogcof8eWXGoGJxWOsqOxzAfxEiSc(41dEC4KWj2mxQmPuVA6RNc6e(m1eYXdnRHp9cjv8nXFdFwP1zHrShd5HhvAhwNaVkudYCSHunSiglcDkE)e431CzsRLl7mlKsn3eQPEP5qCGNt8isEM5tPovYxwl9yVy192cutvx5bxUyfx(l)U17vM0RCypsY4NJhgVjBuHsJC)JiZwtwVLj0Uti23e9kpCZsB7AGI10A6tUBgwqoI7s9JpbcJg2J2KqInWUOC3e5rgroXHygj4IW(0DnBE))c319FGE23AyA2BmI8foSbV8Hn4qhQOdFOJEXbKoWidoq05JAYhNMvZUNM8ptRVY(CrhuxAkCibFFcV)3TqlIBdDb9EUE4M8kjs8fpWuCvLp(iYFP9nk7lWYBzCcgizV3XKgw6ULiM315R)QdfyO7CwYk(2I51SlJ2T8vjHSwD3dIIDiY7t9krjbbmmmu6eHOSMj2NyVEJEeNaY(Ms8aiaxi3y33Cb9VFl5at2SzCGPU32WbeUP7Y9nZy5ylH2FYIyQYUhQx5gp47rEbI(IjXZpO)zn0D5zfc6EFXh9Y3WEKjUM7f7HDKA(Vhw0AZabCHOKWkuxH(HleoTK)XyCowIOjYMZWIF)wQAJjfYzup5xCqEAvEpj4QqR7wp7yA3jOEUHwkmXTQXb1N2MLrZANGqmj1QJhDVAbTHCbKGhscq4Av)UpCJMzTZLD8KAPQBZBA6LtaoB1CkLxog0ZtDc441ywDbDAo8NL2wKwlNhxK2Q3vKBCiuIO8E5yP5ptuk39SsEk(icG5wYoWUGdXQ(siysELmipg44BIuneJwWIyxYkSp4mOXnpNAcJLYzBTGpgftcvkQBs4SvoNG4csAH1JtLPz5HqOcFMNAE4PZZzUWYyrTGbz0rG(6c6hopR1qS(7WVjuCqpiZFnuYXhhgUHjSoAPr8wMC0)6tW(ABYrFZ2zFNlgsymqpK5wiwGsn1StND2lR5pWWdbDFmrsDXINC0)(OSVtH7YF7FY((Jto6))JS4vAPLhFNGYEEHwzJEUA53oQYjnVj6OiMeZPTrh(LPr(MTRZ2GhSK)GYQVI1M8WTaBtKxw6RoP2UC1y89uu1Lz8mEY2eHytYV1hbE(8Q6o(w6XvwZZRCScbKY4DM6GiH(lbJGmNIe320K4QMjf(Ic0YdJ2gCfijJv1jqgqix1WvpxGC0lgg1kyCjQTlJagjpnKScQee1z9CqYuEuBmsLhsxDYzutF9zYOLCkyIt1fC9lcT3zlRVKo1whJC8BxpmeFNWAJC5lrcvxs3PcjgvaeHK4HVjZF9mRJOEiJ4WvH3rLRW5fr6AIt2)sPz8RlQBqUrsttKM2nA845g8Kd8MttmT1VHyu2VV0ZSXLHx4rHxmwdAzpa8QWuXGPHmWrbPMErkjir9NrctmYpvcGzbTT4CDq8SX8cqYpVuhdcDQYppodQRLFtFwhgLPwrQrivjoVRtap22Sv2yY8CQyNwcY9(Ta5RdNWWrGcwkSRxlyvmA7pDB233cdz)a23VBYr)lIrIdyKksPeSWh9Va(OhS34e(NHTYC8Fv0JILBKZphlDro8PNHnVMGnBisIZILYX7fyPBYmP6LKTJy060EHm(hNpcJPiRggdodxLKy3DfhgsZ3Kp4T2wGS8YciPyBXNNfxBxCvO1Qug9wcZlQKzMmPGJtrGdMmv5cUh66MrwHBOF7tqTxt(LQOBY41lRP53rtQD0j1zl7B0Rjgn(28XwgFSTav3F9fIAiuRi8S8rxdnvS6wPZGmHZjkzD7gQcVmSx1)KhY1SOHkp58ElGvIZjJUsIuPy(N(U5LmxfRJ02WAJpn8lIdvtCwx47WDiW3fdp))GVh89Vf8dIb)qmm5hb)y0P)(Wpre88tHFg8Z7SfOg8lHFLf8RRjmaoYXHOVUrnqG2F7jHpig8BGxDjOCRWIGdUTuWvCUE5bF)t2OE)Kgw2ieCz85U8cEEMWnJbbtELl8HFy(wAPFilBrC4wbMnS0DbRgwgwPjWzWWINT4okT9C)7l2fEnXfW4sq3XHxpp8gikl8LH3mp8wzpYGx6Y9)SW6WxbEN4i0i82JaF9QismwkUJDqiI3vqGXbBedUTfhGe(QWxJdjEugKi8E(DVhwZyincSwzSIZBmx6(2RxFZYaNWuhfgiRZfF20Z5LQm8UwS6)(gWMWesWTSG1S24Iha9PjKh8oGd487rdufMhwGvdMOUm4XyajVI)zVhvsXRCJZmIJ4CDC1i(J6kXF(p6kJcje2Gl49UUO7Nchoyra7zj)psnayZ7ZQao0v8Fd1bGnVFQe4of)JUAbAkm5JVsbo0S0pOuuIAmfDC2)TL1SyypCU3GncJEMMGrBGX5zb(ixJB2ge0NaPmwDuY83duYBzTpojimhM4VjOtLAx4MJzROmwQHhOa8EWwnbaYGVyyFJghUTa7B96q5CqoeZdX5gr8VtB3zMAC8YIFVWktHbxIGMVLzB8)twrWSVBEoRJiqnK8X)P42DS0F4A)R

**Comment by Bakamaka11** [comment]
> I actually need example auras that have changed positions.

Also if it helps i asked a friend in Classic to make a screenshots of his WA on 3.0.5 and then update to 3.0.6 and make a screenshot again. You can see how almost all (but not all) WA went a little to the botton and to the left. 
3.0.5: https://i.imgur.com/tM1wMLH.jpeg
3.0.6: https://i.imgur.com/CEynqhK.jpeg

If you swap between those pictures fast you can see all the difference. 

It itsn't a big deal for those like him who have not many WAs, but for us, whose UI is heavily WA dependant and polished to not have a pixel problems it is really something not cool to deal.
