### ISSUE TITLE
save sound handler to icon data

### ISSUE THREAD

**Issue by q513902026** [WeakAuras/WeakAuras2#2741]
**Is your feature request related to a problem? Please describe.**
When I use playsound to reloadUI, the music doesn't stop properly

**Describe the solution you'd like**
The music can be stopped correctly after reloadUI or triggering the event

I tried to implement a wa string https://wago.io/Bc0B-DKuk

**Comment by mrbuds** [comment]
This is aura doesn't use any function from weakauras, the issue is in your custom code, please use this bug tracker only for bugs in the addon. If you need assistance with custom code you can use Discord.

Btw it write to the table WeakAurasSaved, this is not meant to be modified directly by users, don't do that.

**Comment by q513902026** [comment]
@mrbuds 
this wa is work and solve this problem
WeakAuras not save sound handler  
when i reloadui ,WeakAuras don't stop sound
WeakAuras only stop all sound

**Comment by mrbuds** [comment]
Please open a proper ticket without deleting questions asked in the template.
