### ISSUE TITLE
Unknown compression method (236)

### ISSUE THREAD

**Issue by HysterixTV** [WeakAuras/WeakAuras2#2765]
## Describe the bug - error appears when importing addons from wago.io on 50% of attempted imports
imports to be added successfully without error

**Do you have an error log of what happened?**

```plaintext
Error decompressing: unknown compression method (236)
```

### To Reproduce
 Import - paste import link - then done - error appears

Steps to reproduce the behaviour:

1. Go to 'Import '
2. Paste text below ' paste import link'
3. |Click done
4. See error - Error decompressing: unknown compression method (236)

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No other addons installed

**Which version of WeakAuras are you using?**

Weak Auras 3.1.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

First time using addon

**Comment by Causese** [comment]
include the import string

**Comment by InfusOnWoW** [comment]
We need the string you are trying to import and a screenshot of the import window after pasting the string.

**Comment by InfusOnWoW** [comment]
No response.

**Comment by yurifw** [comment]
Hello, I'm sorry to comment on a closed issue, but I am getting the exact same error, here are a couple of import strings gicing me this error:

`S3x72PnstcFV4)mMDme9nWCoZpW2jXENj25eSNzF2jXGaAm6ncjwjrC88CE8D2E2lP3BHTQQBj1sijWyWXjRooXGL6pQU6QRU(S7BuV5QB6BVmWEWyFF3j(35niG9fwqi7MJVP)i)WW5(tgqfygZ52zr3CHU2n99y3foyAG9Cgu)irlegzp(Zd8xg564XUP)LxF1VF(fV(M(r2b3YIgmdQUl2edIyFnAzauKZ9IybtThZ(yVjtU0l8JV31gEYhDMBFll8JHmx24ihFVboEtCgBh5hOFt)PobHrdcw6PJGi1ZroZzbuZcddx)aaOUqL(Ng9BD63g4VbGfkguhNXq7goZ)Ub(tNY8cD(cBWi)GjS4ARq1wPLLj1akTKAcQxxypzIJ3T4JwPnNWkUnB1Xu0Sgf0SHS5aU)M(QTWhVYyZ2B8mAW1)Ee86)v63Hoty3CrxS(FMD)iavfYNugBd4jysjAz4i7GbtTNWGjhQbX(1Kxc8vIzizCNsRUwDS0AlG2UD1unTYJj5t7zhVJNCZiGYz50PHdaSbwen8jZ898dgmY15V)B7GjdwGZ0dSDxmZgFRef2Gfa5NVNTl014WdPQa08apGAJQv4aMN9ix2eC()wx)r2U4Cyimc44fokFq0mNXF2JfgMFgch2W7tOuV4sKmnW27wa8NXaIyo4tqhqM7W8M46W4TdnCTV92a)bqFFhcdlDaAHaMxe1YdCHfqaWRQeJG8dIsiv5v31DWe4ViABEFLmOJrgJTbqzWO7PXTycfNFg4dKib4CousVLZhbJKa2TylLSYa7n5Hdbw4enhFJdJXUaYzq4cyXh807SVpKanSrjKm2OH(ldgZsHnSjOjxbBbezgMLQuphzzheUJSxaeiEoSj5jXIPUelf6MsAnJz7gntI8D0TjSn4CjogOlGzHLEtEyiWsAg0FaHbB(9deK1HiSMJeNwhf683m(8JmsA1zBATpVHtOBfTxbn9Qm(MWW5w(u(4XCsGi)br(3ERlBqcHDm18OvwYMmIpLfz74g(WW3adDa3UGbuq2EaFsKeIgOjtx0mHybbFMySTlTIVt6leanobL)zdUZjAgsccyanlaMJPzIxWlwErtLHifA09liQXXFbGzGtG9s3io9B6UdAdG5kGpHtaNLooZlTWzKDiIrGLe230)4EN8BV9dxE9fNIaFGZIObtWxqKnWOd3FIAIMaH8Ll4OG4xEklC8n9H9waIZ1UdJ)c(sqxBVpFt))W2DjJqzxHJOlGb)f4IV(hJV)HH9Xvl30)3y3FtFEnnGHhmq2YU11EeWOq0T9FnwNhggnJ9WqVfJHFb99dd9dO)8CGk3Xt86dGw9HHxf4C7TSGdEy4i)V(WqBCHWmNi(RpOv8OWmEuWXupm0kZqWchc6FBWCgPD74z4sry85d)pyP4Bjpfh1CEhpoWdeQjg6oog4mIbUteT(fX7S8WWt49bbO8op5L8xfHi0TezjgaCWrweffb)ptntJUkQDTuA3XqpLzihUvJH7sGxVvGuRui1XBCadwKftGL2e8DDbIO7X35amz(cNGK3RAf0R9bgOpm8solM(VjWMVKE0JdDW38kH4beT7D2FLODYoCWElUVENJhIUGXw7VnKSD29t(TARQ3ozMVdNwO0j)t9JYoTpXpkmzgV73gScSx6oHhy)pV01f4SfVVxooy5FTeyOsefQB9wavm9yaIbByQ0TJIExnT1m9iar5jOq8rjZqQz2Ui3ASE0ETPROo(jTIsPLMynLQmOi6K0LsQ6vas9jPh2DGKLaK0KbjrNWbPwijfGz)a7lo8951bvp6VmWfbVyDKwhymNnXX(JuRpYh0cyGfW3)6fti(JGOP9NU0BmFdXdbfnNE0ddx65eD(eXxEdQDl8DM3xUcLpRXd)7pmu8tY3A2KKDe2AEkS)KTxUDSK4Ys0xPvel)HXnDRtS9oPGnBAqnJNuhl(HpeB1NfLTcqBweO3kFZM0GGOUYdl(Fk(bOeyZxm4sVZabGFQOSyioYFbWaRxSKRPGBlUa)hBhid4tKkBJ8iF5Pbq63i)GcW7OS(Pf01hi0KE)zI9((1eiCYOwlc8N6aDoxfvGiBQZTTinla5WeW5ay)u)5JSH6(xAFkTdky88lW0uC)CyUEUXQJLIARRrS88fGEK2ErehgblWFbNBoSH0mhmRr63RAPQy1UJPkW88eq(yqMQXagARMhHVYfdVQfcW2ZrG2mG4dhEV)Yhgo3gKNWJXaHsFvaZ13EcNQp0FoTCaXQqHDc9(jaXyVybOZfwK50c3iM79nkE9wvRV4IpscXG9fONT)DSjY07vVIJOeKgRTeZ(JlSSnBwqlVznywz1QQzsL(zTTLCrLHThfjf1lBu5Wrxsb)LtaXlJyIxEONJlq1CWOeD0pOX2sIdlFIB1)6Vs42)ko3(xXx2(kIO5vsC7v168Pp14r3tV33Xl6WdgZW(5GJkCbnoWslGc8)MMpLr3FWcaf9jcHd5dNF592bHCsJWdlygpvIIg`

another one:
`9svupTnmq4)oSPrAsttHIgpWycPcISP5QXlvM4MCPXBj2r2oW6Ei)25StAAb1nXKqtw66f7E39D33DhnGUGsMGcdLe4tJdOKiugoniCgEd(zEJi1WLI2KJ0qz(hAtAeCZ8SELRuSka1bXdlyRkTQ6ufV24(6DTx3M0D(AjZakpcyIrlQTFDPSuQq)UVF2ZyVuPiNV2JTwk24(V75oE(Uy6D)3GkgxWfRxWRG2KpE(bCJPqb6czzM1Ctbi25STNbh6c5vLmDXziU3C0Ebgk1WRZsIrw)mlfzTx7eVfhKDg)2Xoha)TjN)hU3sA905Lka)T)(DePxbWknfFIPWi67fDyIDpg59TjJFfSpw9OKtOKyO638Jjm1AqX0usJQKskmMA9zJg9iAIhxo6Uv3EZJ3f9JOryHILLjfushSXA3K3UA3livk5uCcAAG)jHt9hJHoWnwndLtoLsMsjDfnmRxTPn5LPYdGsJGIgJwQHQhCO1Z3dDHztnGx6abLeItTOJJhFAuqyKBao65j1br7XhZfAqzAtsLz4SsbO2VF(GAUYoINlSCrBYcfl9NwCjRTHs3beCrYNbDkLSOaSdydCBUTFrTDcTnjRrX6GOrI1aynhvZTTq4ZEO9200M(2ffusFZ1J2j2eJB(EWz4RiwSoJUIsMNAP45cKHZzPWYlYY(IqVSJZxYRyRb9YomFVOPALnf(oRSbJgYk3Y(fnEgU17gydwR3IF8bUWMFglMgsY)TOLA7F3gSoAZYCozOtoPle9jFW2KVVIZQRl52oMEh5G4Ujd0ql9h()DB9FF9XW6VHHdSOkthAVN577pgHn9P)`

(this one is unkown compression method 189 instead of 236

and here is the screenshot:
![image](https://user-images.githubusercontent.com/3476335/109388487-1ed4b600-78e6-11eb-93ee-a64d41cc66f6.png)

**Comment by InfusOnWoW** [comment]
Decoding Errors are usually caused by:
1. You have some malware that is changing the string, usually changing what looks like a bitcoin address to a different address.
2. A browser extension that changes site content, we've seen a currency exchange extension change something like 12USD to 10EUR within a string, kind of thing.
3. Trying to import an ElvUI string into WeakAuras will never work.
4. Trying to import strings for private servers is not supported.

**Comment by yurifw** [comment]
yeah, it wasn't a weakaura string, I'm sorry about the confusion, just started playing this...
