### ISSUE TITLE
sound issue regarding "status - cast" trigger

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2783]
## Describe the bug
Tracking the same unit via different unitIDs (multiple triggers) causes the sound to be fired multiple times.
The sound fires once at the start and once at the end of the duration.

There were times where it didn't fire twice but that was the minority

**Do you have an error log of what happened?**
no error 

### To Reproduce

1.  Import https://wago.io/umBwqFj3E
2. Go to tank dummy
3. Wait for it to cast

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
3.1.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
no idea

### Additional Info

i tried using condition "any of trigger 1 + 2 true" but same issue

**Comment by InfusOnWoW** [comment]
That's "intended", though you would need to know a lot of details on how WeakAuras works to understand that. 

In my testing, there was just one sound if you set the "Dynamic Information from" to "Trigger 2".
You can also work-around it by using a conditon: "remaining time > 0.2" => play sound.

Either of these should work.

I don't know whether I can even explain what is happening easily, but what is happening is this:

Trigger 1 is set to nameplate
Trigger 2 is set to target

Now if the target dummy finishes it's cast, we first receive the nameplate's event, and then the target's one. So on processing that event, the nameplate is no longer casting, while the target is.

Since you have set the "dynamic information" to "First active", the dynamic information switches from trigger 1 to trigger 2.
One aspect that the dynamic information controls is which clones should be visible.

While trigger 1 is active a clone id nameplate# is visible.
On switching to trigger 2, that clone is hidden, and trigger 2 provides the clones now. Which has the cloneId "", the showing of that clone fires the sound.

**Comment by Causese** [comment]
yup remaining time is what I used to fix it. So I guess it's a bit like having two debuffs on group members and not using "most remaining time" results in two sounds being fired on show
