### ISSUE TITLE
[request] Debuff type = raid debuff

### ISSUE THREAD

**Issue by lastmetroid** [WeakAuras/WeakAuras2#2871]
Hey,

not sure now difficult this would be, but would it be possible to implement a predefined type of debuff as debuff type "raid debuff", and taking the WoW own api type for all important (healer) raid debuffs?

This would be super handy, to combine it with the glow effect on raid frames. I think there exists a WoW api call for "raid debuffs" with a predefined list of debuffs in raids or M+.

Maybe a custom script exists for this, if anyone know it, would be awesome to see it. And then maybe implement it into WA2 as a predefined debuff type.

**Comment by mrbuds** [comment]
![image](https://user-images.githubusercontent.com/189656/103596583-88e06880-4efe-11eb-841f-351e7a32fa92.png)

**Comment by makedir** [comment]
I saw that one, but arent that all debuffs a player/group frame gets attached from a boss? Not just "raid debuffs"? The raid debuff api has a specific list I think, which arent 100% debuffs applied by a boss.

**Comment by mrbuds** [comment]
What do you call "raid debuffs" and what is the "raid debuff api" then ?

**Comment by mrbuds** [comment]
Is Boss Debuff is active when the 12th argument of <https://wow.gamepedia.com/API_UnitAura> return true

**Comment by makedir** [comment]
The default blizzard raid frame shows "very important" raid debuffs, if it would just show all raid debuffs, it would be a debacle. So there exists something as "raid debuffs", which is a filtered WoW own list of important debuffs, mostly not debuffs you can decurse but have to heal against it for example. GRID2 has a module for "raid debuffs" too for example, which filters this too more.

So there exists a specific "raid encounter debuff" status list or api status.

Lets say there is a boss fight, where people randomly get "unimportant debuffs" but also a few very important debuffs, then the WoW raid frame would show these. So there has to be an api condition for those. I called them "raid debuffs" because GRID2 called them that too.

**Comment by mrbuds** [comment]
If you don't believe me i'll let you check the implementation in default blizzard raid frames https://github.com/Gethe/wow-ui-source/blob/1977612d0fd23d01a80d44b504bee70039df1782/FrameXML/CompactUnitFrame.lua

**Comment by makedir** [comment]
Where did I say I dont believe you. I said the default Blizzard raid frame gives an output for very important debuffs. So where does that information come from, can you read it via api or not? GRID2 also has a module for "raid debuffs" which arent actually just raid bosses. I noticed the "boss only" only works for raid bosses, not M+ "bosses" hich are 62 elite I guess, so maybe implement another trigger for dungeon bosses too.

**Comment by mrbuds** [comment]
> So where does that information come from ?
From 12th argument returned by UnitAura, which is what "is boff debuff" use too

> GRID2 has a module for "raid debuffs" which arent actually just raid bosses
With weakauras it's users who make that list, if you don't want to make it yourself you can import auras from people who did it from wago.io

**Comment by makedir** [comment]
Like I said, is boss debuff seems just to work with bosses, dungeons bosses are no bosses, they are 62 elite, so that doesnt seem to work at all. Maybe implement a "is dungeon boss" too for that

I already was looking for a complete shadowlands dungeon debuff list, I didnt find any. Also that would be a huge list.

I am not an lua expert, so I am asking just. Dont get me wrong, youre the expert!

Here is how grid2 does it I am not sure if that gives a hint, I dont see a complete spell id list in here:

https://github.com/Drathal/myWowInterface/blob/master/AddOns/Grid2RaidDebuffs/Grid2RaidDebuffs.lua

**Comment by mrbuds** [comment]
search for "isBoss" in that file and you will see it use the same api weakauras an default api use

**Comment by makedir** [comment]
I tried isboss from WA2, it didnt work in dungeon. And I get raid debuffs in dungeons from the GRID2 raid debuffs, on trash too. Thats not a boss.
