### ISSUE TITLE
[request] play sound button in actions settings

### ISSUE THREAD

**Issue by lastmetroid** [WeakAuras/WeakAuras2#2872]
Please implement a simple "play" button into the settings where you select a sound, so if you click it, it plays the sound one time to listen to it:

https://i.imgur.com/APhHAhF.png

If you have a complex WA with lots of events, and lots of sounds, you want to listen to these, what they do. Clicking through the entire list and selecting a different one and then the original again is not really a way to go.

**Comment by InfusOnWoW** [comment]
If someone provides a PR, sure. Otherwise, no that's already covered imho well enough by the automatic playing of the sounds on selecting them.

**Comment by makedir** [comment]
what? what is the request section ther for if you just close every ticket and say sure if you provide code for it do it yourself??? I am not a LUA programmer. And I am sure this is super easy because the pla audio code already exists like you said, just bind it on a button.

the select item play is NONSENSE like I said, because when you import the WA, you dont know what the sound does, because you didnt select it. And then you cant select it because like I said its super buggy. You have to open the immense large list which is laggy to scroll through, finding the same entry is annoying and not easy, clicking on it doesnt play the audio. You have to select a different, and then select the other again to play it once.

**Comment by InfusOnWoW** [comment]
It seems we are better of never considering any of your requests, since you apparently have no manners.
