### ISSUE TITLE
Bug with Combine Matches and Remaining on Bufftrigger2

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#2883]
## Describe the bug

Trying to use Combine Matches along with Remaining Duration in a Bufftrigger gives some weird results. 
I thought it wasn't triggering at all but actually, with a remaining time of < 10 it triggers consistently now at < 2. Can also be triggered < 10 by opening and closing config within that 10secs

**Do you have an error log of what happened?**

No error

### To Reproduce

I made a Wago group of 4 Auras to demonstrate https://wago.io/GSmmcr6Ym
I used Riptide as I was on a Shaman but replace with any easily applied buff. 

No Combine+ No Remaining = shows full duration as expected
Combine + No Remaining = Shows full duration as expected
No Combine + Remaining = Shows remaining < 10 as expected
Combine + Remaining = Shows < 2 - unexpected behaviour. 

**Screenshots**

na

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I didn't test this. Can do if you think it could be relevant. 

**Which version of WeakAuras are you using?**

Current dev (updated 2 days ago) but was reported by someone else so it's currently on the live version.

**Are you on World of Warcraft Classic or Retail?**

Only checked on Retail

**Was it working in a previous version? If yes, which was the last good one?**

I think so but have no evidence to be certain.

**Comment by InfusOnWoW** [comment]
Actual aura, since the wago link is time limited:
!TJvBtnUnq4Fn9dDMEGDia960VKaHx6qt4ImfU7dkrXwjr3zBzKKde(q(T3DLSDsiHRxtPDUYyggJ1A5v7lp7UpyQpnGssOKikrtjNYNH3cIM3B8yn3q7634G98GFoY37Gd9pIsgjvrCfr8eN2TbLmJR0czkSrkraAPl)Hfdb5pwQG3107yud(nA4DS3b(LAGocUJf(LiLm7ezSubhlOe83g2RhyV2K21BVdPgkHLgovQotXs4bZZ4uc5K(D60fFGiHzqJa9fMW(xJDlPYu4AuUY(8boHAEOmncCxotxOk3(W1eJINoXmfpF4q1gMY8kQVXIuHE6RNcbvMJH9KJgfqMD6Djne47hp(APifE4jD6g0PFzW7zcZvXuYuJjt)l7V)dSjY9eY9pNKKeQo6Jj7xLQktLnbRwgwLXFpKvHmToFuF(eqIgClq7I0Xsvvcb9zmLbMnZWSWeDilMBVtzFpNhorjZZOe0ZfMLAZzbDIMGj87Zzk(IHNLhhVy4TtfgqySKzrSgqPP2uvsESryFB49dJzA9gs1i8DdHz8WNl06pgUkLf)hL(DtpmeNaXbkXFpV9GLSCdeE7LTHHVkY2ZIS9SiBplY2h3OrjMmb0TBxW5NNwiYPOLlqlmo(YOItWbwya2Pb(scquwmBoAw8zySGCbNfdifseFu(4XU48fDU66ZU5kBEZUnc8iXJuYGtArcgqcA1py5dVwXTpKCDNRG3jfYK6QqtLxEzQRxr562f11us7yXtpXurlggiLqyfeXclJsqOvyC(szD2QLiU8NmDSys5QzWH0SbCoHvrRQovEOFQzgSwIJDx2aiw3bz7Dq(cNN1cr)M(OsWyNTPY7VRtNFRBJrpEF83sZcbCMezUkekUFN)kJa2SEzTEgU8OH)OzG9IlRniBGrKWhKP4HIQrmBzxUBGhb7oQyhq9OeZOH3kIWcGwWAODJ0aqJaydWCQED7uIiUBfdTq3PgxuR3nbxDjUtRC9uwK8HpUX2fpYJCNu3JAUfJuxzKUSq1HqjNPepTy4hYzry)rOmPmu85CTrmE(YU1wPpa1x3Qyqz0Tv35mTL98BDtqVcPZGi3iOzB7vmkk5hYwmSRCXWtKjJeP8FYTQphr(I0jLHLn8tN7)T0sZMdwDKdeh70Fq)lp)Is)l8RoZ3FzdoaR4m7xcHenhAljcry7kM5wtQf0wqCpCIGPmjEDh6fSeCBxbHknT7p7wzls08ZRE)ro5oyZOCJrM2dG8qd5Ihmve(fqdAhoU01S6YP)IIsFp362v0KWvKQHM4Qvtn467E26Zu87Z5PHZr2tnoSSvQmgcmPOk)71eElt9FyjC)BitwE0yT3PcndWKrUw0Bz26w5Q8KuMyDVvjC(CMfyhieRVYqJniumLlMm1uA5oZc8MmBrcloBAHQsXdYoh5FDggBH9WotkqXb28iecaNDHOd6vBD8VJWqbRR1PsO5qValkbeuoYhdkh5349hwCk9Y4qChs8KF9fPl8mAilzp81jFe66lDnxDdAKGHONcLzXsSaSDrmdaWZ4bUWWVlJSZC8S81C)xiRZU0ImQY3w6KJ2gr5Y(cvSkE3X18kET5vOMlV6ZFWlTxWd18kEJXROMtrnNIAof1Ck(oNtr7DItXIHhSZ0koyDAf(nR5v8AZRiji6h1N3607s)unVI3y8kw)7vuZROMxrnVIAEfL8kA)9cVID7BvSy4H7mVIMRZROHFnVIxBEfx3woV9X3FXNiP18k(NWR4fgc(8P()xW04VKUZgFsJfdB190)xs9OWb2MxwZ)OM)rn)J3o8p21VRrZDL)bCpoe8YtPKQHGGq6F(
