### ISSUE TITLE
Spell ID filter for Cast trigger not differentiating spells with same name

### ISSUE THREAD

**Issue by loneguardian** [WeakAuras/WeakAuras2#2980]
## Describe the bug
I noticed that the spell ID filter for Player/Unit info > Cast trigger isn't working properly for same spells with different IDs

**Do you have an error log of what happened?**
No error message for this bug

### To Reproduce

1. Download the weakaura which contains nameplate triggers for frostbolt spells https://wago.io/PUagaD9mO
2. Head to Auchenai Crypts dungeon
3. Try to spawn Unliving Sorcerer mob by body pulling, kill off other mobs so that you don't get MC-ed for one minute OR you can pull Phasing Sorcerer with non-damaging spells
4. When they cast frostbolt all three weakaura will show up, instead of only the one with the correct spell ID

![image](https://user-images.githubusercontent.com/803017/111144562-2d97ba00-85c2-11eb-8344-fb8fd39219ea.png)

5. The same behaviour can be observed when unit is set to Target and the respective mobs targeted.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, the same problem persists.

**Which version of WeakAuras are you using?**
3.2.1

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [ X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Did not test in older versions

**Comment by Causese** [comment]
so you want an exact spell Id option? this doesn't sound like a bug

**Comment by loneguardian** [comment]
Didn't realise there's a difference, was thinking it's an oversight. If it's intended then this issue can be closed. I can do custom triggers if such feature is required.

**Comment by InfusOnWoW** [comment]
This is the intended behaviour, any reason you want a check for the exact spell id?

**Comment by InfusOnWoW** [comment]
If you have a concrete use case, we'll add the exact spell id option.

**Comment by razko** [comment]
Wait, so this works similarly to how the aura "by name" works? i.e. it grabs all spells that share the specified name (and, if an id is specified, it grabs the name of the specified spell first and then grabs all spells with that name)?

In that case, shouldn't the icon have a tooltip that lists all the spells its now listening to? in order to actually inform the user of how this works.

I.e. shouldn't this:
![image](https://user-images.githubusercontent.com/5488276/111245816-4762ec80-8616-11eb-8128-1914a383ed89.png)
be similar to this:
![image](https://user-images.githubusercontent.com/5488276/111245844-5184eb00-8616-11eb-88ea-e3fc160e6f8d.png)
?

**Comment by InfusOnWoW** [comment]
It works conceptually in the same way. 

But while we gather the information for auras on name/spell id mappings, we don't do that for other spells, so we can't show that. 

That's how spell matching works pratically everywhere in WA. In fact the few places where it is needed, we provide a way to opt-out of this behaviour.
