### ISSUE TITLE
Bug from import

### ISSUE THREAD

**Issue by xouma2709** [WeakAuras/WeakAuras2#3000]
## Describe the bug

I can't import some weakaura from wag.io 
exemple : 
https://wago.io/NyKyPWbZf or https://wago.io/SyGtPbRHm
**Do you have an error log of what happened?**
 

no error in this addon

```plaintext
PASTE ERROR HERE
```

### To Reproduce

![image](https://user-images.githubusercontent.com/63860395/113039231-bbb19a00-9197-11eb-97c0-ca717b387353.png)

i can't do anything more but some weak aura works

**Comment by SpatenLa** [comment]
Decoding Errors are usually caused by:
1. You have some malware that is changing the string, usually changing what looks like a bitcoin address to a different address.
2. A browser extension that changes site content, we've seen a currency exchange extension change something like 12USD to 10EUR within a string, kind of thing.
3. Trying to import an ElvUI string into WeakAuras will never work.
4. Trying to import strings for private servers is not supported.

In short, you have a virus.
