### ISSUE TITLE
Ability to use functions or escape sequences to populate text custom option text fields or other elements.

### ISSUE THREAD

**Issue by ChrisKader** [WeakAuras/WeakAuras2#3045]
**Is your feature request related to a problem? Please describe.**
When wanting to display options related to in-game data (such as spells, items, ect). Being able to populate things like Tooltip text with something like "GetSpellDescription(xxxxx)" makes sense. The big benefit here is WA authors can use spell, item or NPC IDs and let the game return the proper text that fits the current users localization.

**Describe the solution you'd like**
MThe ability to use functions in text fields OR more escape sequences.
Maybe something like `|SspellId|s` to get spell description

**Describe alternatives you've considered**
Current escape sequences to not support such functionality. 

**Additional context**
![image](https://user-images.githubusercontent.com/633360/115980179-21533500-a550-11eb-8e84-d65203701dec.png)

**Comment by InfusOnWoW** [comment]
This has a rather small gain for a bigger effort than you realize. You can easily add the spell description yourself, in a similar way as you did for the spell name. The effort requires figuring out how to even distinguish between code and normal text. The idea of extending escape sequences doesn't work because that syntax is defined by wow not by us.

And lastly custom options are currently not a focus of development so even if there was value, it would be unlikely to be implemented any time soon.
