### ISSUE TITLE
New Search Functionality

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#3157]
At the moment search functionality exists in order to sort through auras by name and nothing else, I'd love to see it expanded to search through other things an aura contains, more specifically custom code, though load conditions and trigger would be nice too. 

This does come up a few times when people report in discord that they have random prints and the like that are bothering them but aren't sure where to find the piece of code causing the issue. I'd like to see this feature mainly be targeted at searching through custom code for a start, since I'd assume searching for specific triggers and options an aura has would probably require some kind of advanced search interface, and be vastly more complicated than just simply searching for words.

**Comment by InfusOnWoW** [comment]
This is pretty hard to do, since we would need to add lots of things:

a) Distinguish between used and unused parts of the data. E.g. if you write a custrom trigger, but then select a different trigger type we don't remove the unused code. Thus unless we have that, we would show matches in unused parts of a aura.

b) Mapping a aura data property to its ui string. E.g. searching for "Todesritter" in german should match DEATHKNIGHT in the load settings. And sometimes there's just a index in the data.

We obviously have that code, but it's distributed in 1000 of places around the addon code, and thus this is not really feasiable.
