### ISSUE TITLE
Resizing the options frame with a code window open scrolls it all the way up

### ISSUE THREAD

**Issue by BartStam** [WeakAuras/WeakAuras2#3410]
### Description

Resizing the options frame (by dragging the bottom left/right corners) while you have a code window open scrolls it all the way up. It happens for every code window.

### WeakAuras Version

3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

N/A

### Reproduction Steps

1. Open code window with lots of code in it
2. Scroll down
3. Resize options frame

### Last Good Version

I believe so, but I may be crazy.

**Comment by InfusOnWoW** [comment]
That's not entirely correct, what really happens is that the edit box is scroled to the cursor position.

That happens in AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua OnCursorChanged, whose purpose it is to make the editbox scroll if the user moves the cursor.

The underlying problem is thus that "OnCursorChanged" fires on size changes. That's a wow bug though I have found a workaround that seems acceptable in scope and effect. Hopefully it won't break anything.
