### ISSUE TITLE
TBCC: Enter combat event trigger broken

### ISSUE THREAD

**Issue by Rahuruk** [WeakAuras/WeakAuras2#3425]
### Description

The newest updates to weak aura over the past few weeks appear to have broken a weak aura I use to announce my tank openings on mobs/bosses to chat. Rolling back to previous updates fixes issue.

The weak aura has 3 triggers, one for checking for a parry/miss/dodge/critical strike on mangle, a 2nd one that checks for dire bear form, and the last trigger being a check for entering combat and only the first 6 seconds of combat, long enough to announce what kind of opening I got on a mob.

Removing the "entering combat" event trigger fixes the auras but makes it so that it constantly announces my misses/parries/dodges/critical strikes on mangle throughout the entire fight which is not the intention of the WA.

### WeakAuras Version

3.7.5-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Troubleshooting was run with both BugGrabber and BugSack. No LUA errors found.

### Reproduction Steps

- Create weakaura with two triggers
- One trigger to check for dire bear form (optional)
- One trigger to check for a miss or parry/dodge/critical on mangle (or any other attack), for testing purposes I also used one that checks for a non-critical to make things easy.
- Create an action that outputs to chat -> %#.missType on %#.spellName >>Low Threat Opening<< or Critical on %#.spellName! High threat opening! with the # being whatever trigger checks for the miss/parry/dodge/crit and whatever good or bad opening you got with the attack
- Write whatever you want for load options, such as being in combat.

- Enter combat and note that every attack outputs to chat.

- Add a third trigger to check for entering combat and with a timer of 6 seconds.
- Enter combat and note that attacks no longer output to chat.

- Lastly, rollback to WA version 12/28/2021 - WeakAuras-3.7.3-40-g04f8e6c-bcc and note that the WA works fully as intended with entering combat trigger during the first 6 seconds of combat.

### Last Good Version

12/28/2021 - WeakAuras-3.7.3-40-g04f8e6c-bcc

### Screenshots

[Image album of weak aura](https://imgur.com/a/4jM2Vy9)

### Export String

!WA:2!DFz3ZTXv5F8yRMsROqCmytsBY01nytctRSTATtctNWO1sYwGKLYkz74uaTND3JK24v7U5S7AB5Ylf1qQbcVjy6a)U43fcO8YWv6cUMjxW1pJh(lWdd)b0)c45C2vYQkUth6m9MMlYQ9CEoNZZlFE(Ewp2Mt6P8QjUEILMS5KgtAC4vowZHzqzYe9DmyoUUtiBzEWbeMHufhhlFtxT9i1DYLUZ13o963FPu5lX2VyTAEu)1(hnw)gNb)xN6mNa3C6o2xy8N6k9i26nCyLCmT91wjZ6vYO0l8mwXXYH9ngBSXILmGz5(cn89D9(AZpp)asy6m)Gty(KmIUVPJT3YkE(eMFCTAM2MEnIlJp8J32NzwVoL598ZXI(5d7Aq1cQvRslxkBTm5lLDJ8Y(4lkKagjzBpxQLvodV4h7fOr3LA7xgT2C)Evxjv5kvlxjLsLbtvIrXPukxkt(8k2KMuV4kIj0wJsS8BihGEHMRfPfL1jWoYfI)(yetz2eRnrxd9EshITztcpqwg(8zFmL4rl7ZO219B8zGPKTDSPhzGUh3IQCNL5rXSOHxBUP8qbMvUjX0ol8LXfaZcZbFf4Q4ZZn6iYgupD3CLjTKi22ob26uPAomjIMPLPFlPMMEEVSKHJrDkAGHKlHXAjSOMjZZxAXfKWZwYPg(E9g(jy7ggdNTlMuuO15fJ4YwoeJADc8Ov1TiEEY(SaQMpXctntR0maXL4YEMhqNgsgxryYCAEM21TOSTsPOKROcoHmwl05wWoataynz8J0IOVqcjwSyLITqILu80XToMwi90OB4Zmyi4E(Y3pGWOszdSSK2QHPpTlt4K8KMIGhJmVm6oN9XH)oKBFwnpAtm8uwmXcjwSRVJEuS(mLM(LmnCNQOl1gDAPurjYMy451RgdbbS8r8jXE)qgplFi(jQvEfLmzwVJh1QMa87kxSsLIfYNjBLi4pNnE0XoIe4JlSORGUJNmW0OxrJDwE3RTW(7DZD0WQpM)J3LtbMH20Z0gltHy0C9eHwyCO6EbZ62omA0ULHtOzymhMNkRv)E0V5n(38E0j1V7HZIR13Y0gteBujFU1ZapfCwOYyWZapR7e6bE(onRq33FdxdIp2njECm6Xo8txFltde9tHVcFoKN3KH9fEeSyKC2Kj48fpti5ylHVkA3whZos36w5D2tQsdgL4lfLzF9x)XrRvq9jlNA7UgovJgt1DM(Zgg4vhA)IgcM1v6jmQVpmWg4CXHjIdNpXCWK)tSB5YhXrxrNm)CvB3V5BYLX5wXPPg6JI0OxNbw5ovP8P2oJsvLmRMz9QPZvoLC(mPzb2ctu8nBsnGVuC45HxaUuC4fbj4cWfHVa8fHzMgOqn80)pWuD0f7VLtDwKy0rfi8wdPRktjSRbxGvTqUYLZKg0tIGjC5UrEuEN6InVo0qeadsgQT7hYkLW2RTFmF2(dPESWwNaMoDduVsT3G1MZOr3tMaK6myhHDGzIJ(77HzRxeQlZl(Y8050WsXGl7orzFe9PZNfhA(uy2teU6tUipKBZpaUXQC3v8gxOuf3s3ZZf03LwjuQSGJb9VDg4LiqoTWof8qS9DNilZ8aPBhqm4TzsvQaV8zHx5Ronm1rOmexLGZ)2g4aWBbjExXzWfCAalYvuGRl()5vHBmodbnEZYCWsYmIPbKCz4RRcVTQShQYO2vOIjsWQWRHgPKwzJCPHKtdpufEvCFQPGIK(TuBxZIUVPMfvnPp1wTR)EyzVvnmAu1c)nAIdAztIn)x4vlOhDXJ8AqmC27oHnIXGBj7J9wWNDCqgwPlE)c1q0r9GNlYYTdT8sNPNHPh)YfEV44Wtpg7EyRPzTwYC5eiDOmLsjUcoumoKngSkSMIEFTZyqHER9AlVX1ZE3nYgKdYhV9EOe0wmIB7TI(rVWJ8KBKHsXHBpnuwfUc)UQrVV5AF03aD4SWgWMdjPaBb3b2gUBOAb8gW3c(2W3bQQcQ4QiNs7jOPISe2lcg8(goW)r1yXxNjoSfOdnXfAlS2rfCvsxm9QzaMQyB8uHaC97ocGd7b7hI2qRHrz4abddVjhEHVBeRcFp47d)Gbmj8w95q4hEkai0gPk4ThWDWduHFuiRbpCyodEhv4qv4hRc)ev4NQcpsf(zxe(5iYa)IiEb(Lp45GF1Lod0HdeWVg(nd4G0870pHdG3TpdSQ2vVZn0BC7Ll0cza43c)o4)7tP1AzUW5N6l1YfqP9tRsxZ4MnvU723FND1)eSsJ(d3TgTAxdEd3eRWWVwb)ATrV(FgP1WpNuYp86FNWR)NrafH8XtCx)INYD9cacPNZfbq)9tdGq4Hxn5LsE1fHib8WjGdNMtmhvNIF6JPE5go7v0(ypXJvW)ihui0MBplee4lJdqiSjUqvpk2qod()53sNovHuOYcN1qi0DItUNnRfPUxYghHrRv5HUtfzu098uDpp32pGFOY9wXNuJFAP(oQNg3Yjvo1(McJfojcT8OnKOpHBdlZ86hwghQmpYiN7jg5db2pfUEe4Faw)OHWAeXX2Kr7aW(KtGDEhgc8iGIkif6PvXMzU1(53S5nfnbriF7(GvFypc9rkh7dW2JHyDEFtiSJ9mF4ClEO9X25x3X(v4L3NeBxNJEwJaUcoKZTDXNCgg13I01S)4HL)fv43d)bXSSq(Ip7FvvO09hBGl99eCwFbV)ud4ppepj2soWeeU1)pR3X)uJ7H)no8VnljXYQphXtRFIO)HKX70huEKGv(Gibcd864hx5QiWyicslSsk0rJGhUYvHEgAT2E11uKPlCV(W1OIMp9ytU7)6o)3)

**Comment by mrbuds** [comment]
Where are you doing the test?

**Comment by Rahuruk** [comment]
My apologies, I just made an account here and I'm not familiar with this site's customs.

When you say where, do you mean what game I'm having this issue in or do you mean where is my tests as in I need to provide a video of me doing tests for you.

**Comment by mrbuds** [comment]
I asked because i guess you are testing it outdoor where wow api won't let an addon use SendChatMessage, but it can work in dungeons, using an older version of the addon won't change that.

**Comment by Rahuruk** [comment]
Oh, I understand, my bad.

Yes I was testing it inside of an instance, but during testing I ran into the instance cap and had to use the outdoors and oddly enough it outputs to say just fine outside of an instance when I use the older versions. I do normally have the aura only load inside of instances when I'm not testing it.

**Comment by Rahuruk** [comment]
Why is this closed? Nothing was resolved I just answered the question about where you can test this issue

**Comment by InfusOnWoW** [comment]
You confirmed that your testing was flawed? WeakAuras does not print any messages outside of instances via say, and thus any testing you did outside of instances is just inconsequential.

Anyway, can you create a minimal aura that shows the problem?

**Comment by Rahuruk** [comment]
Negative, you are misunderstanding the problem. Testing was done inside of instances and confirmed not to work. I just noted that I also tested outdoors and had the same issue, but as you said that is irrelevant.

Also you ask for a minimal aura that shows the problem and if you read above I  have already provided that in the OP.

**Comment by InfusOnWoW** [comment]
This is a minimal aura consising of just one trigger:

!WA:2!DrvZUTTrq4iOw0a6IIy1edeGEWWa1hnkCrCa6nrzkhvilPqs)xrtLxsosCRP2LD3Ls2(w0PCwpc6CpPd9bWpbeef9bipc(jOZUKsnP8a35VDM5B43WATBmPruJOpS3sAiN5XZeHW39eXT9hnscQAI7QewryHXCXaoLPcA50Z3XTiKZtI4ZyEZOPW1pSw1jAmeBRt31Zvc64XGq(n7lQe)lB1DPGlmfyQpkZcmcEzJgrVD1Wwn98h65301FEuMGOOCwJJY)6Iw8jbe1Uo6yLlmxrNL0xmOBZRCCh66CItVHh3XRPDxNJNltHKKorsRnfyGaWc46nWPBx7mgvfKMqUdeUmYeqAvKjHHBs71lJGaSJ8rzXBC6oO9zDxKXQaGv62KqfDk4xQFkpc(ZN8ioxabJKCoIwSTjpEdaPnXoju5Qbs8cjKmYm)Y)sSasIsJqiEj2JUWy8oYFAN8Tkq1as4nJf8mw0hEEAdfCRAOmMGZ2lR(AK(sJrZRrCXecgqLGnJZGfBCV33ltF2NKHw8eU4NRvRw9pwADDtz38m)(PFRXijtXXurdVGgPITBIQpwwl6TqKX47lkjexv1rpy8)7zsfD0DiafCfcoF0ODV(9CY3sG4shZstGHM2Oo(SOcemv6ZAlO3V7BZir4GHSRV)NH91vQWyBgxeDHGKo)IkHYgykvsdsGRRW8NqAt3UtVEivXUVVF)tD7CYB8l2uAp69WlRq0LFwD0En8G(N53TtpN)PyCcFwBb8hzal8UbFXpCWHVQeDAhR0VwNH5Af9LlcYukoR)uqGSULAZDb2yv8lmXVgzl0kT2mzEajLNS2sST2zSP6(X0WByGuw3CdVqscuk2LIM32uaBCUaI4GyGoow9E7eoj68afgktTJ7KSef1APM2hA2TU2nmHiL7K)wlBnPTuahlAHLcd)udL8Nk0SFKSEKRurekRGrugvgBzJhkRfegDIzX9O8lB)aqKGNsya7xLVv((fR3RhQ30esa)nrKCUoot633EcHYAN)RMOZFx(VLpepV6)BzfLvY3XuzzFpNpPM7mdXCPIhoTCj8Pd2zpA0H9GzU)hHB1ibUZJnfYXQ)y5382At66h41Y1XPNljjnMupaBUr0XwcktNri(WmA0QwVU9VC6vSzENFv6Zx)tpnt)yQKGKVO4LAqrntjR5RJiUaxRWA1pT0rdP7pEWRp4vnM(3x(V

It works. So the problem is either, something caused by the additional complexity of your auras. Or that aura doesn't work for you either. We need to know what it is.

**Comment by Rahuruk** [comment]
So using the aura you provided, I added an additional trigger that checks for non-critical damage, and outputs "whatever" to say.

I walk into an instance and moonfire the first enemy and it does not output.

I then remove your entering combat trigger and walk back into the instance and moonfire the first enemy and it outputs.

**Comment by InfusOnWoW** [comment]
It's not worth my time to engage with you, if you can't be bothered to test the aura I posted.

**Comment by Rahuruk** [comment]
But that's what I just did, your aura provides the same issue I am having with mine.

**Comment by InfusOnWoW** [comment]
Please just import the aura, enter combat and tell me if the icon shows.

**Comment by Rahuruk** [comment]
Correct, it does.

**Comment by Rahuruk** [comment]
But my issue lies with that trigger's interaction with other triggers that used to work in previous versions, not the single trigger by itself.

**Comment by InfusOnWoW** [comment]
See, how we reached a deeper understanding of the problem compared to this " TBCC: Enter combat event trigger broken"?

That's the benefit of trying to create a truely minimal trigger. Which is why I asked you for a minimal example, and even went ahead and provided a minimal aura.

Now we need to figure out what breaks with a more complex setup. 

So try this aura:
!WA:2!DrvtYTTnu4OXTtA1QiLy1MoPD8424LEADhNmt2jkt5OoYsQK0)1nsGKqKOMcGfauY27IwL1ArpaADxPf9a4tagoD6bWhbFc6dGukjvlOW7hG333dFpuPD9j1dRh((Dxscyuxwgpa)IhLJYKXmE)ujHrfv530F8ybwwzfIga(hWiuPFl7EE2o5bmwsiBg1Dgjfp6U1M2Hr4yokWCcVYrirC5z8jyHafHT8WczATsRHsPy4ugjax5UnUUjf7mWPtpVLHSHLEhTjCiSF)0e0nyUfHsKv9hd)jIRoxYjrryU472JxU8VTmhgEkMkVxK5Bw4MnEm56vdB101BORxthV5HzCKgT7(thO(Q8wSj(i5o26KfB22aog2MJ7a7UDNlsXjjDcfvxyIPRs62d628sBNHo2hB3B4rDCBA11(O8mbE4MKg5qrarQALbixvBzi2hqJheH)w7UdAFA3fz0sWxDp12)PQXIadCsyrQVoVe0N2QLTRR6Bm4DzjE7cz89QA3RlOWCBEkuKrQxO(2LFWwvt9dQxQ2RAAn9n0uSxr1oHfI)Rh9aC7I5uuYzqFeAiOhUcJtBc0nq6OBrXle4KXgvG6Zb4lqsDVdhVe6to4i9v(BAOAKdM(OGRI4SmA47FwADj(A5qrmcuixuQPsFUXP5ZygFccsOCHfLrXl2eE3xksFYhDcTyjm(VuPsLTUVW7Aqz18uV(Pp14euYm4OibNtcLXwnbZhkQf5ACOX57YlK1xwIO7mX)9mHKm(gGGCMeiNh40Qx)E2QgCGx6CwAsmWaJTGFlkjbvM(K2CYT78RzOqOXG2XZ7t4(6kLB8nJXdpNJsNFE5IcamLii(j4rLC(Jg9sR1PxpqKz13ZR)joDo(TE5BkTl5w8Zlz0fFsD0rnQS(N61Ttp7)npkHnRnh)hzyAWnd(SFC)doSGD6aR0FwFcZ1g6nN7NjLmA)Pyom(Tu7UlMgjJ32K)AMTqB0AtN5oqpE8ApXw6GXMuCdqj4TmaXlMeCffgW3YePlbwxZualOVG5X(XysuS8Dwjmu4z(syNuzdNjzjssvNGeKq0qnQ6sT2VyEzKLw0QDAjG2Ijk3Op1uXs)K3dfDQ2CyKu703TLJTDp(1Rj(6h0ItF26LAPWrebcUDcJxGOKjMhoEL6lBRAOo8omsGDLCtB5X5RFxX8MgxGHIgkMRZrxp1HwtqeQzJQjpwrvmvkS8P)FplLSGPfdKFXGg7scpOhEMZheFoOK0y0woZms6vJ1ecabO(26Gms4QwVU9VDYL0zUNDjNq1Neo2hWYysuvRBzSjvwQrgP4j)veAXmiyvvnEuDHZpV)R3)W6t)Nl(Vp

That aura has two triggers: 
1) Entering combat for 12s 
2) Combat Log => Cast success 

That aura works correctly for me.
