### ISSUE TITLE
Change link in information tab to not include version

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#3466]
**Is your feature request related to a problem? Please describe.**
When people share auras (especially streamer sharing their Ui or people just linking stuff to friends) they oftentimes copy the link which links to an old version of the aura and people just blindly import it even though it says OUTDATED very specifically at the top. 
**Describe the solution you'd like**
Simply remove the version nummer in the link and display it somewhere else in the info tab 

**Describe alternatives you've considered**
People using their eyes
**Additional context**

**Comment by InfusOnWoW** [comment]
Well, this is on purpose. It's meant to link to the version that was installed. Now, you might want to ask wago to modify how the outdated version is shown.

Because people are looking for the "Copy to game" button, and as you can see the warning is quite far away from that button.
![Shadowlands-Dungeons _ Wago io - Mozilla Firefox 01 02 2022 10_30_17](https://user-images.githubusercontent.com/12950521/151943831-184852f1-d37e-4752-9a39-1d4a3b6c5fb0.png)
 
Maybe a better design would be to offer two buttons, so that the user is forced to make that choice:
* "Copy this outdated version"
* "Copy newest version"

But imho that's more of a wago problem then something we can solve.
