### ISSUE TITLE
Built in text subregion of raidMark returns text if index of SetRaidTarget > 8

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3473]
### Description

https://wowpedia.fandom.com/wiki/API_SetRaidTarget
It tells that icon should be invisible if index of SetRaidTarget > 8 , but the builtin text subregion of raidMark returns text as the picture shows.
![WowClassic_ezJqngASaF](https://user-images.githubusercontent.com/46548538/152687091-f52d5f14-a9fa-4a35-a9c1-8241fb9b2bf3.png)

### WeakAuras Version

3.7.8-1-g9b6154a

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. creat a builtin player info trigger
2. add text subregion for %1.raidMark
3. it returns text if index of raidtarget > 8

**Comment by mrbuds** [comment]
For context and my own curiosity, what (and why?) is setting a raidtarget with an index above 8?

**Comment by InfusOnWoW** [comment]
I think this is the context: https://github.com/DeadlyBossMods/DBM-Retail/wiki/%5BAdvanced-Guide%5D-Extended-Raid-Icons

Looking at that it's good enough to simply extend textSymbols with 9 to 16, which then should be empty in a default ui and work with that extension.

**Comment by mrbuds** [comment]
I'm not sure that it's a good idea to extend symbols, weakauras use {rtX} which is nice because it works in chat frames too, but when X > 9 that doesn't work anymore (using dbm option)
Using |TInterface\\TargetingFrame\\UI-RaidTargetingIcons.blp:13:13:0:0:64:64:48:64:48:64|t notation (see https://github.com/DeadlyBossMods/DBM-Unified/blob/master/DBM-Core/DBM-Core.lua#L9967) would break sending symbols thru SendChatMessage

![image](https://user-images.githubusercontent.com/189656/152696162-3c31e22b-0822-4533-9505-e3062c8fc03c.png)

![image](https://user-images.githubusercontent.com/189656/152696137-c59f9934-1626-43a4-9349-d5dbee73e15e.png)

**Comment by roundzero** [comment]
I found this issue when i used o-pie , which has a builtin function for setting and clearing raidtarget , and it set index for clearing as 9.

**Comment by MysticalOS** [comment]
Correct, chat messages can't use anything above 8, and DBM wont use anything above 8 in chat messages either.

Also for context, literally no icon option in dbm is on by default that's above 8, it requires advanced users to jump through multiple hoops to use (it's basically a feature for RWF both DBM and custom BWs forks have played with, but will otherwise go mostly unseen).

It'd be a diff ballgame if addons could install the textures for users, but they can't...For the average user, i don't expect this to cause any issues.
