### ISSUE TITLE
Closing whisper tabs in combat glitches if WeakAura addon is running

### ISSUE THREAD

**Issue by RevOB24** [WeakAuras/WeakAuras2#3486]
### Description

When I close a whisper tab in combat, if weakauras is running, it will reappear on top of the remaining windows and not be closable until out of combat. Tested with no other addons running, no weakauras installed. Bug Sack/Grabber stayed green.

### WeakAuras Version

3.7.8

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Set up whispers to show in new tabs
2. Whisper someone
3. Enter combat
4. Close whisper tab while in combat

### Screenshots

![image](https://user-images.githubusercontent.com/99904554/154537182-8dab5732-e2da-4d61-8fa4-0506ac7b2386.png)

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/8090849/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
I believe this is a WoW bug, specifally this one: https://github.com/Stanzilla/WoWUIBugs/issues/4
There is as far as I can tell nothing we can do about it.

In the chat window you can see the message "Interface action because of an Addon". That message means there was a taint problem.

See https://wowpedia.fandom.com/wiki/Secure_Execution_and_Tainting for a explanation of taint.

Spefically this is from the taint log:

2/17 23:20:09.759  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by WeakAurasOptions - Interface\FrameXML\UIDropDownMenu.lua:40
2/17 23:20:09.759      securecall()
2/17 23:20:09.759      Interface\FrameXML\UIDropDownMenu.lua:74 UIDropDownMenu_Initialize()
2/17 23:20:09.759      Interface\AddOns\WeakAurasOptions\OptionsFrames\TextEditor.lua:303 ConstructTextEditor()

And later:

2/17 23:20:27.323  Execution tainted by WeakAuras while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\FrameXML\UIDropDownMenu.lua:888 UIDropDownMenu_GetSelectedID()
2/17 23:20:27.323      Interface\FrameXML\UIDropDownMenu.lua:550 UIDropDownMenu_AddButton()
2/17 23:20:27.323      Interface\FrameXML\FloatingChatFrame.lua:265 initFunction()
2/17 23:20:27.323      Interface\FrameXML\UIDropDownMenu.lua:79 UIDropDownMenu_Initialize()
2/17 23:20:27.323      Interface\FrameXML\UIDropDownMenu.lua:1092 ToggleDropDownMenu()
2/17 23:20:27.323      Interface\FrameXML\UIDropDownMenu.lua:205
2/17 23:20:28.049  Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by WeakAuras - Interface_TBC\FrameXML\UIParent.lua:4665 DisplayInterfaceActionBlockedMessage()
2/17 23:20:28.049      Interface_TBC\FrameXML\UIParent.lua:2564 CheckProtectedFunctionsAllowed()
2/17 23:20:28.049      Interface_TBC\FrameXML\UIParent.lua:2600 HideUIPanel()
2/17 23:20:28.049      Interface\FrameXML\FloatingChatFrame.lua:1652 FCF_Close()
2/17 23:20:28.049      Interface\FrameXML\FloatingChatFrame.lua:1638 func()
2/17 23:20:28.049      Interface\FrameXML\UIDropDownMenu.lua:942 UIDropDownMenuButton_OnClick()
2/17 23:20:28.049      DropDownList1Button4:OnClick()
