### ISSUE TITLE
Losing all of my WeakAuras upon updating the addon

### ISSUE THREAD

**Issue by lemeziuss** [WeakAuras/WeakAuras2#3504]
### Description

So this has happened once before, in 9.0.5. and now at launch of 9.2.
I update my addons, including the WeakAura addon, and everything I had inside gets deleted.
Both times I've had about 60-70 weak auras, and both times everything is deleted.

### WeakAuras Version

3.7.11 

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

I've had nothing 

### Reproduction Steps

Update addon through "Curse Forge app" 
Find all my weak auras are gone. 
Every other addon is okay.

### Last Good Version

3.7.10

### Export String

it is not even there, it's deleted itself. I didn't tamper with it

**Comment by InfusOnWoW** [comment]
There's not enough information in this ticket for us to investigate. We have not received any other report of deleted auras, except a problem on opening options.

Do note that we do not control the update process that CF is doing and if you suspect that the problem is in their client, you need to contact them.
