### ISSUE TITLE
Be able to change the Alpha value of multiple Text/Icon/??? Auras without it resetting the color too.

### ISSUE THREAD

**Issue by epigramx** [WeakAuras/WeakAuras2#3515]
**Is your feature request related to a problem? Please describe.**
I keep noticing this feature missing: be able to select multiple text/icon/??? auras and change only their alpha without resetting the different color settings (and ideally with a specific value instead of a vague bar). 

**Describe the solution you'd like**
How it should work: exactly like the Bar Alpha setting currently available; if multiple Bar auras are selected: the Alpha setting can be fine tuned separately; their different colors remain intact. 

**Describe alternatives you've considered**
None; that's mainly because the solution is already implemented for the Bar aura type; it's missing on the rest.

**Additional context**
https://discord.com/channels/172440238717665280/172440238717665280/948359740403118200

**Comment by InfusOnWoW** [comment]
Icons have a alpha setting. For texts, I don't see much reason to add it.

**Comment by epigramx** [comment]
@InfusOnWoW I have a long list of texts in a dynamic group so it would break all the colors if I were to select them. 

Both texts and icons have an alpha setting by the way.

It's just that icons and texts can't be multi-set at it.

**Comment by InfusOnWoW** [comment]
The alpha setting is separate from the color setting, it affects the whole aura, and not just one part of it. That's why the alpha setting should not be confussed with the alpha channel setting of the various colors.


That's not really needed for text auras, as they only contain text. (We do have a sub element that can be added to them, but that's a rather niche situation.) So adding a alpha setting to texts is rather pointless.

As to affecting the alpha part of the colors on multi-selection, that's a valid wish. But not something we'll do. It's too niche.

**Comment by epigramx** [comment]
Yes the issue is only about the color itself of the text or of the shading of the icon. 

It's not niche at all! Many people make big groups of text or icons!
