### ISSUE TITLE
So'leah's Secret Technique and Item Equipped load condition

### ISSUE THREAD

**Issue by Surarn** [WeakAuras/WeakAuras2#3538]
### Description

The item equipped load condition doesnt seem to work with So'leah's Secret Technique. 

Tried both the name and the id 185818 as can be found on https://www.wowhead.com/item=185818/soleahs-secret-technique?bonus=6805

### WeakAuras Version

3.7.13

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

Go to the load tab > Item Equpped > enter name

**Comment by mrbuds** [comment]
We need you to include an export of the aura before investigating.

**Comment by mrbuds** [comment]
So after discussing with @Surarn it happen that they have an other trinket in bank with the same name but not the same itemID
https://www.wowhead.com/item=185818/soleahs-secret-technique?bonus=6805
https://www.wowhead.com/item=190958/soleahs-secret-technique?bonus=6805

Aura's data saved itemID from the one in bank instead of the one equipped.

**Comment by InfusOnWoW** [comment]
Right so what we do is:
* Convert the item name to a id on entering via GetItemInfo
* Check against that id

For spells we do have a separate "exact match" option, which changes how the check works.

So our options are:
1) Do nothing. Items with non-unique ids are very rare. And in that case the user needs to enter the "correct" id. Also entering the correct id is almost always automatic, since I think GetItemInfo would typically prefer the id of a item the player has. I don't recall any other instance of that. So we could just wait until they do it again.

2) Make the ItemIsEquipped use "non-exact" checking similar to what the spell option does by default. That is instead of passing on the id to IsItemEquipped, we do IsItemEquipped(GetItemInfo(id)). This isn't backwards compatible, but I doubt anyone would be affected by it.

3) Add a "Use Exact" match, which allows fine grained control over it.

I think 3) is not needed. So it's either 1) or 2). 2) doesn't sound too bad, so I think we should do that.
