### ISSUE TITLE
All of my weak auras are gone

### ISSUE THREAD

**Issue by richard12511** [WeakAuras/WeakAuras2#3702]
### Description

Today I logged in and all of my Weak Auras are completely gone. I had hundreds of them, and it took me many weeks of manual creation to make them.

I'm guessing some unhandled exception or something caused the wipe. Is there any way to recover them? Also, is there any way to maybe fix this bug so it doesn't happen again? I might be able to help in some way.

I didn't have BugSack or BugGrabber installed, as I'm new to WoW, and didn't know weak auras could bug out so catistrophically. I'll make sure to install them this time in case it happens again.

### WeakAuras Version

4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Login -> type /wa in chat and hit enter -> see that all weak auras are completely gone(nothing in loaded or unloaded)

### Last Good Version

4.0.2

**Comment by InfusOnWoW** [comment]
If you use the WeakAuras companion, that creates automatic backups.

WoW itself creates backups too, though it overwrites them if you logged in since then.

This is our bot response in our discord:
If you login and your WeakAura's are missing, go to the World of Warcraft\_retail_\WTF\Account\<ACCOUNTNAME>\SavedVariables folder and check the WeakAuras.lua file. If it is empty, check the WeakAuras.lua.bak file. If that one has content, delete WeakAuras.lua and rename WeakAuras.lua.bak to WeakAuras.lua. If WeakAuras.lua.bak was also empty,  you will need to to rely on backups or remake your Auras.

*Window's hides file extensions by default so you will need to turn these on which you can do by going to Control Panel > Appearance and Personalistion > File Explorer Options > View tab in the new window and untick Hide extensions for known file types 

If you have not made backups or don't use the WA Companion (it makes backups for you) then as a last resort you can try putting the following in to chat in game:

/run local L=WeakAuras.LoadFromArchive local h,m=L("Repository","history"),L("Repository","migration")for _,r in ipairs{h,m}do for _,s in pairs(r.stores)do local d=s:Load()WeakAurasSaved.displays[d.id]=d end end C_UI.Reload()

If you need further help, the discord is a better place to ask.

**Comment by brett1337** [comment]
On logging in to patch 11.1 it keeps deleting my weakauras, I logout, replace with backed up Weakaura.lua, and they dont load and it wipes the file each time. Any ideas?

**Comment by mrbuds** [comment]
please don't necro tickets from 2022 and come on https://discord.gg/weakauras
