### ISSUE TITLE
[aura - multitarget] trigger overwriting GUID

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#3711]
### Description

It seems like when you use the multitarget unit in a bufftrigger, the GUID on all existing clones gets overwritten with the last target.
**Demonstration Aura = https://wago.io/WDfFYhCp9**
* It prints the current target's GUID and aura_env.state.GUID from Actions-OnShow for each new clone. 
* It also iterates the current states in Conditions when I move so I can run through them and see what's there when I need to. 
```
UnitGUID Creature-0-3103-0-13274-153292-00005EB81F 
state Creature-0-3103-0-13274-153292-00005EB81F 

UnitGUID Creature-0-3103-0-13274-153292-0001DEB81D 
state Creature-0-3103-0-13274-153292-0001DEB81D 

-iterating clones and printing their GUID- 
Creature-0-3103-0-13274-153292-0001DEB81D 
Creature-0-3103-0-13274-153292-0001DEB81D 
done 

UnitGUID Creature-0-3103-0-13274-153292-0000DEB81D 
state Creature-0-3103-0-13274-153292-0000DEB81D 

-iterating clones and printing their GUID- 
Creature-0-3103-0-13274-153292-0000DEB81D 
Creature-0-3103-0-13274-153292-0000DEB81D 
Creature-0-3103-0-13274-153292-0000DEB81D 
done
```
So in this print log I cast SW:P on 2 dummies. Then I move so it prints all states. Then I apply to a third dummy. Then move again.

(I was testing on Retail but the issue came up in the Wrath Discord Channel)

### WeakAuras Version

Recent Dev

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

NA

### Reproduction Steps

1. Set up a multitarget trigger
2. Cast on a few things
3. Check the GUID in all existing states

**Comment by Darhole** [comment]
Can verify also experiencing this issue, just didn't have the technical expertise to know this was the cause.

**Comment by mrbuds** [comment]
If i apply to my target + 2 nameplates without targeting them state.GUID is different for each
![image](https://user-images.githubusercontent.com/189656/181742859-e8f17971-b45e-4d7c-b267-425b8089a473.png)

If i apply to my target, move & select an other target & apply state.GUID has guid from my previous "target"
![image](https://user-images.githubusercontent.com/189656/181743245-fe682e12-8fde-42a2-889a-bddb7a2a57e7.png)

Tested on Wotlk PTR as DK with 
```
!WA:2!1z1wZTrsv4Osvynt2aooeZMlegCrm2WANyVKSlBrQkASLIukhzNrY2jlBkPEMULMoE0092tpYxkwGiwcHRliGx5b9tqpXJP8d8CxU4haLFNxYVao90tKYLnZdZm9Ppx6ZTVtNBRPIxEvs3P6mfEk8txSps4VgjQTm4lM(ypMateoi)DWcgNpPti9GdqcSDDglus5I9wVvRyIS8ZU8bNq)i2pJWT6S5w)kGWquKFatSbJgj9wPy16fDh0kjmCfQWpK00nMJ8jNuG8Luwu8nCJLiH0YRfnIghy5aFKw9KcA72er8fMvK97tgGjEjTAvFForuU4ABuAZ1CKWcxuIaTCVyojmSco2644epsxsKSgWnDVHnwPqT6nQvVGBDNeq5E8q0(eHBeQdj2YnLvVYeuOmyKOBiiGOU12O4AR1pjk7iyn0NfM0jQM2dY7jqyAs8x8U9sIjRr7qLbUOqA7i1ecWN0cKBaOqxsBTJA5eYq4sEsuiyGPD7KaHtlh4y7pTAolx)quCS(pNy6be9ph5LLfwHfYe3jF(8BK)AlE9Ec2UMtGafr7GKKa3yFqR59mjVGbMVfXTj8Zu7ZsqcIDjidyVDavsgispq644H49HOa1VTGLWZKQgy9t6eZesNiwez5ekEyT79OcZ)jLXTU2D6htcBLMBxU(6BaNfjsNhZ9CGcreHc3cYAaHDo2hCAjkswcY0mHNBHvRSzTJqjsO4yDEAY36qJnnvqFDpqKw02wdKm)Ug1mr3Nndf7wLSR9YdBjGuwnPajr573wqXBtXYGt9Ctbxj9UAVYR2kUflwTNMd96zCxDOXovIaZK3bC3DDwD9TR6gQtBNkBxtyoxUC5hahem1CehsJAXeDs9sR(Mio87nuVBPdjOy95jT35DuNv9HhHHAr92n0vMIyIwrX908PpjQp0PdIgvs5MYTQMQUAt47PFDkt5FHN(JhaDkIDs9XZnGcAQglr4tU0j82f1Mvz1(BVARspiyf(pr91YPEh1ehLkG7lsj8Z8kRVldtCkSz91xoreYVyGuYJ)4REvTUwKYU6iLD1LvNc8Uz98tILSoCXclSfvGAdigAmGgfW4vHmWC62UgKOUlczzjzERfwGlGIG5MztOj72Bwz1zEF7r)c94TjYzM3kJhwKDCaBxGLxvnlQ5E((ywdJ1BQ(gwQtBP(M)Zzvt(VhOLzLqOSmUjeU(w91cN2hFb3RF9R9HFeKyJwpkC)MQlQUK6cwQZzPMw9TfqhAvGTMQ3tnN67OUS6mIYfCVlaHO(UwGMFI6mQPan(E8PawBG8G6)umbDqtl15putNg3H1Lg1U5XJ5YWXfhSYOsgnEqdnsttq5dX04hLebGDDjQM8PmUvDdGYAS2uF(fBLUplAo582cImrezl)zl9qBseMFguQOzcOnw(0AHg(VauiV6M7O(y1e98qzLW51LWysmsQRgjbISMPtQUYDMwD2Jaqjn0IURpcNraQXjgcp988VNKSNSr6ltTFdEdjTdPbxq8PAvLV)iwM5kC(5)keW8JRwo8XPBnc6q9q(ztPaObmD)KFAvUtby5ZnAHUhX0E)y(3)TDAcjTr(73OviJjcomLHhbHxAR9vtmifzIuhi6uD9Qf5x(TPfZQCQZkGWGE)Jm4j33GkLBqQmJd39Z0rKKpzjb9a77LGWAmj7615tzC0aeMTBMcY)keFGH4LoH582fIMEWuXJsxTlGdTTaX7TD2phnYwA4dNQqLpFstKB8q2bvQwTOBJ1kwQE2rpZi5Y41y5XWBJ1QgS)885FBHMSXdnKbcc06fI3NB)24Tdd3qxT18PN7ROCik7haIBF3ROBYv)90ZI6NREO6Zv)c1V8XQ)wo1JvtO6P(1qR4Vr9Bnv3pv97u)HlDc1Fs9NvFP6VO(Rdn(RBLBxUU6p2u9pop)sVHb1MySnFso1VpVxaH2oaUOYsvUO(IkQzlP(b6bTQ5tF)dtF)J0Vpof50bMuJ1TClxy1v5tcT1fW6cmcMGVlAVGNpUlAuWnDenamOrQ9OD4WC0dtvMjL8GCo6U3a190dqsH8bK)xmhyR3GYPFdkowV(jHcQ7deAOqab4Ln29ZP(OHp4rv(mz5QhuUWU9tboIPyIBAWBykVLPymjYTAXTk6QUTQCg10y1nf6yAIG07f3duvmVXe1nBWNRIEWFl4(iF6kiO5lQTds8PBwzHXRwOMwaVyshaiYDPfV2IlPw5LMS)bUPAuF9jEakV7U6((Y36Z)F)R)lKMCoGX6KZmmC0nHYdJr0OAKa1TSgYeu4ovPt5guED3kFY6vRxyn16xywx)aI)o3qn5j71fjOiOxZrpeXTlkmbUbLFakQnm(yw1ZMw1CVCnPTSJyYXtLGBLjTzIxJWp1(2ezDOSFU5TxWEjBzajYYgEEv2U5y2s3nB43cWTW0xtiQTTF6WmBue2SPMgOmQWwxaVWmg5czW97SJb9TnbTtbWgXlQ1SzOqnnqxjMiB54bZu87BVKrdqNGXwvaAPtATPr2Cevepx882ywkx6hiayMeRdtJDSx8yCHxAw9ODHEfRx(BMZIbJM5gwWw94WfAjc5(dmtc9H2l1gwQtMBQU)N7))d
```

**Comment by mrbuds** [comment]
also %unit stay as "target" after switching target
![image](https://user-images.githubusercontent.com/189656/181744418-3f89b9b9-7b31-466d-b961-65f49319f7a3.png)

vs when spreading dot without switching target
![image](https://user-images.githubusercontent.com/189656/181744496-925d7877-0d19-416d-881b-b862e82185bc.png)

**Comment by mrbuds** [comment]
@InfusOnWoW i made an attempt to make units & guid update on PLAYER_TARGET_CHANGED https://github.com/mrbuds/WeakAuras2/commit/ae93697956f5f1e4d773cc4ecf1ae64167dfe92d but it's crap

**Comment by InfusOnWoW** [comment]
Import string (since wago is going to delete the aura)
!WA:2!1zv3UTrUv4iiSybKtBtutdQ7g0o1yJRD7A7yTngB22uunYsXkWr2DKCCCBwiXziLggpIKLKsYYaffRqXU5A9a0l0JGEeYf9AcJ(eKhH8eShYzICCWADXiYdpNdp)8D(Mj3Zl2ViUOQ0UKHfXV(lNsJ4S2kkMeeu)j71AgMOq6bsKMepNY6YL9rAkNv4nkbsE6bD7Qi6xK7DiwumxwtI6tAnwqcBwjOA1gtrmAQ(743hrz181WH(moJCb26u4K2wrsfbUxSAcbPCoWCZ3yx2uljSE64pnqPrsDnZsMBA(jMFQ5Nb)FRpnSlLrvXFS4Pkss3d5uMoSs1gTQguAGmr8zXATq91BT1iup(Mu(whVB3ANexr8OTkj1KZGSKmXpHE(5ijEMTo0KpqgrU3nKNLMN5cvK(djYGT38bBU9fObAiNpqyZcvHzQbHbKE21p9UMLUa2gIIoTNKpGHZeaLpsQGxVS43AVZ2UhPL12I2AAFsBHKervGJYlw(hrN0fbwvXIFU7mis426C0XuSo2VmSDMKRHMwl4y)gh0O6fPDOxKLjxK5tM2wT9BaDerrNmvmcZhDsQE37gIp)6cZespu042Dt4Cz87svGEgb7IHVv4DD21NJBBXtDEJ7WHqQgMq6mDrejUvnj9CV)2aeg0d51QvQMVAGst7o2CN0GFexIpwIetooBXBtJ)3379lFuRde)6Rlms3LB6IZx5(ISIuwYNtCRpOIuHNWLpnxUC5ZeNQR7QMvVrJQbT3VATwZCNf5uop8ZSKeA8wHI1VUqbpMH6tJARJLevmpbp(k9ISEw(l7znPNtw(135hbEWYwaZbFU5(Mvn)oZA5mRB(9M)W9UHzJV18aZ2MsM7y(sZF08qZoMVAL7ZmpkN5RDPM5pnpnvCd)MhNLcM)IzRoM)AEt5LLJZkobJS95)ZnLWaHfS(jsuKBsyhFyOuxWC7vdJGogVVGTXgpNkr9aoMwCEs7Yy8UqJDneqb0MWgUPYcvxVGqc1Y1w5iW8NCu9Dx5l8wSeM(7r0RSqhNfGcx1fBA1D9PyE70BUJPyHqyqUlT3viSojxOLeO(UtxWbmNlPeM2rjnBVdcQ)3pOrRY7VcfxQbz0BDg7Nqy4NXXKsL3DxXTgOiLXwqjbtWpJYIN70ApkgtybnQ(8QbVdcwIKHsEEAr603DjNWca1H5FWMpCsisMkjVdIDvNJolE(hG3m3P0akE(jVQ()uVxJZ3R8iOQy7dK4zAEuwh5xMRZ34FoN3p3mxG5gm)fZ7AjPbIvOdK33sZfNwAALsbkwRUnM7IIiVSccM4y98rYxEu9nUC3gnTgmZsztD98F1QbrXKOt3rQL0E9iYpzYqKKIGbBFarpkyikzajVmkgX6ra1NiKCG2xpEwANkcQQMK7AQFwUDPD9yC9LT2e4E94YpsWF27jeDly8zT192WBBpDmHvW7Ju6XxQeCwg2zdkKFiBQ4fLaeFkpedNEOvg4iQ0ZIK2yfRvj8iuINc81Xe0PLb)R20610eTPf3vJlZ2EjMMI)cVTT2ddKP3tDqIdM6rzEcevQwtTUhMd645bjDke2wUEFYy)Lg0Fa82jhaIfE)ZS0cdxHlGlaIDV)6dOHe321Jd4PiCli2SZfxrwUm4lH2lw)y)eocxluJamV(Ub9hKOPfcIGQQ6UMrf8vafu6cbjYUim2z4Vzsgcq9FxD6aw2Mcg6)tYhXoGLmUd8nfHd621(Ih5ELdEwTJ2xcW9gaSSJ)ayI3mAQTmcKIauP0d)QhzwkWkOuGtuHaYqiOc3JGs0XVfOxD7pusG3)e08WQ7V)cHnHlIE282vk3Sv7MTkh0AceWjj1X23ydL6koeqNvn)lig)UjqC02gcDERDfkuXLH2IvhZKqrcAmrA((zvwG7n)B5Ev3)qidEJvFQQpFiGH6ikEP52Wm1flzMikMI3ZGl7Z7rJeFw3bmh35A619KeykK5P)hB)n2(R42wA1HKmdSok)Cmv9kNjdjM6bOermkF6mELfD8zs3hJ4QY2IhWVe4ujU4W))lmnmh8d
