### ISSUE TITLE
Maybe add spec role to load conditions

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#381]
`select(5, GetSpecializationInfo(GetSpecialization()))` gives a role for the current spec, whether people are in an instance group or not. 
It came up recently on the Discord and seems like a nice simple thing to add. Just up to you guys if you think it's worth adding more options to the Load tab for it or not. 

Perhaps the load tab could have a role option as it does right now, and a tick box to use dungeon role instead?

**Comment by InfusOnWoW** [comment]
Hmm, maybe we should just replace use that as a fallback to the existing dungeon role? That wouldn't add another load condition.

**Comment by Hamsda** [comment]
I think actually replacing it might be worth to be honest.
Dungeon Role gets set by Blizzard if you queued somewhere, which means if you go into a dungeon with friends and two of you queue as DPS/Heal, you can end up with "wrong" roles, because the one that wanted to heal gets the DPS role and vice versa.
For every other content (like raiding or group finder) you can change the role around as you please and I think most people only have the role set because boss mods do it automatically (according to the one that GetSpecializationInfo gives anyways).
So using GetSpecializationInfo instead of UnitGroupRolesAssigned should just exclude "wrong" specs and work in solo content where you cannot set a group role.

**Comment by asakawa-k** [comment]
I've used it a bit.
So, like, if I make a set of Auras for my guild for each boss fight in a raid. I'll have a few Auras that only load for healers and a few that only load for tanks. But they're all bundled in the same group so it's easy to share with the whole guild. 

But making the info come from a different API wouldn't make that application work less well. I'm also using a load condition for the raid zone or for the fight. 
The only issue I see is people who are using the current load condition as a shortcut to "healing an instance run" or something.

**Comment by Hamsda** [comment]
Oh yeah, forgot about that last one. I've only used it like you described to differentiate between roles, which wouldn't change at all.
The "healing an instance run" would still be doable with the new role + instance load condition though, wouldn't it?

**Comment by asakawa-k** [comment]
Yeah. 
So, at worst, people would have their auras pop up a bit more than they expect and can then go and add an extra filter to put it back again.

**Comment by InfusOnWoW** [comment]
database isn't currently setup to search fields like that but I did a text search on the lua table, there are 5589 imports with use_role: true, out of 105726

**Comment by InfusOnWoW** [comment]
That's a lot more than I expected, so I'd rather be conservative in changing how role works

**Comment by InfusOnWoW** [comment]
I changed it now for 8.0 without any fallback. If we get complaints we can work from there-.
