### ISSUE TITLE
Please Allow Linking of Spell In Classic as Output Option

### ISSUE THREAD

**Issue by Gogo1951** [WeakAuras/WeakAuras2#3846]
Now that Linking Spells in Chat / Raid is a feature in Classic, please allow it to be an output option Weak Auras can produce.

Thanks!

![image](https://user-images.githubusercontent.com/55365231/193337993-c37e59ae-0ae3-4709-bc77-bea74a52b162.png)

**Comment by InfusOnWoW** [comment]
That sounds like something that is far too niche. That's best handled via custom code.

**Comment by InfusOnWoW** [comment]
Yes we accept PRs. But again I don't see the value in this. It's not useable for normal text replacements, and only for chat actions.
So that already adds complexity that I don't want to have.

Chat Actions are really not that much used, and when they are used, they mostly annoy your group members. So no I don't see enough value in this to accept a PR for it.

**Comment by Gogo1951** [comment]
I can tell you're great to work with already! What a joy...

If I get around to it I'll push a PR. Cheers!
