### ISSUE TITLE
Several Shaman Aura Presets don't work as they should.

### ISSUE THREAD

**Issue by jsimarddavies** [WeakAuras/WeakAuras2#3856]
### Description

Namely Earth Shield, and Riptide.

Earth Shield, "Highlight if Buffed" Does not highlight if buffed by default. The settings for "Condition" are "If Trigger 1" = blank Then Inverse (Unchecked) And Glow Visibility (checked) And Color White.  In order to get it to work I had to change it to; Total Match Count > 0 Then Inverse (Unchecked) And Glow Visibility (checked) And Color White. Another issue with the earth shield aura is that it assumes you have selected Surge of Earth as your Talent or it will not load.

As for Riptide; it will not load unless you have Deluge and Surge of Earth Talents selected. 

I don't know if this is a "bug" exactly; but it certainly seems like it shouldn't be that way by default.

### WeakAuras Version

WeakAuras 4.1.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1a. Click New Aura
2a. Premade Aura
3a. Icon
4a. Buffs/Earth Shield
1b. Click New Aura
2b. Premade Aura
3b. Icon
4b. Abilities/Riptide

**Comment by InfusOnWoW** [comment]
Yes those are bugs. The premade-auras are a mix of auto-generation and manual work and we do make many mistakes because there are just that many abilities and we can't test each pre-made aura generated.

For the pre-patch we will regenerate all pre-made auras from scratch. That's in roughly 3 weeks, so we won't fix this anymore.
