### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by Arduouss** [WeakAuras/WeakAuras2#3902]
### Description

After updating on the 22nd, or 23rd I have found that none off my load settings are working correctly now. If it is set to load on Druid it does not load on Druid, it simply doesn't load. I have to remove all load options to have any WA load at the moment.

### WeakAuras Version

4.1.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Apply any "load" condition to a WA, and it seems to just change it to not load.

### Screenshots

![WAsettings](https://user-images.githubusercontent.com/116578859/197563970-ce0cd0ad-1de6-4007-aeaf-02f6ee1b7fc9.png)

**Comment by rgk85** [comment]
I'm having the same issue as described by Arduouss, after having updated weak auras via CurseForge.
My settings for WeakAuras was set for Release type Beta and it gave me the dragonflight-beta-6 version which is causing as you state the load options to not work.
I reverted to Release Type "Release" and now everything is okay again.

I don't know if you are having the same case as me since you state you're already on 4.1.5, maybe you also accidently downloaded the beta.

**Comment by mrbuds** [comment]
We need a better bug report, doing the reproduction steps you mention on weakauras 4.1.5 does not reproduce your issue.

**Comment by InfusOnWoW** [comment]
I tried to reproduce it too, and I suspect that the wrong version is installed.
