### ISSUE TITLE
Weakaura icon for PvP talent randomly just started disappearing after leaving and entering skirmishes/arena/bg's.

### ISSUE THREAD

**Issue by Rittler281** [WeakAuras/WeakAuras2#4114]
### Description

Very new issue that has only started occurring recently that I have had with multiple characters where after leaving a skirmish or BG the WA to show a PvP talent just goes away and the only way to get it to show again is to re-select it as a talent or reloading ui. I never had these issues before yesterday and would love some help on the issue. None of the other skills or talents have had this issue, it is only PvP talents.

I added the string for the WA and tested this on another class and the same thing happens for different PvP talents, also created a completely new WA for it still occured. Any help would be greatly appreciated. 

Currently tested with -
Warrior talents: Disarm, Bloodrage

DH talents: Reverse Magic

Hunter talents: Sacrificial Roar

### WeakAuras Version

Weakauras 5.3.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Make an icon for a usable PvP talent set to always show
2. Que up for a skirmish and then exit
3. Icon will no longer be there

**Comment by JackVania** [comment]
I'll add to this that PvP talents like Psyfiend will only show while in combat while PvPing, regardless of PvP status. The icons disappear when out of combat, even in PvP zones or Warmode on.

Create icon for any PvP talent to monitor cooldown
Get in combat - the icon appears
Leave combat - icon disappears

This makes tracking cooldowns on those abilities difficult since you have to be in combat for them to show, constantly expanding/collapsing dynamic groups.

Would request an option to load based on saved spec loadout, if that's possible. You can select to load in certain zones/instances but I do not see options for Arenas/BGs - it's all PvE zones.
