### ISSUE TITLE
When anchoring weakauras associated with trinkets to the Plater Personal resource display, cause everything else anchored to the Plater personal resource display to bug out

### ISSUE THREAD

**Issue by JR61010** [WeakAuras/WeakAuras2#4182]
### Description

I expected for the weakaura to work like normal, but ended up bugging everything out. It works like normal when not anchored to the player PRD, but when anchored bugs everything associated with plater PRD out. When switching back to the normal blizzard PRD it works fine.

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Make icon weakaura with Trigger 1 type as “item”
2. Make the second option “Cooldown Progress”
3. Anchor this weak aura to the Plater Personal resource display
4. Watch everything else associated with the Plater PRD including trinket weakaura to bug out and not work properly ONLY when entering combat

### Screenshots

![5A22E302-CEAA-4F3B-9A7F-292BA89192CC](https://user-images.githubusercontent.com/121605280/209983608-289af1a9-6905-4c91-9168-e45f3a36a155.jpeg)

**Comment by SpatenLa** [comment]
can you share that aura directly? makes it easier

**Comment by InfusOnWoW** [comment]
Nope, that's the same person that insulted me at: https://github.com/WeakAuras/WeakAuras2/issues/4180#issuecomment-1367186379

I'm not interested in helping them. Also clearly the "Tested with only WeakAuras" response is wrong since it apparently requires Plater.

The "No responses" to Lua Errors is also very much questionable.

Being rude sometimes has unfortunate consuquences, and JR61010 will have to find someone else to care about their problem.
