### ISSUE TITLE
Allow non-progress texture cropping

### ISSUE THREAD

**Issue by VinterJo** [WeakAuras/WeakAuras2#4198]
Progress textures are able to be cropped, normal textures however are not. Would it be possible to add that as a feature?

**Comment by InfusOnWoW** [comment]
Technically it would be possible. 

But there are complications because the texture has a setting that affects crops. It's the "Allow full rotate setting." Replacing that with the crop settings from progress textures is possible, though the crop settings from progress textures are pretty ugly. For legacy reasons the scala is rather strange, where 41% is a good value. 

That's not something I would want to copy to Textures, instead that needs cleaning up.

Also together with the closely related "recenter" settings, is a lot of settings.

And for on the other hand I don't see the great benefit of having crop settings for Textures, you don't actually make any case for when you'd use them. Nor have I seen any demand for them in the last years at all.

**Comment by Rycia** [comment]
Actually, there is a pretty large usecase that I myself have just came across and had major issues with.
![image](https://github.com/WeakAuras/WeakAuras2/assets/43384589/0424880c-a984-4ae9-bfbb-0873c932cbe3)
In this image, I'm wanting to use various background images to overlay on top of this panel on the bottom going across the screen. However, I don't want that top area sticking out.
Though this is doable with progress bars, it took me a long time to figure out that it can be done with that.. other method.

I would suggest adding this for conventional textures. There's a lot of background-like files that can be overlayed on top of other elements like this, and it'd present a viable way to use those.
