### ISSUE TITLE
Progress bar Issue

### ISSUE THREAD

**Issue by Sylveria1** [WeakAuras/WeakAuras2#4219]
### Description

#
![WoWScrnShot_010523_185515](https://user-images.githubusercontent.com/122240573/211227077-e0dde852-eded-410b-8731-53e4073e04e5.jpg)

Hey all my progress bars have this weird bit at the end. I feel like I have tried everything to remove it.
Reset all my CVar settings, disabled addons, tried to google for similar issues and I tried reseting nvidia settings.

The only thing that "kinda" worked was changing the scale of the weakaura itself, but then the problem is that the weakaura would have to be huge for the thing to disappear.

### WeakAuras Version

Weakauras 5.3.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

I just made a progress bar and it seems certain sizes make last bar bug out.

### Last Good Version

It was not a thing before dragonflight prepatch.

### Export String

!WA:2!TFvEWTXD1)iVeARAltTATjKWHQGXexsCILTttcnKrRT8rItK6kzNdAr71xPDJxT7MV7kzRekfudLauOG6pokNfXz5gX1pOCumNLZhgk0YnUqpGPaJzMYFwEF)UR8rAlmatNoDM4zI2D)E8((((EVpF(8sKPJ5jnuFd03GXkhtpM(P3HyjQZSQdpvU8zoWIQouDcvurBgDQJR7fjAzEItOq1JN3XXY30vDwLsotmsJC1gZpRQ04LPZLPyrpIFeATWxwYZH6pEnvQPEEfvlYOlLIQPytIpSHcTejEsJZyGbpZbg4mhOFJwbo2Wowo09fjsebjpxfnY6twHA5Ezg((UE7EBBJ5C9z6STjRmNVHJ3bukrgHIJzx0YSKH)2g4YPkA(Mo2E7qYZxH6hvTOPTPNrur8HF06(uZsLiuVn2dn81RVPorTsXI5R5sOJNEYSJo1KI(4hskvOkjR75sSSMq3l6IEvujvj2(5WvBoxRcdNkx(c5YNsk)YtLLsWPKYLn9KtkwbprvxlLAeQeFw1Xjkw(gs2kLjErBuXo0fI2sZXQsz7CSBSWsM2(eQTI10OFIxLtwVIhzsZYM4ovWRPT4KPhnVkvr3SI3PUakEpzgjcTAW63Ft0BKiLyrHOn8iwfZ6GMmz(mzBOyBwwHfF2bCjJoprXJKZNsSl5BCoWMeTDSjlOJ3A2kkWIbupIMJTUxD2szriyiXYkM2JcdIBagc2bC5WoXNDDMJiA5OOpQON5jiDlvUcwAfvedLADdxrujnlfpp2BQ(kwyGH9AdfQ2KCx5uDVGAy9zq5GGGqwHT33q1lXk5qViHeM15xfIrtTkE(oLhdRXDVJIvS5P)nBtMnRJNjVuylXz1evjHXKEJgh)ZYrtXk(Khkv89W)vXwN98fNGvtL4QJ7qJFYRHVs(pMfx9Q6JDAJudZJMAsepNkunsCFdInFTS)Emw0)E)IyRhf)NKh6EeHMAewXa)opPKAagXOzWZ06LiUDM74vuOK4JwXYk(Hmm9jnPC7X2Z86bhpsauXnCx5WmY6fzqyyivm5w0Suu1aVt1SSloEiuCcBeSl0QifRwXQefFLZzrC9y5MT)OON7qvLsnYetLRoEpdkDNpyNb8eNNQhPmwtQoqFBVV(3vtFhTWk0ne56BMWu3DJRLeyR8q8wJZYanyP6dzQ7BC(lPyRz4qhL5hSlLAUHLsN(GswmiXfMSIPElYrVCRP3fT)E3fDbLkiZanJlpehTvWM5ia1HtFW8PLAwedvdBs1SiYnzv3MHl10UOdnaE0Dl8vnsAgQ1tgVG(8HJetBFNwSUdEpqyT3gzevJV37(MV5BFDRBNnnrJLJhiFMRduJcNxeqd0xa5XOZi12cqNqSLyL3SCIT(Y8DJV37C(B8AF4h(b5MPGw7cFHfj2ms2Xy4D0BmG(HK1vvczkhFV3ZnDt3Y6wxhJV376Whg3))qqaj08u8zWyIX88tpiHCKiUxCPqZKHY(L7snhpJ0ehnZbZNAsy3p0ciztbxIVQIVVfXOb7tBK9IAa7LbtPNajjq6WoGxupQEM2LSiIhi1yPHROB10tNz)PLKDJX2ehJxabmfyWE5fzJX5sNX2zwB5glVgzrQJfHzB(zxLyyIPMPmnQhUfnzyp9aZjaxXULLLxCTgUByURP5k29CR(3HxiZwl6v2XX3il1PeL45z4ErO1sPFmKSGOt0pGPTmSFkJIhJLTcZOAwMUYuFYCy0JiLZXYupiaMpyi3npbdoweR1VQHv88XRVOc9QMAITUYxBnhBdIyzOJmCuwPoYA7AOi0KBPLz0qSn71CysG0XQtthoc8uHZjKwJDWD425AQHoGJorm1u5Zap9d2dSHtFXnyxJarfekANX2QM888GNHZSd745ldXHlTHRZSekJv)sdsYT)ugEgWgrU7ebjofKnGYLQyhKm8SHNd88KYYwT7LWwaLC8kMucFegG0a6jk8SIsX5oi6ebP6aRWTappYedLxarxAgeVCOFLXUjZ9sznlIKGeWZfE(rBPB6DmofEvssf7AUDgWqMpqNKznHwbCwJXO0MxZPSQdEtq0Thmatu7mfM21P7sLhOLeAYDEwqKyOY5xNtObp3WPvcc4bloLqWZXcxWOOt1bVKL)Pb)iqZhyMAcWnePEBHZoIvlsS5I0m4KyMUUhsFY6prnySt1n6LHZZSS7Hym)lRD5gwZUL48wy2sCDILVsVHAlucwjAhmv8xq8LxD8lB1RJjJepEWLquGhnEes0UDA6LLIQO0AT1NmGTTFy77RBytlGnrScnv4aiPijyGQleq1xWjONW2Fgq3MeXuWMAWmbF4qDHqwnKTlsyFOfQA6zISBTB)Rab10G91(lw3dR)ExOKLZSJYQ6i2A1Y(u2EFjhc2efToBcwH(ywS6C02g1zdXI5sznNJyX3AEKqzgBmej0I95rcBJTrP27Idh5ZD4vpxoUeSi7vd(SH3o42AY(kOzLU4lDst0(DYhwmqJw1GWY49Uih6kID5OZkFtMAKrotQiL5KHSWvcYT8o2yswwfDo6UOnAtXNe9UicqMOOIj80AWvh8m1jsstm245div4cLD1sj0MOfJ1Fl(mJZ9I9SYuM2X2(sTfWcP12iCAO3tchgoIiZ8gHB1uxNylDW0tNws8eooLJa5eGRgEjWfJaTUBO7uiaYyaDff6Uh4wD3kJiQaXUAFb9G03QWQyFwju469f0469jGFVS0Smp)6OM2Swdigs8t2OLZkYtGpu8Y6rcPn0MzuydcjCCtSN9ivvXQcj2G1RQqnz6JsC6mkAA7seS9E4(7gDOJ(iDO2CUm)H1jqIOhIOmtkCDE9HzC7an)nNa7fPWuzhjv(0fetjLaBwl0uBjE)Bj(G9whbEUmc0qMAnm7Ud4(qczu9)bAQW518PviQwM2Zq0LH)CBVA6)1E1)TEe8GWFbk1dyi7Ub8)MaIvd7cIBG0uQd1tgo3iNweo2ABDbMz1DSaw8UuGYRPVeWMdtahEhiG7JARhWXnaAeWdtA7(HGkgq1W2gGzznmaZb1WgfGtidNugEPYW1idVm(0xRb8YxJmp8kyk7q9Lf0HRZaofQzdVs46LHxfwY(QHxd8Ad1yHBqaEDbo4RVd4g5sOWBOd4ncnARsc3uu4)tgEtCXq4nFPWBzzHp4TgkZb3m82cLZG3Um8oKH3Pm8UG3DO(eClW7bAkaVx499yQ2aVFb4dyaFqb4db3k8HfGpIa8r7a(ylRzaFCMCb8jc1jGpj8PGwCjb4tdFg4Z(yWwdFUviNHpp7N))QWxic8fHBdF)lbFzoVk8vmGVkSp42x)9cFT2uLW8Wx3a(gW3e(wcW3oc8Dccu3re47kaFpd47JM4h0f8d7e(rga0l8JHfGFsBoPntZVZnlTtPAUda35Q5IoF4Nb)C4U6cU7yjHFXEGFzS(HF1kujWV2a(nWVf(DRH2iABUcyre(d3Z1b)bd4pAa3BamhUVvG4W9hBq4bG)0k4MhFqZjBJDwb9c)v4V94kEn5AXRWsNfxEwC5)z4sZdK94jNsCWms1wlU8cxbxoqaUm5tkXLd8eaUCGZIlplU8)nC5vAmn5iE7xPC(PxlU8cwbxoyaUCGNuIlh8jaC5GpA4Yyv)Ph(F(d

**Comment by InfusOnWoW** [comment]
We need a lot more information, such as:
* Your settings
* Your resolution
* Your ui scale

**Comment by Sylveria1** [comment]
So not sure which settings you need to know but my resolution is 3840x1080 and my ingame ui scale is set to 80%

**Comment by InfusOnWoW** [comment]
Your WeakAuras settings

**Comment by InfusOnWoW** [comment]
No response from reporter.

**Comment by Verzhul** [comment]
Hi InfusOnWow,

Hope it's okay to write here since I have exactly the same issues with every progress bar. The triangle in progress bars only appears on the right side of the screen and seems to disappear on specific sizings when I switch to windowed mode and change the window size manually.

**WeakAuras Version**

Weakauras 5.3.7

**World of Warcraft Flavor**

Retail (Default)

**Tested with only WeakAuras**

 Yes

**Lua Error**

None

**Reproduction Steps**

1. Make a progress bar for any cooldown (used Fel Devastation, width 200)
2. Move it to the right side of the screen (triangle appears when moving from offset X = 199 to X = 200; depends on the width of the progress bar)

**Last Good Version**

None

**Settings**

Resolution: 5120 x 1440
UI Scale: 0.53

Don't exactly know what you mean with WeakAura Settings. Are there any general settings for the addon? Please let me know if you need more details.

**Export String**

!WA:2!1vv3UnXru4SYsPcRsfeArejuRlQubxqekuGsl0IxJnjuJDY6n8NOD94Dg7DkRNz0mZMeN7iQTIR9JGL6D9k)euLNGrw9jix0hG8e0Zm7sCbr2lSpZzpZzoFFN57SEnwA4s4LWVz1jkbs(QNsX6Kp7aND7(9ve9Z8K7MBT29t6U4cWJC0BDS1FFkRJPiwCcxUbNY09QvVvy9GzUueW1inLZ8eN9Dw)yoM4xDRW2h1df)QbsEgdxJNYLpYZZBJsxFLBUVwshmGivFYxllm)xF9ibjqjiPPhQY6r2MW0DY63NU70OAv7eg1jSAq4emPh4meIvUw9MB0yRMIZMPirdimIKg3jHVtBw3zVZYjk4VQP7GgPcyOHev5zsckTJ9SAbRpQbjTYdiBJu5ayMnHQ3(2U77mxhRk7NXO6EIu0iImWvHILRX5Py(oSkBi5dKeLQYvCj(QhJInKeafbD2OEZMJTPwlbEP74JpHlu6U6XzScMOS4SOynDBsy(AlD(xlmHgZzrXoASe8Ce0nisgk9janc18RhRiP9DnjZI73djZz8sEELaotH0zsKMKeGsfjOs))7ap3BcuPbKbqwup68MtpdwoVZv4OpxsYD8MLfFPMSRoY9d4FishjI00HKiHKetTLtPXhhYLUSqu5K2WqooYwyDp09Y5y4uIZ58GY0CiEAS7YRFvy5r55HUlb7C(AXxDsPpLmafpkQFkNltoWfWVMP00(JmlorAVVscbN(TA3Q(SI9Z02Bx(T4mI50sa6w)ZYfbplNY8M4IDE3y8X7vCMgs6Ev2mdHbCHQegkwkhAji4Asrck9ooFEUZlUGy5paqYncS4bNxJ7WL4NkrI9FAHroY2gy(EPKUIZKZCZLTtwVvR6brnR3iu85NexLVYRy35v2XY2sZzNo09illU6jLg8iqIrJJ0jGyib0gJk4Ucu69Mp1uTK56x6YmZp5sTzvZPm3W8nMB(AtlpZTnlA(wZDmN2CxZp4yxZpAUVX)IlyQBAyEyxZAtZXtW6pCTqZ3z(EtZLn3Z7dWEScdFg0n7LqOds0FHFkhHB0tJsbX55dgMLQPL9b1y85nBvoiofPuwlFfGuRXHo1Ipeo2kgxT6dEG4mGqUk2EzIGj4hJ2nzmIrh6MFCRayqIu34acsr6OLe2aDYhbaAZzyRmecjYoTtQiGOgR23gN9sNzt)HikRH5xCrBImDniZM96tzuvY77EkLLJoiFLpKWqqZ)HseMcWkX3oVi59ltklzI0P0Dtqrq1aJkK25nG4)wMFUSjUSpCA6YUboD4zYyYfxySB6JIIjbosF1mkEAWlc0BDN9U(J7XNbYuOf3w4Yt5PocBnhDFpPTHKjj77Ns3BpKehSJv1(BFC(qOW83kUY62bA9rXKxwdgetzd8rYxU16xB(QR1X9zg32sMO5XBNp77cE)XFwCKumMWcAv)j1d83JZh6nTVeMWcnbqmw6O8BInSUSeqVo1cQxV1LO4dk(eqLqIs3daBF6GYskZEcKK8pFw7y5(uU0sYoMFYATdw)fTBfwT5eB3KMtbJF7i4vHD4vsCUbfDM2Z3Q53xsfCZvUXk3EPT)NN9Fp

**Comment by InfusOnWoW** [comment]
@Verzhul can you try reproducing that while setting a lower resolution. My monitor can't handle a 5120x1440?

I'll try to see if it reproduces with the closest I can manage, but I very much expect this to be very dependendant on exact settings.

**Comment by Verzhul** [comment]
![WoWScrnShot_013023_124029](https://user-images.githubusercontent.com/123829362/215467863-4bd934a0-be1b-409f-9c8e-87e03a39a0d3.jpg)

@InfusOnWoW 

This shows the issue with 3840x1080 which is the only resolution I can choose with fullscreen (windowed) enabled. Everything else will force wow into a window that also changes the resolution afterwards.

As you can see this also 'breaks' the UI scale and the pixel perfect borders of everything esle so I don't know if that's comparable.

But I found out that when, for example, I switch to 2560x1440 the resolution will be set to 2480x1395 in windowed mode and the issue disappears.
This is true for nearly all other resolutions, too.

![WoWScrnShot_013023_125036](https://user-images.githubusercontent.com/123829362/215469419-5aef4ece-66fc-465d-a2a1-5230115e7256.jpg)

Btw. thanks for your support! Really appreciated!

**Comment by grantfang** [comment]
![image](https://user-images.githubusercontent.com/26598394/217319239-365d1c99-b8d1-42a0-a0b2-8892f555e579.png)

I have the exact same issue with every class' resources bar from both Luxthos UI (https://wago.io/p/Luxthos) and Afenar UI(https://wago.io/p/Afenar).

So I contacted Luxthos and he replied that this is a pixel issue and caused by rendering. He suggested this may happen for some people with higher resolution or like me using wide screen(personally playing at 5120 * 1440).

Like others above suggested there is a work around by adjusting the scale of particular weakaura, but that will make the weakaura ridiculesly large.

**Comment by Verzhul** [comment]
Hi @grantfang,

Thanks for the info!

Do you know of any possible workarounds which don't involve changiing the scaling of the weakauras to guarantee pixel perfect borders? 
Maybe some graphic card options or anything like that?

Additionally, one of my mates is using the exact same monitor as I do and we both play at 5120 * 1440, too, but he doesn't have these issues at all.

Cheers!

**Comment by nosolacez** [comment]
Hi all,

Can confirm, this is happening on my monitor as well at 5120x1440. This appears to only happen when the auras are on the right side of my monitor.

**Comment by grantfang** [comment]
> 
Hi @Verzhul 
Unfortunately I don't know any other work around, I asked Luxthos for the same question and he doesn't as well, so I don't believe there is one atm.

Regarding your friend, It maybe due to different graphic cards or rending method I guess?

Cheers
