### ISSUE TITLE
Change of aura, does not remember the tabs

### ISSUE THREAD

**Issue by Machou** [WeakAuras/WeakAuras2#4292]
### Description

Hello,

In the old version, when I changed aura, the tabs stayed on the same position, if trigger 2 was open on aura 1, when I switched to aura 2, well it was open too. Now it resets, which is a bit annoying.

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Simply switch Aura

### Last Good Version

4.1.5

### Screenshots

https://i.ibb.co/9tCGK77/Sans-titre-2-min.jpg

**Comment by InfusOnWoW** [comment]
That was an intentional change in https://github.com/WeakAuras/WeakAuras2/commit/029a88566d101aa01facbdd371b106c52e04ca80. The issue there was that for an unrelated aura, e.g. after importing having random triggers being expanded was not helpful. Thus the expanded state is now cleared on chaning the selection.
