### ISSUE TITLE
unzip failure

### ISSUE THREAD

**Issue by YMCYC** [WeakAuras/WeakAuras2#4320]
### Description

I import String from wago io but it says unzip failure 
It is already the latest version,I don't know what happen

### WeakAuras Version

WeakAuras 5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

just import String and it die

### Screenshots

<img width="648" alt="微信截图_20230218112932" src="https://user-images.githubusercontent.com/63227165/219829366-5ee189ca-6f8b-48f0-ae5d-6ed7336e61d7.png">

**Comment by InfusOnWoW** [comment]
Decoding Errors are usually caused by:
1. You have some malware that is changing the string, usually changing what looks like a bitcoin address to a different address.
2. A browser extension that changes site content, we've seen a currency exchange extension change something like 12USD to 10EUR within a string, kind of thing.
3. Trying to import an ElvUI string into WeakAuras will never work.
4. Trying to import strings for private servers is not supported.

To find out if your import string is being altered, get into https://mrbuds.github.io/wa-antivirus/ and follow the instructions.
