### ISSUE TITLE
Dynamic Group: custom anchor does not update on trigger update

### ISSUE THREAD

**Issue by sense-amid-madness** [WeakAuras/WeakAuras2#4338]
### Description

I have a dynamic group with a simple custom anchor for testing,

`
function()
    return C_NamePlate.GetNamePlateForUnit("target")
end
`

I have also two triggers, one for "player is casting" and one for "target is attackable", and show an icon at the target whenever one of these is true.

According to documentation on Wiki, "the custom anchor function is updated on trigger update and should return a frame".

The anchor works in principle. When I click the "set parent to anchor" checkbox in the position settings, WA automatically makes an update of the anchor and it changes to my current target. However, when I select a new target and cast a spell, the anchor is not updated to the new target, the icon stays at whatever target was selected when I clicked the checkbox.

Did I do anything wrong or misunderstood the documentation, or is this a bug? How can I trigger an automatic update in the aura? Thanks.

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
No error.
```

### Reproduction Steps

1. Create dynamic group
2. Set custom anchor as above
3. Add triggers as above
4. Add something to display
5. No updates to anchor position ever occur except when checkbox "set parent to anchor" is clicked

### Last Good Version

No idea

### Export String

```true
!WA:2!fwv3UnXru4UyOKUqPednecTf3qlfuvtb3cvi1lQxhBsqojURDsOsrkE2DM17aRNDyMzZpOEdriex7hGEHLAVQx5hH8emYQpb5ripb9m7UjoKIu9f7UZ4ZpFNZ5B(gR1kkDFWC)WC)uXEfXfXV9(9rc)gewxv4RN6aVybMiCq(phlI58l7erF5lrcCP2XXrkkFekrfglwHROXmPTy3vccKeL1qeZh2VzmLP8QwB521ChMfRQXrXINyzzvWvYr(KZjq(Po)qxPcju2ougvz7faVKH27Pe0UDjc5m3wK)5BgGjEjbbT3LteluRrZ6R2WrblCrjcu59KCsu0IyP9bYepYweMQfynDNHBwTsR2B2QDf32ojqs84rODjIJnRPGaM52QzTgnCt3XBbcksf6Yq9is7(jSCiyp0pokPhRLPck4jqyAI81xSpIr7HmvZd1xSU(koSygzFcssAPePT0Zpcdy0yXMgelKe)ygwUNXgt9OVLtpeLb(QVL(RoV(R13w)nWNx6074IIODz6jeqtZGiRbqv4s6MogCJO9OQl4efJW1DK0xsMYTxcmVSDGMJ)u6V321pcjLMV8uOiOunFoYlFqNnKkuOqZc3BUhmiijkQkv4hr6iYkrs4EjssdtAcDL(qekmWhIcryQIzB46LnTdhK9UgUlHpzRxKGeKs1HWvA9qQImqKIyJp7J3f6Yu)UI4eEUxTaKFohzSqPVLyNCQ1((jsvCVkPem(8bjSu(ZDURDj4NGOseSsv3CzyK1mcq6CpMOoEr9yXQWK)oZcuTUe1S31MWW27jIvPdfl(Kze36cJhayzQWdGre0LzQ6atnw45wz(fxTvoDErgGPc7NTidHF0EDfuCAFWD(bQy)TG5me8PTEZFolfZl2on3LYQGsTjsvFJhRtXQWlmmWKAGVGuOchEc0ycOx1vB1ELLa8UDo1dWwaTRD5ekEi1N8IvrLRuE71DG242oZVY6lFi1mvyOO1YqXRgyyC0SZRdPSGyrgL1UVKefKEITC7vAw0FM3Ep9VyP)ql951tWVkMirkd5LyKdmJjgoC0XmEd8acxmFO0awYoGTKo7NEMUjryihwh6DSNzmSu61PEWVA2aggvKmBDJ3w(L9t7lUq6VPETxP)nasZCAdRtJilqODdvwhfLXynnk8R)(8jTZBP)2zMsFLrW5OXW0lmnCNDc(n(poAWtE20FxD9CMtq67L(8(PplBEYNCC0Y7k8FCrZmjagGBubJxHj3yDc65vGMRCJLiykAJClLBa5K3l20G5x70vu1uniOOMm4yuL7O(zNmV59)cE9OcrSiu)edxu)Zdgh9bKXMDYz946nuFbqvZw)X26lzFeyg)3hbg9N8h3wF53EL(gX4uDZz4xUIWhXiLmLDueXxXNeup2SlHreu)wHXBVcRZO3z5bY0xvHRzWXBZmQnBA0S7ONuxe0cNMx0SfYduhsvPxkgt6ONsFnbSV58Eh9N5ufjvhm2UuBgjaRBzUJWyL1iZFlpAzh9NARNwFD9m6B0)4DT6Bmcos6)8o6VWwFtBOe)ldk07c58m6Fhsg)QgLLsvdrMB0GkrQO(s9oD0t7LP2ON5mzGrPGiH8a500Q5M2dXu5ZsfY2IugX2LxmR92o76MgXDP(8p)DK6Yf6uIesQggOCL6EUlMs9V)a(uVxwR0s)R26L9Av1TwTLFpNJmgLDO4OimM1LhbqjZzrqk5Gqk(ekcD0lvWDBJRNDc95S1Ud35XEpATk4fE0YnfuMrlKe2hQDg2GrxNg1wE(ddojpk7QNc61T1p1wpB2DPV79H35))gYIB9pp9F)d
```

**Comment by mrbuds** [comment]
Old custom trigger doesn't seem to update anchor, while TSU does

doesn't update:
```
!WA:2!1vvWUTTrqul4dgGOOiriqOXThiubAJrdmA8H0t(GOJKTBvSDPOQJrrb9sUdf3eQDj2DPIKpQwuKZ(tqa9woPpH8fqy0Va)jKVGo7sjz7uhciQzND2zEZmVzzTo1hwNwN(UVxkk0zmoipUFq3dpQ9vKcDQqECUMj4kN8FGYu5zKjbWyDyIqoKOdZd1SHqiDcNmKfhQtLGkvKrNiNCCsIc01Mt4XOxorW4AVUT7eK7(59t1QA5piUqPfdnw0pNs0Gpmc46RrejqdyXNYO6uVw4sjj2IVN7R0eP2XJXz6gxsfHv(inkb1OsDMQLSbdaP6OVtUq8D1VUqbHf4jykZ7u7AsKsiJEPGcN7J5fOCMrHOIKKGj5G8G2DpPt)UEACruvmYRFZXoaiz2JoVAVqRDi20fQPlJ25Lo5pQpk4UxkXKbGKPW0sDTQiYMQ9WWXgppCVw9cc7f0YpOsVk)rN0T1zT9d7C8E97fU3bToA)2VWZ4v)ebgZPQCil7qkI6BsSitbhK(XPq8BkDwfMtKagg)EN0UB3YnhxRrsb3wpFYwoU4dlXLl0UgO2Emcr1tAAdsZTC1Pa3vc6cj3nHKPaxGtThIuijHaF02mofg7URlNLz3aBVUmC9ZEQ7Z(rxQWQ08KjIjzUgGI72msOun3EB2QTruyqWHkZ7Li4Pw7RWXklV3WZUZ2lGSwwaR0Ve5l))2PLdQCzVmLrHYnVSGVGa5mh5YV2wYgb7q4tYFiXkhuTVHi8(1Y)67LXxj4Bi(0pIthGKtY(nKGIL))8sfKLyhA89pC)dc8seCD(d6izx4(RfeQKOjUbbZWgPpmWmaSzJYhFfUmIe)Mb4SmN6Lji0oEk2fqd)HfzAMJhsoIBuURJFCgrPmsrAsgYemItnbPhA(UivUqgdrSH5cP(kvkHkE7RQgPx)dvvJw2b7X1C()CMpTfyPa3HXSSs7Ct7xvKGnRW9)9M963bhJOG0Wem9CVcTwWroXDD8FSmEMJEBVBwFprikJDXfejDry8Q4z31NBVDZaICaO7iXr)MRcXQZE74SsPjy4VzsBVWCpHNgB25F7N)UUCjeZm961xuEpRQ8(nRndhjbQ9kU)6lKJRu)(1KVgl7SKjLBmtlIhvru(QA)9)0KrZB0Xmu4AsPedWD7cAKrn)wXVEN52T6PnKN1)y1fZ200a4i86KGJFPFSiti)51XNDky05EB9lN9t8D6cbhgfl4jSbotFRqspvsYNE6cH5vzWE2JwRwT1NHMszvF4yoJxL54QgZrXyOT9QSZVKWzv6FE5x2P8XECbh(aqugmc8b60nUIIDhJf27rLkW4y1uJngqxg6nKW44zldlpFJsszuzmk(WpvtD1oVagvF0)(Q)l
```
update:
```
!WA:2!1vvZUTTrq4O6dbGOOirOWOjThiubAtqduBDbspLciQqzRwfzxkQ8dccOxYDO4MqTlXUlvKCrVOwuKZ(rWa9woPhH8eqy0Na)iKNGolPKSLJdbK4SZSZ3mZUZ3WADQpUoTo9nFRuKRtzCqU)q)ED77EkjxNiK7NPzcUYk77OmvwkzMpmvhelKJj6GSanBmeqNXjJzrb6ejOseP0zYz7hhRaDTfeEeIYbcgx70ZTJFM9hhNQv1YUruUslgB2XWmkrdEWeGRpdZibUbw0tyuDItlCPKevMF33tPjsTLdJZ0BFmveuHrsymQrLynxlzJgbsv)VrUu8n1plxbb5OhmL5)KY1KqLqg(ibfo0dRlqzDcfcZJJ9NLbY9C7DqNH9C04IWQyKv)C32diPLUUOYwGzFlWCtd5LLY8vH8WcRSpFiky3oHykdqYuyTPotLhwwVdWyYMUiODRb(bd8B55xC7PFY3hNZlR57qURLn(KkIiP2mofMA)aBol1OS0cl22ea3PiWQ70iwG5uJ7ARtaEPDZdEMBZq)(X7z)J)GnvS2W5qBYwChncfkvJMnzBSLLXORY8)QyCVsFUuKw7XYmL9bwcLa5vBOf4uRllV6ng5kO2ikKN3OXlq0)JnWb7kFnQulZH7THHOecFeqVsBRtuZ71w(Z1ssqNl5LowLyPkWAZJof6EzgzDHZl1hEUOAUmdJjxeKktBMJBy8YPWLpNWFoMRcVY7L5QminTlf7OpVPp0qgbPxuce9QcR1DFhibS7ZBWbU96vPrL9th0R1ZC9c6SF7HdcAVxR(76(q7U9XMZ(TDdC73E)H99Xn42F3w76gmSFx)veHegfkU9X58LSpRf4GGxw2lpb2HWNLDtsPSFLDdl6Txl7lVYXfvcEMPg03JJwajNK(yKDJ8I)6yfKgxoXXZR7U757el46SB0rYoY(3ZjujrtS99pbRupyKz6XT3U4wNIldjrVAeoiep1sfe6Jp2qw5yXltc1Ku8myBVX5PAMLxukrP2U4xSCWd1Okb2rGryUjEdWfpahjKlJGq24mHuFQkHqfV(PvJg36DvhmTkhqoTMCnV(QO1KCjja4tAwokP55TKRzbpOI7BATw1wSQt4c4PYJr0c295ngmSdoSIcsdT2qEDY1Ab3qWn49IvOB84IGAwFfadPtYzlH2nDYWoboiUbM5H4OAI8dWTYHns3snxb2HPSJoIiPlH3z5CidCnB2WNihb6osCuDJ1OV2LlgG1kxsnorwE9BMR7OX(RSV(J)TPmjeXmTxBT8A8zvxJF11obPjaT8ts)9NkNwP(Txt(s86LfpR46NOfrtQ6n)IA)Z)2GrZ2UJHpABQKytIB3d0yt8Ile)6DwuAAG20VU17R(qAzzAs4qKb6V)J8IePc5VUf(egj4XSrw7KZOlCU7V9SFMVtpWV78xlK0NijzZFYsHfvvq7sxRvR2wNGUszvFOFbJxv54QTxGIrGBj7)WJjCwL(7x8zDkULdxWH3beLjhb(iDY1pLI9PMDu(DpPcmaRMB2JjPlo0zmHXrFloSGC9IWIOckkEZlRPUANhctQp5)E6)p
```

**Comment by sense-amid-madness** [comment]
Great, thanks for looking into it and for providing a working example.

**Comment by InfusOnWoW** [comment]
The wiki is talking about the custom anchor function of an aura. A dynamic group does not have triggers, so what you quote does not apply to the dynamic group's custom anchoring function.

What you instead want to do is to use a custom grow function, since those are rerun whenever a state changes, e.g. like this aura:
!WA:2!fA1BVTrrAC2A4k3Y9Ne3qAjqv3gjYvO56vfvkhiXHSDStdNtIV1ouoAofp7oJ9oK1Zm3mZgN0t8MiavXl9haEHLGxXR8hH(jyKfFcYhH8jGNzwh70CvIOKD3z3N))8753t8(8IQ1wNCyXEfXfXp7dl3vY7hvz3MT2zRtJ4smrwgfFawYfI5kNsF6trsCqlopvtfJrz6eUChHMYzkF5X70PJIO9otXL6hDCKKIBHIsjlgTzmNfSwI4AXzknVxjwmOxdICxgvFLHDYstRqLXPK2I5YuKx4ZjsuSZ(pmuPrsTFzk8w)OoWnvI)jAjTBxIuT0kYjp(DdXKOSoDADSGiFu16nQTB9YA4qiktIw7eLGKMUjw5FQklICiHPBcstpA0(vk1S1(nBvkSv5mWjrIu0Xezid1JO8dDIg9ickvNmv1gscOAyZgvRxFqgBsi4pkMNM1J1uGIjfIKimnt9n)HqL98Rnqrs70GtbRvP62TQggIsPDzMvISv)DyY4eeRlbpaXO9q2K)HM)unZBwMXzKNtqkstTKW6QtU6ymKswj23MGsfbk0y1jwzSPV5UL7HOmqxZDnREvZF1CpZFdECUl)gjuBTbU3qiXcjDDn0r5aGk8uU8Z888kmcL3zSHUzLYPCeUwzf9PKfd7Lbic)YqTnErZh6hgNIuk7trAukuNSpoXEBYaqsHXrtWv5MVqHcnkC)79bLTyhZDJu8mzmjI2taNhMdB2aQoh59x6KXCiI7Wi9BWvuh6y1alm5qYKy)98dGFs5XO0aa10LO3UrWNeuz)THEzJuKMCVnG3D(HAChw7olNl7Y5Qt7eW46z6Rtim3hS)ij6mz(rcd7U7UCXG6jNR6)b89)7RDFVdxgqxfu3gNbu4xbIkv35fd)amFQNE5w8j5wWz5G7VAW9)6PXI9pF)qfK8KcdJHQprArdlxpmkVfKmm)EvCxIy(M)3mKKeudgddECcvtgMBBRophFma)PXaYmtmrRMqh)1gJU4uQPWaKmUUdu(nloOlm6)ykwN8gHP0Eu9BiMpx8AsBjh8gt3(uaRcWoMUgK7CzuyP13C3MRLrXJ2D9Q72Fl9DQEWbpp3N5ul)(tKCTdV7nuZJpeq8WZ3W77(XLPyrXwUItqo)rqlIsdY3pFiCuhRRHbhKgv4Slen2SmQzLWQv3wE0egSii06q76FInrCLUW1L5tJKKZO2ckdL(55U)BhAh6Y7p(JOmOdNp16FcqMv3M)jfJx6zpW8epZv9od(oXwoz4Pq)cIfWefsBhMjwc38VNmEkdGniGboUyKYgZKJazjTFUJse6b2MSN5pc8e(M)SVzoFXc5Zm1M6SqEF1Th4QcHGxULz)V9uHK3vsuQMUPT3)DELRyExZkILUSU1OPKhrODt0ENB4zrPZWI36LPJdd4zwBPfnV5yGzjAQsrjoZ9QVU4T))u0gIt8M5dQzEOL7W83Dx)i31p2DD(FyftXNDTbwwDhf9sI5kjJrmsWMqhknLeRpf6a7Ja2ez0wCmP94UegrsJBMyjApv5UvbwNH59z221(wI)2MRzwqcNSeeTffNzel7VZqMByElZsM32CZYvqkTyERmVGXBpwcc30USXAgVXwjuNFST56(ah8sMBzcgm9TEdScby04dABEhFZT9Hu8NCYDm4YRyGq7MIfStCbvsq2vJGdvAASY0VTzPOC6bZTUsEIR1GLSRGDzeyUryQ6RC8NhswdXowumV63kFVvDExAS4MtzyT8G5eDbAzgXXSaJYo1NOITA8ZVs(EB8xbgJGj4TqhLiMFw3EcEv8aBJr2bMh3RegVdtT3JjOdkbnq1EBrWu0EtKuThevIECBuy(hMpvm)SPMjIy((l6HjZafmpawJ2JkLCzYLdkklXSXWzgwS4lf6P8gsMzWZM5J8Xv3AQlDrC9lBPkU9)QBB2Z38(5RVFXvW3)3EPS5FB(YttO4lWi0(LmBAJ58bTZtOzYpjHa2XY2)hmZUwUsZxuiSVvHx91n)oFZ)AK8Fw6l3Oo9ynntszwwvsYaa1WW2UBy56v3E9ZtXYxSCKNIT9ni)lYGnl4skE4V8f)6
