### ISSUE TITLE
WAs go missing after recent update.

### ISSUE THREAD

**Issue by erock209** [WeakAuras/WeakAuras2#4376]
### Description

After updating my WA addons, all my prior installed WA have gone missing. I trouble shot with some friends but couldn't locate my old WAs in the folders. I ended up redownloading/ creating new WAs and getting them similar to what and where they used to be. They seemed to save for a day and upon logging into WoW Wotlk again, they are missing. 

### WeakAuras Version

Weak Aura 5.4.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
Not the issue.
```

### Reproduction Steps

I installed all my WAs again and it worked for a day or so, and after logging back on they are all missing again.

### Last Good Version

Yes, the one prior to 5.4.3

**Comment by InfusOnWoW** [comment]
This might be due to having a lua error, see this message from our discord:
If you are having errors we need a copy of the entire error's text to be able to help.
See this message for details on getting detailed Lua errors:
https://discordapp.com/channels/172440238717665280/413380679410384896/722189624579194973

Or the game just didn't store your settings correctly on logout. That can happen due to varierty of reasons, e.g. permission problems, harddrive full. Addons have zero control over how the game stores the settings.
