### ISSUE TITLE
range check trigger + conditions + test on range = broken

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#439]
**Describe the bug**
Someone asked for help with a rangecheck trigger

with a range check trigger
use condition on distance '<=' 40 => color in blue
and another condition on distance '>=' 41 => color in red

results are not what is expected 
=> never turn blue
=> red from 0 to 40y

**Do you have an error log of what happened?**
no Lua error

**Expected behavior**
icon blue if <=40y
icon red if >= 41y

**Which version of WeakAuras are you using?**
tested on 8.0 from github, and live master/git

**To Reproduce**
dWJ6eaGArI61ik2NijZuKuhMIzlL)sOUPurptu1TLQopHStjTx1UjA)Ie8trbddfnoeLonQgQiLgSiHgov5GOaNsuOJrW5efzHOqlvuulMsSCKwKOupfSmkPNlXePuutLKjlIPdDrrQABuQ6YcxNuBuKkBLsr2SOY2PQ(gLspgL(mcFxQW8qu10qKrlvA8OGoPirUfLcxtuY9Ou5HiQmkrk(nvEHvd9djdjRgmSi3puuobrq70LexTHaZbUedQ00SPGw4o518diLtqe0vdOiVyOGguxg0LqSP1HrubP6ygh0YWpK4GrJUbDjeBSuCulD6sIzCi8djoqoNmHJCNSmOlHyTKJZ4qPRRJmihkDDDKbjdyrUFmo0CMKvdCjb1P9wn0RBiF144aAAHexn0RBiF144qcpxooRUHIwn0RBiF144a11Ivd96gYxnoo457HMwiXvd96gYxnooKZWICNC1qVUH8vJJdudBSAOx3q(QXXb00cjAD1qVUH8vJJJd8KHA0XagmefsV0yPfjBzG1jt4i3jlRUkSAGTBWsMvdiLtqe0Rcd(gk3yPfduJKig8nnDmqI5GZBG82noW21ijIYQRcRg8nnDS6QWPZwM2tIKTmzYmVTcKLK1SoNnYY(RwVY8A(RcxjDvyCWJ68ckkAG11C0XRwxn4BA6y1aRUGU(bpkxIPjBYBhjMzNXXbpQZlOOObwDbD9SUKyCC8Q1vdSDdwYSAaPCcIGEvyW3q5glTyGAKeXGVPPJbscdoVHuz34aBxJKikRUkSAW300XQRcxfUA9kZR5pDKvitKSLSzzLjP8c5ZBB(ZzJSS)kPRcJdEuNxqrrdSUMJoE16QbFtthRgy1f01p4r5smnzNk7ijKDghh8OoVGIIgy1f01Z6sIXXXXbPUxr5eebTC16ani4oPsKxmWzDYHeEjL1swK7hdgPObJgDBzWKKWrUtAAIrkNGiOLvxfwnGuobrqxnGI8IHcAqDzqld)qIdgn6g0LqSXsXrT0PljMXbQrsedKyoOlHyTKJZ4qrBj8djc6C54mCqm5yaOedkgKz1GUeIPgjrmJdHFiXHmBKerkKIKRBWsMHI2s4hsmT0ihNHdqAtFQt9a1ijcXoVGAqhDG82nOLCCanuIahh0sKYjic6QbTKJdOHse4444axYrXf0qXi5QWqcV41mIsjwN8Q9wTxitmhhkd2C4p4FvGKvHXha

ps: it works fine if i set distance in trigger, and in conditions check if trigger is active instead of setting distance there

**Comment by InfusOnWoW** [comment]
The bug was in how >= was handled and affected the range trigger too. This will be fixed in the next release.

Do note, that the aura you have posted won't work as is. The range trigger is set to be only active if the distance is <= 40. If a trigger is not active at all, conditions on that trigger won't ever show.

Secondly, the range estimate has a min and max component, and thus two <= and >= checks don't necesarily negate each other.

E.g. if the range estimate is 38-42, then neither <= 40 nor >= 41 will be true, as those conditions are only true if the whole estimate satifies the check.
