### ISSUE TITLE
aura_env.spellId and Trigger:Spell On Cooldown Ready Event

### ISSUE THREAD

**Issue by furtrade** [WeakAuras/WeakAuras2#4398]
I'm trying to play a soundfile (named after spellId) using the trigger: Spell / On Cooldown Ready Event + Actions "On Show" Custom Code.
![image](https://user-images.githubusercontent.com/74581845/231407051-10968698-5ef6-4683-8594-562b92a3f1d8.png)

`local spellId = aura_env.states[1].spellId` 
However, this returns nil, which means I can't use it like this...
`"... \\Sounds\\%s.ogg"`

Please take a look at adding this functionality. Or if the functionality exists, help me see.

**Comment by InfusOnWoW** [comment]
The contents of the state depend on the trigger's needs for conditions and text replacements, not on what arbitary custom code wants.

I this case I don't see a reason to add it, since you can easily accomplish your task by either just playing the sound via the built-in methods, or modifying your custom code to run the correct sound.
