### ISSUE TITLE
Allow groups to use another dynamic group for layout.

### ISSUE THREAD

**Issue by EmElw** [WeakAuras/WeakAuras2#4488]
**Is your feature request related to a problem? Please describe.**
It is common to duplicate dynamic groups for class auras, boss mods etc. across multiple classes/specs/encounters. Changing becomes cumbersome since it needs to be changed multiple times and editing multiple groups simultaneously isn't possible.

**Describe the solution you'd like**
Conceptually just using another dynamic group's display, grow (and sort?) functions. Perhaps you'd register the target group as an anchor group or some such.

**Comment by emptyrivers** [comment]
Why not meld the groups into one? Raid specific auras are unlikely to be active (&thus affect layout) in a dungeon.

**Comment by lierox90** [comment]
you might want to have different grow directions for specific set of spells handled by groups

**Comment by InfusOnWoW** [comment]
That sounds like a lot of complexity for not much gain. There are after all ways to share code via the common environment.

**Comment by lierox90** [comment]
@InfusOnWoW could you point me to PR that added group in group support ? I wanna check it out how complex it would actually be for my own sake

**Comment by InfusOnWoW** [comment]
That's a complicated story, there was a PR but it was incomplete and buggy. So I took apart and over a year integrated various bits while ensuring that everything continued to work. The last change that actually enabled nested groups, dfba73fcea580880707f1f26484c486386194161 and 68aad849a2f65462d0b3678d69dfbbd742f731ea are not that big.

The PR https://github.com/WeakAuras/WeakAuras2/pull/2965 did cotain a buggy implementation of nested dynamic groups, but due to its bug it wasn't merged.

I did promise that I eventually implement that, but since I'm not 100% sure how to best implement it, it's probably a major project of which I manage around one per year.
