### ISSUE TITLE
Condition > property > sound > stop does not stop looped audio since last update 5.5.5

### ISSUE THREAD

**Issue by Hello-code-junky** [WeakAuras/WeakAuras2#4508]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Before 5.5.5 sound stop would stop previous sound loops from continuous playback. Maybe this is not a bug and is rather just how things are meant to work now. If that is the case I will have to rewrite a few weakauras to accomdate for this.

I do see a change with regards to sound in the 5.5.5 change log. "Prevent an empty PlaySound from stopping sounds". I have not inspected that part of weakauras source to determine if that is the case but it seems a likely culprit.

Included a quick demo weakaura of the issue. Mounting + flying will start the sound loop. Landing should stop it but does not. I realize that moving antithetical checks of condition 1 into condition 2 and getting rid of condition 1 will solve the problem but this increases the complexity of each condition and therefore the complexity of weakauras with multiple else if conditions playing many different sounds.

Thanks for reading.

### WeakAuras Version

5.5.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Set condition 1 property sound stop
2. Set condition 2 property sound loop
3. Profit?

Try the code export I pasted below and it will explain more clearly. Thanks.

### Last Good Version

5.5.4

### Export String

```Text
!WA:2!1v1YUTTrx4OF9xuaII2u5aJ20BQobo3QnIDr8Ic0fIos2kv2IHKo2X1f0d5mKAIPMzWmdvSYsHEBDEa6cTUR0Jqw01dm6tGFeYtqpdPId6ftTGZC45Y35C(ohvRtJHnWnW)6TK8cDoLrK93lSx3DBlpTFAQIORjUhMQe5OXHKt1rPC5qKosePPdjr4Xm0qAsKEGKOgWZXJptnaH5p)Pvg)PxzgILmGl94uMoEZ27g22x08YDy1TAIRMuO08Hwn2tGrAIpzeHPphvasrAAY(uSEGBl4QeLOPCMAdFLgj1oXPugvnWXfEPDMOL0SmIu9BllNF8pC1Jfe3c4ZIgfksekwXLXBtq57WXKJpxvexgTGI0u6PZI2Svqyuqyl)WZFR6LQACMUjNHPLa4c78KeWo)aV296nrji55DXkNPysm4Wqi2YTB3ZRZE9mxl2whisFOmsuotSU3IRJNzpnKxW0e8XVeEvbDNLnn(zZ1mFHzH4QkK5MIBMwWklb3(oonHhjrxizn7Q6KpMYYaPegEwL6r2upgku6cLFYasYjXfL1xZNz(8k0Repi0V7wB12)BwRPxVwpTTFvY3(Hr70)jD3DR3kTVN3fsFtegqXeFBZeBUHZmOv)Ss4nISoInw0yEJTkF6XZOjI7Drcmpn)B5XCzF)A)GnpeFiQ0zZDGTl87xrS0LZOgYXrsibpwS8LRuojdLmoknNZLdEPIKNwryD7hg2Fh3uotlUAhj9fnFCbcdUd1mmCk0V9jz2w)1x0SWzW1yuYjzWKed7MZr4oXAuousx0FyrUM64cKHKfnFRJFsosPSNCv0xqShMydsaC5JNpcDq1iu9PYYyy5nUAa6XjCwknZ5Lig1okWzByE)oVIGuKaTKWY0dExZcUmoJCgUqwQrzBxQiGPy1eRQw3z22DiIY6y2cmWSTPR5rMVdE)b)tjIBC5LoHKKqvqmQl(K)tTQoywzAYftk3DzZT3W04RUYKrijffNtwQVFCjDuDx4d1nEUW6KN7pcLxqQbsEhJNX3eutMmaXYiwpeS4uLTsxMBUbAUyIqYH0up2V8dwvGXJVuiHw5Tx6Ib1MR1CLMbwnAATAP7y2FAfRmbytBmhAgV1BT7dnp(6v4Xg96XWcYtGbstOn(DEvv8LebbP9QF)vFGzp3ECUWCG4wDHrxzkkHCulmUptDKh0kw5Rx9(hvgA1rD3zvEw2zv(WMwms(6bDoWSV5G5qF5)f0xhGUhuINJFBWS43COFcpNlFuD4r(mizOPJD71Ut4unpze06bJ)OA)Y)FjkwSqy7GWvFRdA6wKn55CjEFjsmz)5hMLkHDsaJci71FD1w8owrwMtCWM(TBVRC88)Jy9ckEMFRIqvWH5hUrWzWEAq)(IY2D5wG3qm(FZQO3BwI3A1QvFkSSKGlxO)JV3mkRIWag68AQTiYq5pPkd(Pgk)hSk8RXO)8G)6p
```

**Comment by InvisibleSeoh** [comment]
I am having the same issue since a recent update. First noticed it on Thursday raid night. I have a WA that's set to loop a beeping sound to warn me when my brewmaster's brew is about to wear off, and should stop looping on apply / refresh. It won't stop looping until the fight is over or I lose the buff. I have a WA to loop sound when Rashok is at 85 energy and stop when he's back at 90. Same deal. I just created a test mistweaver renewing mist WA that beeps on a loop while the buff is active and is supposed to stop when the buff has less than 15 seconds remaining. It doesn't stop the loop ever while the buff is active. Tested with and without other addons, same behavior. This is driving me batty. BUT!!! I literally just figured out a solution. Instead of telling sound to stop, I can break the loop by changing the stop condition to play the sound instead of loop. It'll beep once more then stop. So there's a temporary workaround at least.
