### ISSUE TITLE
Ready for Update WA's cannot update and cannot delete

### ISSUE THREAD

**Issue by AndrewOldnall** [WeakAuras/WeakAuras2#4531]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello. Somehow i misclicked and collapsed a weakaura i was using, it was sarthe's dk one, i went through and deleted the children bits but some were outdated and now they persist to be ready to update. The issue is when i try and update them to delete them i get errors 'Invalid update target, uids don't match', is there a fix for this? i just want to delete these WA's

### WeakAuras Version

5.6.0

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
N/A
```

### Reproduction Steps

1) Typing /WA to get the window
2) Under Ready for Update
3) Pressing the symbol next to the aura that needs updating.
4) Importing it again so i can delete it.
5) The WA stays in read for update

### Last Good Version

Not sure, definitely wasnt working for 5.4

**Comment by mrbuds** [comment]
There are instructions on how to remove auras for "ready for update" on wa-companion channel on weakauras discord

**Comment by serena-yu17** [comment]
There is no dedicated documentation on the Discord channel about how to clear updates that were stuck. 

You would have to read through all the chat history which depends when you open the channel. 

One way I found was to delete the Wago Addons (not weakaura itself).

**Comment by InfusOnWoW** [comment]
There are pinned explanations.

**Comment by Aealm** [comment]
> There are instructions on how to remove auras for "ready for update" on wa-companion channel on weakauras discord

Could you not just add the instructions to your reply? Let me go join yet another discord channel.

**Comment by ujl123** [comment]
Decided to copy over the instructions from the discord pins here because it's more searchable and all information regarding the app should be consolidated on the github page anyways

What to do if WeakAuras keep showing Ready for Update auras

- Check which of WeakAuras Companion and Wago App Companion addons are loaded, do not run both at the same time. Note that in the case you have an old installation, uninstalling app does not remove addon in Interface/Addons and you may have to do it yourself.
- In companion app, push the button to Refresh auras, then in game type /reload
- Mouseover the yellow-ish Ready for Update buttons, tooltip show the list of auras it wants to update.
- Find the aura using the Search field on top
- If you want to keep your version but to not update, go to Information tab, and delete Url field
- If you want to update and Companion is not helping, delete this aura and reinstall from wago (with Url field)

Once you removed url or aura completely
/reload to save your data
Refresh list of auras in companion app, this will write new data in companion addon
/reload in game once again
 
![image](https://github.com/WeakAuras/WeakAuras2/assets/13132548/8e5823c9-cb7d-4b39-b235-5d52b36254a0)

**Comment by silverwind** [comment]
Deleting `Interface/Addons/WeakAurasCompanion` also works to get rid of stuck `Ready for Update` auras, but I agree there should be a right-click -> delete option on these.

**Comment by haggix** [comment]
Thx for the tip silverwind, you can just edit the  `Interface/Addons/WeakAurasCompanion/data.lua` then search for the line slugs and remove everything inside the bracket slugs:{}

first i've saved all my custom wa (i think this isn't necessary but play it safe
then removed the data inside display `<path to your woooow>\World of Warcraft\_retail_\WTF\Account\<accountname>\SavedVariables\WeakAuras.lua` there is a property `display`, remove everything inside the brackets `display: {}`

you have to reinstall all auras after this, this is my recommendation. 



alternatively you can remove the auras inside the `slugs: { <tons of auras> }`  and ´display: { <maybe more tons of auras> }´ those files are big... and you need a proper text editor

**Comment by drthompson65** [comment]
thanks for all the information.  I still struggle with addons that are stuck in a perpetual loop.  Be nice if we had a way in the WA app ingame to ignore or delete these.
