### ISSUE TITLE
PvP Talent Triggers and Loads dont work after patch updates

### ISSUE THREAD

**Issue by ireliamonster** [WeakAuras/WeakAuras2#4557]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

With most patches, some of my triggers and load conditions involving pvp talent selection changes, see reproduction steps.

### WeakAuras Version

WeakAuras 5.6.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create a weakaura that displays an icon if you have "Master Shepherd" pvp talent selected, the 3rd talent
2. Wait until blizzard removes the 2nd talent, "Ring of Fire"
3. The weakaura will now trigger if the NEW 3rd talent, "Improved Mass Invisibility" is selected, instead of the intended "Master Shepherd" which has now become the 2nd talent. Note that Mass Invis was the 4th talent before the patch, and is now the 3rd one

**Comment by ireliamonster** [comment]
I'm guessing this is the code that needs to change:
https://github.com/WeakAuras/WeakAuras2/blob/82b7bd70c6c5d6c2ec6f635b7bfe3b33eacde0f0/WeakAuras/WeakAuras.lua#L906
```
    local pvpSpecTalents = slotInfo.availableTalentIDs;
    for i, talentId in ipairs(pvpSpecTalents) do
      Private.pvp_talent_types_specific[player_class][spec][i] = formatTalent(talentId);
    end
```
Does it have to be a hashmap based on an arbitrary integer? Maybe we could do something like
`Private.pvp_talent_types_specific[player_class][spec][talentId] = formatTalent(talentId);`

**Comment by InfusOnWoW** [comment]
That's the simple part. (Though obviously incomplete).

The complex part is modernizing all existing auras, which is I think is currently impossible. We would need to map all indexes in all existing auras to talentId, for which we need a class, spec + pvp talent index. But the pvp talent load option currently doesn't require setting a class/spec, thus that information is missing. (And yes people do that, and it works because they only play one class/spec.)

I don't see a good way to do this within an expansion, so this can't be done until the next expansion.

**Comment by ireliamonster** [comment]
> But the pvp talent load option currently doesn't require setting a class/spec, thus that information is missing. (And yes people do that, and it works because they only play one class/spec.)

In case this wasnt clear, the pvp talent load option also breaks on patches with new pvp talents, in the same way as described above for triggers. I realize now I put this in the title only

**Comment by ireliamonster** [comment]
So it could perhaps be considered in a regular patch where pvp talents are changed, as this will break the load options anyway

**Comment by InfusOnWoW** [comment]
Well, they only break for some classes not for all, and also only partially. This wasn't a problem in the past because the pvp talents rarely changed. They have been doing more talent changes in general, though I'm not positive this will continue for the rest of the expansion.

**Comment by ireliamonster** [comment]
Alright

Just for documentation this is also an issue if you try to edit a weakaura for one class when you are logged in as another class, e.g. when I'm working on WAs while in shuffle queue on an alt

**Comment by InfusOnWoW** [comment]
This is now implemented for TWW. The pvp talent trigger now internally uses spellIds, meaning that on patches the trigger should mostly continue to work. (Since spellIds changed less than indexes.) And for specs that share some of their pvp talents, the spell id allows using the same trigger across specs.

Which spells are available can't be determined on another class/spec, so editing is limited.
