### ISSUE TITLE
"Load" tab should have an option to have the aura load only if you're in party with a specific player

### ISSUE THREAD

**Issue by Knbi** [WeakAuras/WeakAuras2#4682]
It'd be a very big quality of life change if you could have an aura load only if you were in the group with a specific player.

Allow us to have an option to write a player's name as a condition for aura loading.

**Comment by InfusOnWoW** [comment]
For what case would that be useful?

**Comment by Knbi** [comment]
> For what case would that be useful?

Playing M+ or arena with a specific player or a specific group of people, tracking various things that are otherwise important when with other players

**Comment by InfusOnWoW** [comment]
That's too niche for the load options. We can't add niche options to the load options page, due to its current design of showing all options on one page. Every option in there has to be useful to a decent amount of players. A check for whether you are grouped with a "named" player doesn't really strike me as something that would be useful to many, even with your explanation of your use case. Having to use a trigger for that is imho fine.
