### ISSUE TITLE
All WeakAuras Erased (?)

### ISSUE THREAD

**Issue by Ceejaikae** [WeakAuras/WeakAuras2#4695]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I had all my WAs yesterday (over 3k of them, custom made for each class) and today I logged in after the 10.2 update and they're gone. WAs opens fine, but there are no items in the list. I have tried reloading. I am going to try to revert to the last release and see if that changes anything.

### WeakAuras Version

WeakAuras 5.8.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
3x Error loading WTF/Account/REDACTED/SavedVariables/WeakAuras.lua: WTF/Account/REDACTED/SavedVariables/WeakAuras.lua:675341: unfinished string near '<eof>'

-----------------------------------------------------------------------------------------------

3x Error loading WTF/Account/REDACTED/Hyjal/REDACTED<Character>/SavedVariables/Details_TimeLine.lua: WTF/Account/REDACTED/Hyjal/REDACTED<Character>/SavedVariables/Details_TimeLine.lua:692991: unexpected symbol near '<eof>'


Locals:
```

### Reproduction Steps

There are no steps to reproduce this. I updated WAs, logged in, and my auras are all gone.

### Last Good Version

WeakAuras 5.8.3

**Comment by InfusOnWoW** [comment]
Unfortunately the game had issues writing your saved variables and the error message indicates that it was loading corrupt data. Addons can't affect the saving of data at all, that's entirely blizzard's code and thus their bug.

The game does automatic backups, but due to blizzard's incompetence it didn't uses these backups on detecting the corruption and even worse since it's been a few hours you probably closed the game by now, and the game has now saved an empty file and overwritten your backup.

Thus you were hit by: a) a blizzard bug on saving the data and b) incompetence by blizzard which on detecting corruption simply overwrites their own backup

If you are running the WeakAuras Companion then that will automatically create backups for you. Unfortunately there's nothing we can do for you.

**Comment by Ceejaikae** [comment]
I have a SV backup. Can I restore my WAs from that? I make it a habit to
backup my Interface and WTF folders fairly regularly.

Thank you,
CJ

**Comment by InfusOnWoW** [comment]
Yes, you need to replace the file in WTF\Account\<Account #>\SavedVariables\WeakAuras.lua with your settings. The second error message indicates that Details_TimeLine.lua was similarly broken, so you might want to take a look at that too.

**Comment by Ceejaikae** [comment]
Thank you so much. (Sorry I didn't say so in my last email). You have
always been helpful and quick on responses. I'm glad I backed up because I
had over 3k WAs! I will let you know if installing the backup works so it
may help guide future issues.

Thanks again,
CJ
