### ISSUE TITLE
All Range checks are failing and causing the addon to stop functioning with the latest game release: 10.2.52188

### ISSUE THREAD

**Issue by voigtboy** [WeakAuras/WeakAuras2#4713]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Just noticed this about 10 minutes ago.

### WeakAuras Version

5.8.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Create item using the Range action.

**Comment by Stanzilla** [comment]
Yeah Blizzard did that

**Comment by Vokilog** [comment]
WeakAuras.CheckRange is it based only on items? will it be completely disabled, or redesigned under IsSpellInRange?

**Comment by fwater** [comment]
I tested that latest fix（[Prototypes.lua. For example, I set a prompt within 20 yards of the Sword of Justice. The distance determined by the plug-in is significantly smaller than the actual distance of skill casting in the game. This distance determination is seriously inaccurate.

**Comment by fwater** [comment]
I tested the modified version commented above. Not only is distance detection grossly inaccurate. Some small range distance detection is still invalid. I haven't tested them all, but some distances such as 10, 20, and 30 work. As for the accuracy of distance detection, it should not be as good as the previous version

**Comment by Vokilog** [comment]
it is clear that the functionality of IsSpellInRange is severely limited by your spells. For someone it will work well, but for someone it's just disgusting.
I'm just considering a way to do at least something, instead of a complete disable.
Use it only whitout combat - idk, it generally has the right to life? I can't think of a good example when a Range Check is needed outside of combat.
