### ISSUE TITLE
condition for "if t[x] duration > t[y] duration" (vice versa)

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#477]
**Describe the solution you'd like**
basically a condition that's like:

If Trigger x
Trigger Duration
< or > Trigger y 
then do things

**Additional context**
Every few tiers there's a mechanic where you have to soak something unless you have a debuff.
the debuff however sometimes expires right before the soak applies a new debuff. 

Instead of going custom or having to do math mid pull, it would be nice to have a condition that compares the duration of triggers so you can hide the text for example from "Soak" to "Don't Soak" based on comparison results.

(basically making 2 texts, both bottom, hide one or the other based on the result)

edit: it does come up a bit if you search for "compare duration" in wa discord's search

**Comment by emptyrivers** [comment]
Some notes on how to possibly achieve this request on the back-end:

`condition.check` contains the data which generates the...condition...part of conditions. `check.value` is the value which `check.variable` is compared against. Instead of having a static value, we could instead have `check.value` be replaced with:
```lua
-- mimic today's behavior
check.comparand = {
	source = 'static',
	value = 1.2
}

-- source from trigger 2 state.duration
check.comparand = {
	source = 'state',
	value = 'duration',
	trigger = 2
}

-- source from data.config
check.comparand = {
	source = 'user'
	value = 'someCustomOptionKey'
}
```

and then, depending on the value of `comparand.source`, look in a different place for the value to be compared to.

**Comment by InfusOnWoW** [comment]
I think adding a way for custom checks to be written is good enough.

**Comment by InfusOnWoW** [comment]
This is now possible via the custom check option.
