### ISSUE TITLE
Spellname (GetSpellInfo) for Boss Mod Timers Trigger

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#4777]
**Is your feature request related to a problem? Please describe.**

BigWigs/LittleWigs tend to change the key/spellId at times.
example1: https://github.com/BigWigsMods/BigWigs/commit/5ec1798f489a32f067e8dda049ccc92b1a7fc778
example2: https://github.com/BigWigsMods/LittleWigs/commit/b8126c26c4201fac925a5b7d95ffc9b00ffb01b2 (skyfall timer)

it sucks when WAs stop functioning mid progress

**Describe the solution you'd like**

it would be neat if weakauras had an option to use key name instead (GetSpellInfo() input and see if there's match with BW/DBM)

**Describe alternatives you've considered**
custom code

**Additional context**

**Comment by InfusOnWoW** [comment]
Four points:
* This is the first tier of key/spellId keys, I'd want to wait for another tier to figure out whether this will be a common problem, that we should adress with a feature. 
* This change in spell id is probably also because the boss wasn't tested. That is I couldn't find anything similar in the recent commits. Are you aware of any other similar change? If blizzard decides to have less testing in tww, your problem might become more common.
* I'm not sure the solution will solve the problem of changing ids sufficiently, often abilities have multiple parts that have different names and this would do anything if BW switches which ability is the "main" one.
* I'd say that's mostly bigwigs fault. If they promote this as the id that boss mods should use, then they shouldn't change them. 

So at this point, unless you can point to more examples where the id wasn't stable, I'd rather wait and see how it'll work out in the next tier, though this is important feedback.
