### ISSUE TITLE
List multiple spells in the Load Condition for Spell Known

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#4804]
**Is your feature request related to a problem? Please describe.**

Would like to be able to load on multiple different spells being known. The specific use case would be things like interrupts or dispels that exist across multiple classes/specs, but you might want a single Aura for all of them that only loads when appropriate.

**Describe the solution you'd like**

Could simply be a comma separated list of spellIDs/names/links in the existing setting.

**Comment by mrbuds** [comment]
it's easy to accomplish by adding simply adding:
```Lua
      multiEntry = {
        operator = "or",
      },
```
which result in
![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/7756dbc3-71fa-4c3e-aa4f-a8af9f2fec43)

But it raise some questions
- depending on use case, one would want the operator to be an "or" or an "and", giving users the choice of the operator is not currently supported, it's a path of action to consider that could benefit other places, seems not easy to implement and i'm not sure if it's worth it for something that could be accomplish with trigger logic
- it always add at least 2 lines because of the "Exact spell match" option, that overload a bit the options with widgets (sorry not i'm sure how best to describe in english), it has a downside UX cost that has to be considered


> Could simply be a comma separated list of spellIDs/names/links in the existing setting

Spellid widget is built to show spell's icon, spell's name if an id was typed, and optionally an "exact spell match" option, all of that is not fit for multiple entries in same widget as you can do with encounterid/mapid/etc..


My personal opinion on this feature request lean into not implementing it, for the reasons mentioned, balance could weight the other way with more use cases and demands

**Comment by InfusOnWoW** [comment]
Yeah I agree with Buds, this is not as trivial as it seems. At some point we probably need to make the loading more flexibel, at which point multiple spell known and their conditions would be on the table.
