### ISSUE TITLE
Please split the Loaded/Standby section into two groups

### ISSUE THREAD

**Issue by aproctor** [WeakAuras/WeakAuras2#4821]
**Is your feature request related to a problem? Please describe.**
Adding the "Standby" weak auras into the "Loaded" section has made the list a bit overloaded for some users, and challenging to find and update weak auras that are active.  I have dozens of auras in standby currently, that are gated on zones, encounter ids, class/spec settings that are all included in the section.  Before this change I had < 10 loaded auras in the "Loaded" section.

**Describe the solution you'd like**
I think it would be nice if there were 3 sections "Loaded", "Standby" and "Not Loaded" sorted in that order.  It would hopefullly provide whatever functionality the surfacing of Standby auras added, while preserving the sort priority of the Loaded auras.

**Describe alternatives you've considered**
If we could sort all the Loaded auras to the top of the current combined category, it would be a quick improvement.

**Additional context**
![image](https://github.com/WeakAuras/WeakAuras2/assets/711967/eeaf87c3-e1b3-4e39-92a5-1c9cb12e52b2)
As an active Raider and M+ player, my standby list is quite large.  I do reguarely clean it up so this is only content relevant to this season, but it is still a huge amount.

**Comment by mrbuds** [comment]
> I do reguarely clean

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/478abb77-9ff0-4d80-a408-b6e88eeb1429)

**Comment by InfusOnWoW** [comment]
A standby section would defeat the purpose of the change. All relevant auras that you actively are using to be in the top section. Previously raid/dungeon auras would be hidden in the unloaded section, which was bad.

That is all these auras that you are using, and don't want to delete would be hidden in the bottom section. Auras that are loaded only in specific encounters will never appear in the upper section, since you can't open the settings while an encounter is in progress.

In essence the same problem that you are now complaining about existed even before the change. It's just more apparent.

As Buds has pointed out, you have auras even for Shadowland's first raid in your screenshot. After properly cleaning up and sorting your auras into a few groups the end result will be that no matter whether you edit a raid aura or a class specific aura, it's likely in the top section. Whereas auras for other classes which you are unlikely to interact with are in the bottom section.

**Comment by aproctor** [comment]
I find it wild that you guys expect us to reparent and potentially break imported weak auras.  I have 1 (out of dozens) from Nathria.  You're telling me to delete weak aura groups that are used by details.  Also having them in a group does not solve my problem when I'm trying to debug which active aura on my screen needs to be fixed.  These auras are not active and obscure the loaded aura even if they're logically grouped.

> A standby section would defeat the purpose of the change

What is the purpose of this change? Because if it's raising the visibility of addons that are in standby, I believe you can still do that without sacrificing people's ability to see which auras are loaded.

**Comment by InfusOnWoW** [comment]
If you are debugging an aura, there's a decent chance it is one of these encounter specific auras, since the majority of your auras are in that category. 

Previously these auras were all in the unloaded section together with tons of irrelevant auras. Now they are all in the upper section, so you no longer have to potentially look for the needle in the haystack. 

So there's a decent chance the aura that you are looking for is actually easier to find. Obviously there's also some auras that are now harder to find, but that's the tradeoff we did there.

And once you properly clean up and maybe organize your auras a bit better, you'll have a even better chance of finding an aura quickly.

**Comment by aproctor** [comment]
I've done a bit of organizing as suggested to see if it improved things. The down side of using top level groups is that they appear to be added to the loaded section as long as any sub aura is loaded.  Which means that while my auras are getting more organized, the loaded section is becoming less and less meaningful as slowly nearly all my auras are making their way into the aura section.

![image](https://github.com/WeakAuras/WeakAuras2/assets/711967/714c5030-f2fa-4fef-99fd-4f36b3c63c9d)

**Comment by mgarbacz** [comment]
Standby being lumped in with Loaded WAs is resulting in a cluttered display for me also. I raid and mythic plus and solo pvp and group pvp and do professions, I play all classes and roles in some form or another, and I actively make my own WAs. This results in my having a lot of WAs, but only very few loaded at any one time.

The previous experience of a clean `Loaded` section was nice. The current experience of a giant `Standby/Loaded` section is a lot of cognitive load when trying to edit a specific WA while on a specific character doing a specific form of content. Naturally I struggle to find time to do all the content I want to do on all the characters I'd like to do it on. Hunting through WAs is not how I want to spend that time. Spending any more time trying to workaround this or organize them further isn't either.

I understand the argument for the combined list. It sounds like the default won't change for that reason. However, I request an option or active toggle to have a section that just displays "Loaded" WAs, please.
