### ISSUE TITLE
Add checkbox to hide glow when Condition is no longer met

### ISSUE THREAD

**Issue by Thundertom79** [WeakAuras/WeakAuras2#4848]
Right now whenever a condition applies a glow you have to create a seperate condition to hide it.

My suggestion would be to have a checkbox in the condition that reads something like "Hide glow when condition is no longer met"

This would save you the trouble of creating seperate conditions for the same thing.

Thanks for a great addon!

**Comment by InfusOnWoW** [comment]
If you show a internal glow, then that is automatically hidden if the condition is not met.

If you glow an external element, that glow is not automatically hidden because it's an action not a property change. There's no way to automatically undo an action, becasue that's not how these things can work.

**Comment by Thundertom79** [comment]
I did mean external element yes.

Ok Thanks for explaining, if you say it cant be done that ok with me, merely suggesting it.

Thanks for your reply.
