### ISSUE TITLE
Loaded/Standby view/display all aura's not working

### ISSUE THREAD

**Issue by Warzau** [WeakAuras/WeakAuras2#4888]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Loaded/Standby view/display all aura's not working, it only shows some aura's, the ones that are green loaded?  the yellow "standby?" aura's do not display.    the display all is nice for adjusting positioning of all aura's?   can this display all function be fixed, or added back?  user error?

### WeakAuras Version

5.10.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Open weak auras, click the Loaded/Standby green eyeball button for display all

### Last Good Version

a month or two ago it worked, prior to the standby function?

### Screenshots

![WoWScrnShot_022624_113441](https://github.com/WeakAuras/WeakAuras2/assets/161368275/7e679584-1c11-43ba-9d2a-3c030bfb9a1c)

**Comment by InfusOnWoW** [comment]
That's by design. 

I agree that it is a bit confussing to not show all auras in the loaded/standby section, but there's a good reason for the button behaving that way. 

Many users have multiple dungeon/raid packs installed, all of which are in the standby section. If the button would toggle all auras, that would make all of these auras visible, which is something we want to avoid.
