### ISSUE TITLE
Debuff Type: Magic

### ISSUE THREAD

**Issue by cybersrs** [WeakAuras/WeakAuras2#497]
First, I want to thank you all for the addon, it is amazing!

Okay, I play as Priest Discipline and I like to Dispel Magic and Diseases from players (or myself) with Purify (Skill).

So, let's see the Magic Trigger...
The trigger is Type: Aura > Use Full Scan (High CPU) > Debuff Type: Magic > Unit: Target(or Player) > Aura Type: Debuff > Show On: Buffed/Debuffed.

Tested it dueling with a Frost Mage, Magic skills like Forst Nova, Polymorph etc. The trigger does not work. If I disable Debuff Type, it does work, it is like the trigger does not recognize those debuff as Magic.

Looks like I'm doing it right, please let me know.

**Comment by mrbuds** [comment]
UnitDebuff returns "Magic"

on line 1472 of BuffTrigger.lua 
debuffClass == trigger.debuffClass compare "Magic" with "magic"

the value "magic" come from line 205 of same file:
values = WeakAuras.debuff_class_types

taken from Types.lua:
WeakAuras.debuff_class_types = {
  magic = L["Magic"],
  curse = L["Curse"],
  disease = L["Disease"],
  poison = L["Poison"],
  enrage = L["Enrage"],
  none = L["None"]
}

i tested to rename the key : magic = L["Magic"] => magicx = L["Magic"]
and the comparison debuffClass == trigger.debuffClass compared "Magic" with "magicx"

trigger.debuffClass is populated with the key of the selected value instead of it's value

**Comment by mrbuds** [comment]
changing the case of the first letter of each key fix the problem, but it's gross
WeakAuras.debuff_class_types = {
  Magic = L["Magic"],
  Curse = L["Curse"],
  Disease = L["Disease"],
  Poison = L["Poison"],
  Enrage = L["Enrage"],
  None = L["None"]
}

**Comment by cybersrs** [comment]
Thank you very much!

Also, I would like to know how can I make it trigger Only those Magic Debuff that I can Dispel, the ones I can not dispel, I do not want to get triggered. With old addon Power Auras I could select an option to trigger only the ones I can dispel. Weakauras also have this option?

Is there a timeline for this fix?

**Comment by cybersrs** [comment]
Also, I would like to add, if I set health trigger on focus and the focus is a player, it does trigger, but if the focus is a dummy target, does not work.

**Comment by asakawa-k** [comment]
I can't replicate that

**Comment by emptyrivers** [comment]
Fixed in the next release.
