### ISSUE TITLE
Controller support / Controller Trigger

### ISSUE THREAD

**Issue by jsinger7** [WeakAuras/WeakAuras2#5033]
**Is your feature request related to a problem? Please describe.**
I'm dealing with carpel tunnel and trying to use my controller more when not doing higher level content, and sometimes using my steam deck. I'd like to enable certain weakauras if a controller is plugged in, or possibly if the consoleport addon is enabled. I've got an LUA solution sort of working, but it would work much better if it could be used as a trigger or load condition instead of custom code.

**Describe the solution you'd like**

**Describe alternatives you've considered**
https://pastebin.com/dEKCBQsd - this code sort of does what I want, but is difficult to modify, and I'm not a coder at all.

**Comment by InfusOnWoW** [comment]
That sounds far too specific for a built-in trigger or load option for now, as you are the first one to ask for that.

And it's doable with an custom trigger, which our discord can help you write that in a proper way. Your code isn't the best way to accomplish that, since you are manually showing/hiding the aura instead of writing a custom trigger.
