### ISSUE TITLE
Avenging Wrath Bugging out and not loading

### ISSUE THREAD

**Issue by LsdPanda** [WeakAuras/WeakAuras2#5283]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Avenging wrath wont show up in view on cd or active nothing appears I tried making a new fresh aura and it still would not load even though I have it unlocked im not sure if it is bugging or not but I could not find info anywhere on it. not sure if something is happening with the might version but both wont work.

### WeakAuras Version

5.15

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Premade- Icon- medium/large/small- Cooldown- Avenging wrath- show cooldown/ cooldown tracking- create

**Comment by InfusOnWoW** [comment]
We have not actually updated the templates yet, we'll do that before the TWW release, so it's not unexpected that it doesn't work.

From your description it's not clear which spec you were in when creating the templates, so I can't tell you whether this is due to that, or whether there's a further issue. 

If you attach the aura that is created, or mention the spec, I can take another look. Until then I'd assume that this due to us not yet updating the templates.
