### ISSUE TITLE
[Feature request] Add option for edge animation for spells with charges

### ISSUE THREAD

**Issue by Mistrick** [WeakAuras/WeakAuras2#5295]
**Is your feature request related to a problem? Please describe.**
Recently I noticed that there is an option in "Track Cooldowns" - "Cooldown". With it you can get almost identical animations as in "BlizzUI ActionBar". It's missing a small detail. "Edge" animations when at least one charge is present.

**Describe the solution you'd like**
Add an option for the "Edge" animation to match the behavior of the "BlizzUI ActionBar"

**Describe alternatives you've considered**
I can make custom conditions but they don't allow for the desired result. If the charge is in cooldown, the GCD animation will not appear.

**Additional context**
Left BlizzUI, right WA with Track Cooldowns - Cooldown.
![Recording 2024-08-07 at 13 23 31](https://github.com/user-attachments/assets/5a9d7b9f-5ae8-44bc-ab6c-7fa915e8b551)

**Comment by InfusOnWoW** [comment]
What WA displays depends on the what you track. If you want to track charges, you need to enable that option, as you noted. Your wish of "easily" just adding an option for that is counter to how WA treats configuration.

WA does not on one icon allow for tracking charges and the gcd concurrently, and that's because I don't see the value in showing the gcd everywhere.
