### ISSUE TITLE
Button with "Collapse all"

### ISSUE THREAD

**Issue by Foioyoi** [WeakAuras/WeakAuras2#5449]
**Is your feature request related to a problem? Please describe.**
Yes. Every time I edit my auras.

**Describe the solution you'd like**
A button `Collapse all`. Every time, when editing an aura, I switch to "Display" or "Conditions" and have to collapse all manually.

**Describe alternatives you've considered**
~~A clear and concise description of any alternative solutions or features you've considered.~~

**Additional context**
~~Add any other context or screenshots about the feature request here.~~

**Comment by InfusOnWoW** [comment]
I don't think we can easily add a collapse all button. Our layouting possbilities are quite limited.
I did tweak the collapse settings, so that by default most of the display is collapsed, that is all of the sub elements, the position and progress source settings are now by default collpased. It remains to be seen how well received that will be by other users.
