### ISSUE TITLE
Add Toggle to check for "Nameplate Timers" of the bossmods trigger.

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#5484]
**Is your feature request related to a problem? Please describe.**
Both BW and DBM have nameplate timers now to display cd's. This is extensivly used especially in Dungeon environment. Many people like different displays of their Bossmod timer bars (timeline types or text based displayed) so they have no additional filter selected in their bossmod trigger as they just want to see all of them. Since there is currently no way to distinguish nameplate from other bars in WA they get spammed with a billion timers showing up that they can't rly disable without disabling the nameplate timer feature from those bossmods.

**Describe the solution you'd like**
A simple toggle to differentiate between those so you can just trigger off of al nameplate timers (or all bossmod timers)

**Describe alternatives you've considered**
To disable them you can currently only disable the entire feature of bossmods or write extensive custom triggers which include the complete state handling of bossmod callbacks.

**Additional context**

For DBM it could work simply checking if the guid arg exists see [here](https://discord.com/channels/157608978124242945/821535537911037952/1107316113794138202) Probably could ask @MysticalOS about more details. 

I don't know how BW handles those things someone would have to look into it or ask funkeh

There is also IsPriority flag in DBM idk if bw has a similar thing for emphasized things. See more context [here](https://discord.com/channels/157608978124242945/821535537911037952/1280298881367670874)i think both buds and Infus have access

**Comment by MysticalOS** [comment]
I thought I solved this ages ago when i changed bar type for nameplates to "cdnp" or "castnp" and you could just ignore those in custom code. But if you're just using the bossmod timer start then I guess it's still hard to filter because BW never added bar type arg (they don't like to add features only one boss mod supports and BW doesn't categorize their bars by type).

I could just move the nameplates to use a different named callback cause I'm pretty sure BW doesn't send timer callbacks with theirs. I could be wrong though.

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DeadlyBossMods/commit/495d66f138fb6742fd5e9289af99e1e3223a0169#diff-20314ec663836ac506d2c67e86fe37695be308560685e74aada452f52076b80cR197

Just splits nameplates to their own callback. the callback is a perfect mirror to timer ones.

If anything WA Addons can now just add a "BossMod Nameplate start/stop" now and add my new namplate callback and bw equiv so weak aura devs can easily watch nameplates IF they want to and don't have to filter them from timer callbacks using type arg anymore.

**Comment by mrbuds** [comment]
I'm not interested in adding more features to bossmod triggers, but PR welcome

**Comment by MysticalOS** [comment]
Fair enough, but either way jods problem is solved. basically with tonights DBM update his timeline aura will no longer show nameplate timers, it won't even have option to anymore.

**Comment by InfusOnWoW** [comment]
I don't think there's much value in having a nameplate boss mod trigger. I can't think of a good use case for that.

But thanks for fixing jods issue, we could have easily added a bit of filtering on our side too.

**Comment by Jodsderechte** [comment]
I could see people wanting to use something similar to the nameplate cd aura but relying on bossmods directly that don't want to use plater with the direct integration. But i don't feel strongly enough about it to make my case.

**Comment by InfusOnWoW** [comment]
I see the value there, just not that much atm. Adding it would be easy though, so if anyone really wants it, I'd put it on my list of things to look at at some future date.

**Comment by linaori** [comment]
My use-case is specifically for Jods' timeline WA, so here's my "Why I'd really like to have this feature, or something that makes this possible"

Nameplates are cluttered, it's hard to provide the right information in a visible way because as soon as you're in M+ and making "bigger" pulls it becomes sketchy to see things. Nameplates will overlap and hide important information, including those timers, but timers might also hide casts, especially as we also have to keep track of debuffs (and sometimes buffs) on mobs. There's only as much space before stacking nameplates will start overlapping and this is something addons can't solve.

For this reason having DBM CD timers on the timeline is really important because there I can actually see what's going on. Especially as a caster it's important for to see how long I have until our entire group is being pulled towards a mob in Siege of Boralus, or when in Stonevault several charging mobs will start charging. I don't want to search for nameplates and try to figure out how many other nameplates are overlapping before I can see it.
