### ISSUE TITLE
Option to force Cooldown Progress triggers to check cooldown via SpellID

### ISSUE THREAD

**Issue by BillWiegert** [WeakAuras/WeakAuras2#630]
**Is your feature request related to a problem? Please describe.**
The Guardian/Feral Druid spell Thrash has two different versions with different spell IDs. It swaps between the two depending on the form you are in. Currently a cooldown progress trigger for thrash will only track bear thrash if you are in bear form and cat thrash in cat form, even if you enter the spell ID of the version you want to track. It is important for Guardian druids to track the CD of Bear thrash while they are in Cat form.

**Describe the solution you'd like**
I assume this problem is a result of using the spell name to check cooldown progress instead of the spell ID even when a spell ID is entered. It would be nice to have a checkbox option to force the use of SpellID when checking cooldown progress.

**Describe alternatives you've considered**
I have made a custom trigger that gets spell cooldown info with the spell ID (77758) and it works as expected. But this means I am unable to use dynamic info in the conditions tab and makes the weakaura more difficult to edit for people I share it with.

**Additional context**
It's Catweaving, not Bearcatting

**Comment by InfusOnWoW** [comment]
It's a bit more complicated than you imagine.

If you enter a spellname, we immediately convert it to a spellId. (That conversion depends on what exact talents/specs etc, you have at that moment.) We do that, because if we save the spellId, then it stays localization independant.

Now, on actually tracking cooldowns, we always ask via the spellName, because for some classes a talent changes the spell id, but uses the spell name. And obviously a aura should not be affected by selection a talent.

What you want runs thus a bit contrary to how it's handled internally, but we'll get that sorted out.

**Comment by InfusOnWoW** [comment]
There's now a "exact match" on a few spell related triggers.
