### ISSUE TITLE
When creating auras, add aura to a group automatically

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#647]
**Is your feature request related to a problem? Please describe.**
When creating an aura, it would be very useful to have that aura go into the group I have selected automatically.

**Describe the solution you'd like**
If I have a group selected and expanded, add any new auras that I create (from New or From Template) to that group.

**Alternative**
Allow sorting by date created/updated/imported so they can be near each other for easier adding to group.

**Additional context**
When creating large groups of auras (like through Templates for Azerite Trait tracking), it would save a lot of time to not have to find them where they fall alphabetically and intstead have them go directly into the group I have for them.

**Comment by InfusOnWoW** [comment]
The problem is that on selecting new, the group is technically no longer selected.

My preferred solution would be to make new part of a "toolbar", next to the search button. (Same with import, and thus it would be capable of inserting into whatever is selected.)

As to your context, @mrbuds was interested into investigating adding "creating groups" directly from templates. I think being able to create into a group is a generally useful idea.

**Comment by emptyrivers** [comment]
Something along the lines of this has been implemented in 2.7.8 and later.
