### ISSUE TITLE
Supercharged Templates Design Dicussions/TODO List

### ISSUE THREAD

**Issue by InfusOnWoW** [WeakAuras/WeakAuras2#660]
~~* The last page needs icons.~~

**Comment by Stanzilla** [comment]
I want to work on the descriptions some more

**Comment by Stanzilla** [comment]
item.buff and item.requiresTarget and item.debuff and item.requiresTarget have insufficientResources, that should be isUsableBlue, right?

What do totem types do with insufficientResources?
Do we make color items blue when they ARE usable and spells when they ARE NOT usable or is that just weird naming?

I made some wording changes, can you check if that all matches what it actually does? @mrbuds

**Comment by InfusOnWoW** [comment]
The templates don't work very well with non-icon types.

**Comment by mrbuds** [comment]
Except "Basic Show On Cooldown", I made everything use either insufficientResources or isUsableBlue (if "usable = true"), including totems, because most shaman totems cost mana.

It is a bit overkill and the condition will not be use on some ability with no cost indeed

Yes it's a weird name, isUsableBlue, make the icon blue when NOT usable.

**Comment by Stanzilla** [comment]
okay we need to rename that then :D

**Comment by mrbuds** [comment]
I made a PR to fix non-icon types and rename isUsableBlue.
Instead of the glow effect i used the color yellow for non-icon.

I'm using a color code to show the state of a spell
- blue = not usable
- grey = on cooldown
- red = out of range
- yellow / glow = active

Now, the 4 types of progress bar we give have different default color :
- red
- red
- yellow
- green

I think we should give only 1 default color possibility, which would not conflict with the color code.
White is the easiest solution, what do you think?

**Comment by mrbuds** [comment]
btw i think we should only give 2 possibilities for progress bar, horizontal & vertical

**Comment by mrbuds** [comment]
![cooldowntext](https://i.imgur.com/bq5aR84.png)
"Show Only On Cooldown" is bad naming

**Comment by mrbuds** [comment]
"Default" icon have cooldown and inverse = false instead of true for all other icons

**Comment by InfusOnWoW** [comment]
* Changing the first screen to be more like this:
https://media.discordapp.net/attachments/273144328447197186/481179051445452820/wa.jpg

**Comment by mrbuds** [comment]
I made isBuffedGlow() use color yellow for regionTypes which don't support glow but support color.
As a result, the description of templates with glow is wrong for these regionTypes.

**Comment by mrbuds** [comment]
Added icons in #664 
![icon1](https://i.imgur.com/1Vlwlgy.png)
![icon2](https://i.imgur.com/gouxOMu.png)

**Comment by InfusOnWoW** [comment]
Ah I like 3 out of 5 icons immediately. The silver/gold clock thing is brilliant.

**Comment by InfusOnWoW** [comment]
All done.
