### ISSUE TITLE
New "target" condition for status - cast

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#677]
**Is your feature request related to a problem? Please describe.**
This is a suggestion coming from a guild mate, he wants a condition for `status - cast` to change the aspect of the bar when he is targeted

**Describe the solution you'd like**
What he is asking is a new condition for target = "player", the condition could take a unit id instead of just "player".

Maybe also add this in the trigger.

To make it work the trigger needs to listen to "UNIT_TARGET", because there are a lot of examples of casts where the target change after it has started.

If this feature make sense for you, i will work on this next

**Comment by emptyrivers** [comment]
Why does the UnitIsUnit trigger from unit characteristics not work?

**Comment by mrbuds** [comment]
I'm trying to mix `status - cast` with unit characteristics and the conditions doesn't work as i expect
https://wago.io/SJLk1RePm

activation: return t[1]
- trigger status cast
- trigger unit characteristics unitisunit(targettarget, player)
- trigger unit characteristics isattackable(target)
conditions:
- T2 active: print (tried with active, and with unitisunit=true)
- T3 active: print (tried with active, and with attackable=true)

both conditions don't work

Am i doing it wrong?

**Comment by InfusOnWoW** [comment]
First of all, whether you are targeted by a spell is complicated. Some bosses don't target the right target on spell cast. Some bosses target after a short delay and so on. This is best handled on case by case basis with custom code.

I fixed a few bugs in that area, which had to do with how actions behave differently.

There seeems to be a issue with running print from custom code, I didn't investigate since there's a "Chat Message" option for conditions which works.
