### ISSUE TITLE
Only preview custom code editors below a certain number of bytes

### ISSUE THREAD

**Issue by Tehrible** [WeakAuras/WeakAuras2#697]
When swapping tabs (display, trigger, etc) of any WA with lots of custom code (or going to a different aura in the Options that fits that criteria), WoW will temporarily freeze up until all of the code has been loaded in the preview/editing window (at least that's what I assume is freezing the game).

I would recommend that instead of loading up all of the code right when the tab is entered, instead check the size (either by bytes or lines or whatever) of the custom code being loaded, and if it is beyond some arbitrary limit, break from loading it all and instead show just the first few lines in a preview.

Most auras only hang for a few moments, so the issue only becomes apparent in auras with excessive amounts of code (like mine), but I thought I would suggest this anyway.

**Comment by InfusOnWoW** [comment]
Well, don't use excessive amounts of code.

**Comment by InfusOnWoW** [comment]
So to expand a bit on that, because that's a bit of a too short explanation.

Your solution would add additional complexity to WeakAuras for a case, we would need additional logic to decide when to show a preview and prevent editing in those previews. In this case this would be not that much.

But on the other hand, the gain is minimal at best. There is probably just one or two auras in total, that use that much code. And while it the interface hangs, it does work otherwise, so this is incovenient but not broken.

**Comment by Tehrible** [comment]
Thank you for the expanded explanation.
