### ISSUE TITLE
Progress Texture - Orientation clockwise and anticlockwise

### ISSUE THREAD

**Issue by MattBurkett** [WeakAuras/WeakAuras2#72]
While using a progress texture to make a circular bars, the quadrants become offset by 1 pixel down and to the right while the current angle is in that quadrant. This leads to a noticeable 1 pixel gap between the 1st and 4th quadrant while in the 4th as well as slight offsets. I'm not sure how to fix this, but I have narrowed down where I think the problem is: RegionTypes/progresstexture.lua at the spinnerFunctions function for the WeakAuras2 source code. The issue persists across both clockwise and anticlockwise. If anyone has an idea how to fix it, I'd love the help.

I have attached a gif illistruation the issue, as well as the group's export string.

![progresstexutre](https://cloud.githubusercontent.com/assets/20583130/17032869/0f5c9cac-4f41-11e6-9993-79d644054cad.gif)

[ProgressTexture.txt](https://github.com/WeakAuras/WeakAuras2/files/376645/ProgressTexture.txt)

**Comment by InfusOnWoW** [comment]
That's because the circular progress contains actually 4 different parts. Those are positioned on the same coordinates, but due to how WoW's coordinates work, those might lie between pixels. So there's not much we can do about that, if the coordinates don't fit.

Changing the ui scale so that the coordinates in WoW match your real coordinates, e.g. see this:
http://www.wowinterface.com/forums/showthread.php?t=31813 should make it work.

**Comment by MattBurkett** [comment]
Thank you! That fixed it perfectly!
