### ISSUE TITLE
Glow when off CD triggers multiple times.

### ISSUE THREAD

**Issue by Himegami93** [WeakAuras/WeakAuras2#721]
**Describe the bug**
With the current version the glow effect when a spell comes of CD seems to trigger multiple times. It also seem to happen when any other skills comes of CD, then the other icons will also glow/flash again.
This seems to be worse for 2.7.6 and not as bad with 2.7.7, but it still happens. 

Expected behaviour should be one "flash" and then just glowing (Works fine with version 2.7.5, if you want to check out the normal behaviour). What happens instead can best be seen in this video: https://streamable.com/56447  (Please ignore the German :-P )

**Do you have an error log of what happened?**
No

**To Reproduce**

1. Get this WA set ( https://wago.io/rJEy1klOX)
2. Go to a dummy for example
3. Start fight
4. Don't use chimera shot for example so its glowing.
5. Use other skills normally watch as the chimera shot icon will keep flashing

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, the issue persists. Also clean installed Weakauras, removing everything from the Addon Folder, then reinstalling WAs and just adding this one Weakaura set.

**Which version of WeakAuras are you using?**
With 2.7.6 the problem was worse, with 2.7.7 it doen't seem as bad but still happens.

**Was it working in a previous version? If yes, which was the last good one?**
Was working fine with 2.7.5 and beforehand.

Again link to the WA:
https://wago.io/rJEy1klOX

**Comment by mrbuds** [comment]
Can you try give a single aura as example instead of a full package? That would eliminate the possibility that what you see is a combinaison of 2 or more auras.

**Comment by Himegami93** [comment]
Hey, sure:  https://wago.io/rynB01gum . Sorry that its only hunter stuff.

**Comment by InfusOnWoW** [comment]
I can reproduce the issue with 2.7.6 easily, but not at all with 2.7.7. 

There was actually a bug fixed in 2.7.7 that would prevent some conditions from properly applying and your aura is setup in such a way that it runs into that bug. So any issue in 2.7.7 is unlikely to be the same as the one with 2.7.6.

The video appears to show the 2.7.6 bug, can you record a video showing how it bugs out with 2.7.7?

Your example aura is setup rather suboptimally, you can have the same effect with just one cooldown progress trigger with "Show On" set to always and using the "On Cooldown" condition. That might have something to with it.

**Comment by InfusOnWoW** [comment]
With some help from our discord by @mrbuds and @amiyuy, we figured out the problem in trying to reproduce it. There need to be at least two auras tracking cooldowns for the bug.

**Comment by Himegami93** [comment]
Nice :)

**Comment by InfusOnWoW** [comment]
Fixed for the next release, thanks.
