### ISSUE TITLE
Tracking buff with longest remaing duration

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#787]
I think the option to get dynamic info from the last active trigger would be quite nice, a use case for this is something like unstable affliction, since it has 5 different dots, you only want to track the duration of the longest one which will be the one that was last applied.

**Comment by asakawa-k** [comment]
"First active" is referring to the lowest-numbered trigger. 
But above it sounds like you're using "last" to mean "most recently triggered"?
If you meant "last" in the same sense as "first" then you could just reorder your triggers. 

My issue with this idea is that more control of dynamic info would be nice but if you decide that more dynamic info options are needed then the requested setting becomes one of a massive number of equally rarely needed possibilities. 

If Dynamic Info were to be expanded then I think that it ought to be a bit more holistic rather than just, piecemeal, adding more single options to the list.  
For example (and this is just off the top of my head, not a fully formed proposal) what if the custom activation function didn't just get sent a table of bools but a table that, if the trigger is active, contains its dynamic info. Then from the custom activation function you can return true/false _and_ a trigger for dynamic info. 

So it would look like:
```LUA
function(t)
    if t[1] and t[2] then
        if t[1].expirationTime < t[2].expirationTime then
            return true, 1
        else
            return true, 2
        end
    return t[3], 3
end
```
This would be pretty well backwards compatible (only issue I see would be anyone comparing directly to true/false, `if t[1] == true then`) and would give complete control over the dynamic info used in your Aura.

**Comment by 1ps3** [comment]
Yea, that's a pretty nice idea. The only reason I brought it up is because we have one thing but not the opposite.

**Comment by asakawa-k** [comment]
Oh. Well if you do just mean the opposite of what "first active" currently does then users can just reverse their own trigger order very easily now. That's definitely not needed. 

Worth saying that that also doesn't achieve your stated use case. AFAIK if you applied 2 UA then, after the first wears off, you apply another, the new application will take the empty first slot. At this point the "last active" is not the longest expiration.

**Comment by InfusOnWoW** [comment]
You two are asking for two very different things.
For aura triggers, I can add a "longest expiration" time mode in the new code, that's pretty trivial to do.
For dynamic information, I'm not sure what the best solution for that problem is, but adding it to the trigger combination is wrong. 

I do have some ideas that make what asakawa is asking for somewhat possible, though not the exact thing. Hopefully some of that will be visible in this year.

**Comment by InfusOnWoW** [comment]
The new buff trigger will have a "highest remaining time" option for buffs.
