### ISSUE TITLE
Throttle "Display" code by default

### ISSUE THREAD

**Issue by blooblahguy** [WeakAuras/WeakAuras2#790]
**Is your feature request related to a problem? Please describe.**
It's increasingly common for me to find WAs that do all of their work inside of the display as "Update Every Frame". Often times this code is a new loop inside of the OnUpdate, calling UnitAuras or other information and these calls are expensive. i.e. There are multiple Uldir WAs circulating that loop through the raid roster, then loop through 40 for UnitAura with no breaks, all OnUpdate.

**Describe the solution you'd like**
Instead of novice developers having access to OnUpdate by default, the display update should be throttled to something around every 0.1s. Then experienced developers can create OnUpdate events when they actually need it. This is inverse of how things work now, and shouldn't necessarily break compatibility with existing WAs. Experienced devs can always do what they want within WAs, I think everyone else should have certain best practices 

**Describe alternatives you've considered**
Instead of always throttling, it could be a good idea to make a slider show up when %c is enabled in display with values ranging from 0 (OnUpdate) to 1.0 with 0.1 steps. This at least gives novice developers notice that where this slider is affects performance and gives them an easy avenue to provide better performing WAs.

**Additional context**
FPS issues in general have been a hot topic, and WAs itself is about as optimized as it can get. Many people just blame the FPS on "blizzard's change to UnitAura" but that answer is incomplete. Performance needs to be more front-facing when user's create WAs so that the end users don't just lose FPS and have no idea why without requesting support from devs.

**Comment by InfusOnWoW** [comment]
WeakAuras is not as optimized as it can be for buff tracking.

We certainly can't change the behaviour of OnUpate. I'm sceptical of adding a option for throttling, that's a option for less than 1% of all auras and adds complexity for everyone.

**Comment by Stanzilla** [comment]
I think he has a point about many people (and even many popular auras) using OnUpdate "wrong" so there might be some value in throttling.

**Comment by InfusOnWoW** [comment]
Yeah the benefit is there, my point is it matters for very few auras and we I'm not convinced it's that common of a problem.

**Comment by emptyrivers** [comment]
I’ll be the first to admit that there’s a lot of lazy and/or incompetent people who end up creating auras with extremely poor performance, but I don’t think enforcing this on high is going to be effective.

**Comment by Stanzilla** [comment]
Maybe wago should display a notice?

**Comment by emptyrivers** [comment]
That would need to be curated by hand to have a chance at success.

**Comment by emptyrivers** [comment]
As in, the most effective strategy there would be to mark wagos with known performance issues. But that needs humans who are willing to spend the time to review wagos, and also some sort of moderator system incorporated into wago.

Otherwise it’ll become just another warning that gets clicked through without a second thought.

**Comment by Causese** [comment]
how abount an "on event" thing for display? make it fire if certain events happen

maybe they feel forced into using everyframe cause the only other option is trigger update

**Comment by InfusOnWoW** [comment]
you are supposed to use the trigger with the right events, and use the text only to augment that information.

**Comment by Kha-Khan** [comment]
There are cases where a built-in display throttle would help me.  I think of things like the GCD snippet "To hide the cooldown "progress" text when the CD is triggered by the global" or doing things with nameplates.

**Comment by emptyrivers** [comment]
The custom text function is intended for one thing only, which is to give WeakAuras custom strings for it to use when replacing %cN patterns in text fields. Using it for other things is up to you, but ultimately I don’t think that reducing the impact of unsupported side effects is a good reason to impose this change on everyone.

**Comment by blooblahguy** [comment]
I think the above is valid, but it reinforces my alternative even more imo. Instead of forcing throttling by default, add a slider that allows for users to change the frequency of display update from 0.0 (OnUpdate) to 1.0 in increments of 0.1. This doesn't impose anything on existing auras, doesn't add any new steps for anyone who's creating a WA, and gives everyone the option to add simple throttling to their WAs.

I'm not sure how I can quantify how common this problem is, but I can tell you anecdotally that any time someone comes to me with FPS issues I find a WA with it's code in OnUpdate ~8 times out of 10. Well written popular suites may be optimized, but people almost always have oddball single weakaruas to track specific things in their UI and those ones are usually the culprits.

**Comment by Stanzilla** [comment]
Instead of a slider, a new entry in the dropdown would probably be smarter. Something like

```
Every Frame
Every Second
TSU
```

**Comment by emptyrivers** [comment]
The kind of person who never learns how to write code which doesn’t do anything more than it needs to also never bothers to learn any feature at all, beyond the first one which makes things go. If you actually pay attention, you’ll see plenty of poorly coded triggers, animations, actions, and custom texts. This is certainly not a problem that is limited solely to custom text. I’m not really against adding an every x time update for text and even for custom triggers, but I sincerely doubt that it would be effective in improving the crap that some authors create.

**Comment by blooblahguy** [comment]
There's a big difference between learning how to code and dragging a slider. Someone not knowing how to code does not automatically make them the kind of person that ignores everything right in front of their face. I get your point that there will be people who continue to do things wrong, but this will absolutely be effective is helping people make better optimized weak auras.

**Comment by InfusOnWoW** [comment]
The slider won't help them write better code, and certainly not help them make optimized auras.

**Comment by Zinoh** [comment]
Slightly off-topic, but are animations throttled at all by WeakAuras? If not, would there be any value in having that option or are animations pretty light performance-wise?

**Comment by asakawa-k** [comment]
Throttling animations would just make for stuttery animations. Their nature requires them to run every frame.

**Comment by blooblahguy** [comment]
It would help them make more optimized WeakAuras, that's exactly the point of it. How would it not? Not to mention is would be a generally useful feature for all level of devs to be able to throttle their display updates.

**Comment by InfusOnWoW** [comment]
No, it will make people make wrong use of having everything in a on frame update custom function. 

So adding that option would lead to worse auras, because it leads people unto the wrong path.

**Comment by Stanzilla** [comment]
We're currently thinking about the OnUpdate option for display custom code with "OnTrigger"

**Comment by Vrakfall** [comment]
@blooblahguy has a point right as this could help the end-user, not versed in the art of coding, to identify displays that are making his interface lag when it shouldn't.

What about detecting an abnormal amount of `OnUpdate` calls, like a certain percentage of frames on which it was used, or detecting if some auras take an abnormal amount of time/CPU time per second and then throw en error if that amount is too high/on every frame? Or both? The bad coder would instantly see something in his code shouldn't be coded that way as a feedback message would be spamming his chat (and maybe his `BugSack`) and the user of those `displays` would be informed that some of his displays are sucking the hell out of his CPU time.

It would then be possible to cancel that error throw with a function call with a specific argument: I'm thinking about a boolean or a specific string like "I acknowledged my code is taking too much CPU time and assert that it is for a justifiable reason.". That would then require the bad coder to check the documentation where he would be explained why he shouldn't be doing that in the first place, he would then be given the `API` call to make in order to stop the error to being thrown, for genuine usage.

It would also allow for easy detection in `wago` of that function call which makes it possible to programmatically alert the end-user that the display is probably doing something terribly non-efficient while leaving the possibility for the author to justify why he couldn't do it another way.

Now I'm thinking about it, it could also require a button in the display's options in order for the end-user to voluntarily keep using poorly coded ones. The problem being that the bad coder could just check that checkbox and getting away with it without having to check the documentation. A solution could be to open a pop-up (when ticking that checkbox) with information from the documentation telling this is probably wrong. It could also be possible to add a warning like this at importation time for the end-user.

This idea just creates the problem for implementing this as to how to detect the abnormal cpu usage: solely referring to the time being used would lead to displays not throwing errors on some machine while throwing it on some others. Though, using a percentage of calls on a certain number of frames should actually trigger the same way along every machine. Maybe there's is even a better detection way.
It also assumes the author tested his display before publishing it, which is needed for him to acknowledge the error thrown at execution time.

**Comment by InfusOnWoW** [comment]
All that complexity for what? We are talking about a issue with a few auras, that's far too complex for the benefit it would bring.

We do have a profiling feature that can help identify which auras are problematic.

**Comment by emptyrivers** [comment]
On hold until #913 is released. Then, we will re-evaluate whether or not this request has any further merit.

**Comment by emptyrivers** [comment]
So.... 2.14 contains a pretty large rewrite to texts, making the system a lot more powerful. Is this feature still something that people want?

**Comment by blooblahguy** [comment]
I think it would still make a great addition. I still find myself fixing other people's WAs all the time to help people get better performance.

**Comment by InfusOnWoW** [comment]
I still think this is a misguided idea, the custom text functions should not be used to run arbitary complex code. A option to mitigate the effect of using it wrong, is thus wrong. It signals to people that what they are doing is the right thing. 

And it's been 9 month, clearly nothing will come from this ticket.
