### ISSUE TITLE
Improve group batch editing performance

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#821]
All edits go through `WeakAuras.Add` (and most also go through `ReloadOptions` or `ReloadTriggerOptions` too), and those aren’t the cheapest of operations

So if you are making a bulk change, those will get called many times in the same frame

Basically the code that calls `ReloadTriggerOptions` for each individual edit, doesn't know that it is part of a bulk edit and since the API between the calling and executing code is the API that Ace options gives us, that isn't entirely trivial to fix, though it shouldn't be impossible

**Comment by mrbuds** [comment]
While looking at where ReloadTriggerOptions is called, i saw that WeakAuras.EnsureOptions(id) call WeakAuras.AddOption(id, data) which call WeakAuras.ReloadTriggerOptions

PickDisplay() for example use WeakAuras.EnsureOptions and also WeakAuras.ReloadTriggerOptions, so options are reloaded 2 times here

I tested to remove that call in WeakAuras.AddOption and .. ok i don't know 100% what i'm doing but it looks fine

**Comment by emptyrivers** [comment]
`WeakAuras.FillOptions` is our entry point to Ace, and must be called in order to refresh the options interface. `WeakAuras.ReloadOptions` and `WeakAuras.ReloadTriggerOptions` reconstruct the options table we give to Ace. Some options interactions necessitate that we Reload the options, but not all of them. For example, setting the color on an icon doesn't require a change in the design of the rest of the interface.

I think a longer term project to improve performance here will be to examine the places where we call `ReloadOptions` and `ReloadTriggerOptions`, and see if we can't reduce that to just `FillOptions` with a find & replace, or a small tweak in surrounding code.

**Comment by emptyrivers** [comment]
Eh, ReloadOptions is actually just a wrapper for FillOptions, which ensures that the options actually exists. But my point still stands about ReloadTriggerOptions, I guess.

**Comment by InfusOnWoW** [comment]
I'm researching some ways to make this better, and as part of #913, I'm actually introducing a new way to reload the options.

**Comment by emptyrivers** [comment]
It would also be nice to thread-ify editing a group, so that large groups do not hang the game quite so much. Additionally, some users import groups which are so large that they run into edits that take too long, and blizzard terminates the thread before it is done.

**Comment by InfusOnWoW** [comment]
https://wago.io/kR7bGhWG5 is a good set of auras to test.

**Comment by Stanzilla** [comment]
Just tested and works wonders for perf
