### ISSUE TITLE
[2.8.1] "Add Overlay" option in custom trigger when using an Icon type. 

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#842]
I just noticed that the "Add Overlay" button is visible when using an Icon type Aura. I don't _think_ this was always the case but might be mistaken. It causes no ill effects as far as I can tell, it just does nothing.

**Comment by InfusOnWoW** [comment]
That's because triggers don't know what informatin is used by what aura type. E.g. for a plain texture you also get the full set of custom functions, even though the plain texture doesn't make use of any of that information. We could improve that, but in general unless there's a huge reason I don't want triggers to acutally know anything about the regions their information is used in.
