### ISSUE TITLE
Random Sound From List

### ISSUE THREAD

**Issue by WadeWilsonWannabe** [WeakAuras/WeakAuras2#850]
It would be nice to be able to play a random sound from a list as an alert. I would use it for random sounds when a spell is cast (custom recording). I have tried using the PlaySoundFile() in the On_Show Custom code area with the proper sound path, yet nothing plays.

I have done PlaySoundFile("Interface\AddOns\WeakAuraSounds\MoarDotz.ogg", "Master") and PlaySoundFile("Interface\\AddOns\\WeakAuraSounds\\MoarDotz.ogg", "Master") both of which fail.

So adding a feature allowing a random sound from a list would be easy and allow some cool customization for sounds so people don't get tired of sounds so quickly.

**Comment by emptyrivers** [comment]
Random sound effects are very easy to produce using custom code, via math.random or GetRandomArgument.

As for sounds not playing? Make sure you've done everything on this list:

1. Sound files must be .ogg or .mp3 format, and Textures must be .blp or .tga format. Fonts must be .ttf format.

2. A texture must have dimensions that are powers of 2 (32x32 and 64x512 are allowed, but 40x40 is not, for example).

3. The file must be located somewhere within the World of Warcraft folder, this is usually found at C:\Program Files (x86)\World of Warcraft. You can put it in any subfolder within this folder, but it's not recommended to place it within Interface\addons, since addon managers will muck around with those files and change the contents without your explicit knowledge.

4. When referencing the filepath, remember that it is relative - C:\Program Files (x86)\World of Warcraft\Interface\CustomSounds\MyCustomSound.ogg is wrong. Use Interface\CustomSounds\MyCustomSound.ogg instead. If you are using the filepath in a script, then enclose it in double square brackets, like so: 
PlaySoundFile([[Interface\CustomSounds\MyCustomSound.ogg]])

5. Spelling is important! Make sure that you didn't misspell some folder name, or capitalize wrongly. For best results, copy the file path directly from Explorer.

6. When adding a new file, or changing the name or file location of the file, you must exit the game entirely, or the new file won't be recognized!

If you have done all of this, and your file still does not seem to work, then there is something wrong with the file itself. Double check that you didn't encode the audio at 0 volume, or that the opacity of your texture isn't zero, or something similar to that.

**Comment by Stanzilla** [comment]
WeakAuras is designed to alert you about very specific things, I don't see a way where a random factor would play into that. So I vote nay

**Comment by InfusOnWoW** [comment]
And 7. if you still need help, come to the discord and mention your problem.

**Comment by WadeWilsonWannabe** [comment]
Thanks for the input. I didn't see anywhere that I needed the double brackets in the PlaySoundFile parentheses. I added this to my custom script (already had the math.random down) and worked like a charm. This is going to go well with the custom sounds I'm doing for the shadow priest (random maniacle laughing when casting mindflay, random whispers of "pain" or "embrace" on cast. As if the shadows are speaking to you. 
Thinking of doing some percentage math so it plays one of the random sounds X% of the times you cast.

**Comment by InfusOnWoW** [comment]
And that last point is another good reason why custom code is sometimes the best solution.
