### ISSUE TITLE
Event triggers - custom hide: what to do with it ?

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#897]
Currently all "Event" triggers share the same untrigger "Hide" select widget
- Custom
- Timed

"Custom" duplicate some of the trigger's fields and allow user to set different values.

Problems:
- untrigger event have to be a variation of the same event use for trigger, you can't mix them. Like use a chat message event as trigger and a CLEU as untrigger.
- "Clone per Event" option is duplicated (i don't know how it's working), ex: BW, DBM, Chat Message, CLEU.
- The option doesn't work for some events, ex: Cooldown Ready, Ready Check, Entering Combat.
- CLEU don't let set another Message Prefix/Suffix for untrigger.

Possible solutions:
- Get rid of this option, and leave "Time" as default untrigger
- Replace it with a field "event" + a field "custom code" (wasn't it done like that before?)
- Something that let you select another event trigger as untrigger

What do you think ?

**Comment by asakawa-k** [comment]
In WoW, during the old "tree" talent system, the Devs used to talk about certain talents being a "trap". They looked good but were always a bad choice. I feel that the custom untrigger option is basically like that right now, on all non-custom trigger types, both Event and Status. So although it might seem like giving up, I don't see optionA as a bad one tbh.

(a side not about Status triggers which is a little off topic, currently you can set a custom untrigger on a health trigger, for example, and that looks appealing to people who think it is the way to show health levels between two given points. In that way it is a "trap" because it actually allows them to set different health levels for going up and another for going down, something that, really, nobody ever does. )

I'm not sure what single custom code snippet you could put in to a custom untrigger (optionB). But if a reasonable format were set up then it would be an option that would make sense, I think, though it wouldn't be used much since, if people can do code then they will use a full custom trigger. 

OptionC would be ideal.

**Comment by InfusOnWoW** [comment]
I have fixed bugs in the custom untrigger code, because people report bugs in that code multiple times. So removing it is not a option.

**Comment by emptyrivers** [comment]
Did we ever come to a decision on this, or did people forget about the ticket?

**Comment by mrbuds** [comment]
I want to do a complete audit of all triggers with a "Hide" option, see what is working or not, and from there we can discuss for each one what needs to be done.

**Comment by mrbuds** [comment]
https://github.com/WeakAuras/WeakAuras2/projects/7

**Comment by emptyrivers** [comment]
@mrbuds have you completed your audit yet? There are still 4 cards left in the “to audit” column of that project.

**Comment by mrbuds** [comment]
There are still 4 cards left, because i have no idea how to test them.
Out of 12 triggers with a custom hide, only 2 of them works, and they still have an option that break it.
The option is broken and should either be dropped, or rewrite from scratch.
The best way to handle it would be to use an other trigger for the hide logic.
Considering the amount of work needed, and how niche this option is (we rarely hear complains about it), custom code fill that niche pretty well, my conclusion is we better remove it.

Maybe some usage stats of this option from wago could help make a final decision ? @oratory

**Comment by InfusOnWoW** [comment]
I'll take a look at those triggers soonish.

**Comment by InfusOnWoW** [comment]
This is mostly fixed.
