### ISSUE TITLE
Multi-Target Buff trigger misses some debuff re-applications

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#916]
WA doesn't catch the dot extension when the player uses the CD "Summon Darkglare" due to there being no CLEU event that's passed to notify the client of the dot duration change.

**Comment by InfusOnWoW** [comment]
Also see https://www.wowace.com/projects/weakauras-2/issues/1264

**Comment by emptyrivers** [comment]
So, is there anything we can do about this? It seems like this is just another limitation of the multi-target buff trigger, honestly.

**Comment by 1ps3** [comment]
I think the multi-target trigger at the moment uses some amalgamation of unit_aura and cleu, where it checks cleu first then get the info on unit_aura, what if it was just changed to unit aura.

**Comment by emptyrivers** [comment]
What you said isn't very coherent. Multi-target works on the hope that any GUID it gets via the combat log can also be found as a valid unitID. The problem here is that Darkglare's targets are not always reference-able as a valid unitID, unless you enjoy `/assist`ing your Darkglare summon.

That doesn't really have anything to do with my question, though.

**Comment by emptyrivers** [comment]
Well, I just realized that there actually is a suggestion in your message. WeakAuras actually does listen to UNIT_AURA for most possible units when you choose a multi-target buff trigger. That's just not enough sometimes.
