### ISSUE TITLE
Buff Trigger 2 Custom Support

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#937]
Recently in the discord we've been getting a few requests about the ability to use buff trigger 2 in custom code. It'd be a pretty nice addition to be able to use it, either by getting wa to pass fake BUFF_TRIGGER events or direct access to the cached info.

**Comment by InfusOnWoW** [comment]
asakawa:
Example https://wago.io/RaidBuffCheck
I want to check range info only on those people that need to be checked (are unbuffed).
The immediate way people made these was to iterate the raid on every frame, check their buff, check their range, return info.
In the system Ipse is asking for, we would request unbuffed group members and check range on them.

Ipse:
The only examples I can think of can obviously be handled by the user with the appropriate events to avoid using ever frame. Like imagine you wanted to count the amount of buff on nameplates and use that info somewhere else. You could just get that info from wa whenever you wanted instead of having to jump through all the hoops to get it yourself

asakawa:
I guess it all boils down to using WA to gather units based on buffs in some way, then using that list of units to display some other info: 
- debuffed people in range - buffed people with health below 20% Or using WA to get info about units affected by more than one buff/debuff so that you can use some logic that correlates the multiple effects: - units that have debuff A but don't have debuff B

Perhaps another one would be gathering people affected with a buff, but you want to display the info in a way that WA doesn't directly support, like showing stacks as progress on a bar: 
- Mythrax stacks

**Comment by emptyrivers** [comment]
The times in which I've seen this request most often is when someone asks how BuffTrigger2 works. After having it explained to them, they then ask if `WA_GetUnitBuff` does the same thing (which it obviously doesn't).

In my experience, the majority of points in which someone is using `WA_GetUnitBuff` and would benefit from being able to access cached data is because they're calling `WA_GetUnitBuff` in some code that runs very frequently, or similar. And in pretty much all cases for that, there is a solution which involves either the author simply writing better code, or us adding some functionality (like how #913 solves #929, but with buff queries instead of an item query).

**Comment by InfusOnWoW** [comment]
The "difficult" point in designing this, is that the bufftrigger2 code wants to know which names/spellIds/unit combinations to track before for optimal performance.

So, in a way any custom code must be able to register itself with that information and also unregister itself when it doesn't need that information e.g. on being deleted.

That's not something a current custom trigger could do.

I can think of two potential solutions:
* Make a fully generic proxy trigger. That's something I loosely considered as one of the future directions which the introduction of states allows. That is the input for the proxy are the states of all triggers and the ouput are the states that should be displayed. (Or new states that the proxy generated.)  That could be useful to in general be able to combine/augment information from multiple standard triggers. There are lots of pontential benefits to that, but it sounds like a gigantic project.

* Add a "custom" buff trigger, which essentially replaces UpdateTrigerState with a custom function. That function has as a input the match data and its output are the states to display. So the user could use most of the existing options to filter down what is passed into the function and then generates the states based on that.

**Comment by InfusOnWoW** [comment]
That's to early to tell, which and how a potential future evolution into supporting custom code is done, depends on what other feature requests we get for the trigger and what other use cases come up.

Though b) sounds pretty hard to do.

**Comment by asakawa-k** [comment]
Indeed. From my point if view I've not yet needed to add units/spells programmatically, (b).

For accessing states across triggers (or even across Auras?), (a), the main issues I see are that:
    
* going through triggerState is awkward 
  * mostly due to the cloneId key being an empty string on non-cloning Auras, while `aura_env.cloneId` does not always match
* To make it effective/efficient you would ideally have "events" fired when a state is changed. 
  * Workarounds I've used include firing a ScanEvents from Custom Activation or Trigger Update Custom Text. Or just running every frame :(

**Comment by asakawa-k** [comment]
Additional use case came up on Discord:
`Ok guys, is it possible to create a weakauras to show people affected by certain debuff but with HEALTH as the progressbar not the remaining time?`
Fits the (a) mould.

**Comment by emptyrivers** [comment]
@InfusOnWoW, did you ever come to a decision on any action that we can take with this, or has this ticket fallen by the wayside?

**Comment by InfusOnWoW** [comment]
We now have a method for custom triggers to watch other triggers, which for now is probably good enough.

The bt2 conceptually (though the code doesn't separate that cleanly) is 3 phases:
1) Unit Selection (that is e.g. the unit type, class, spec, role filter)
2) Matching (That is check the trigger against a specific UnitAura return, there's a bit of magic here to ensure that the trigger's that have name or spell id filter, are only checked if necessary)
3) State Selection/Generation (Depending on the trigger settings, all matches, or the "best" match is selected

Theoretically custom trigger support could mean having a way to adjust any of these steps. Let's see how the new watch trigger functionality is used, and maybe revisit this at a later point.
